fix(ci): add missing inputs and rpm delivery refacto

diff --git a/.github/actions/rpm-delivery/action.yml b/.github/actions/rpm-delivery/action.yml
--- a/.github/actions/rpm-delivery/action.yml
+++ b/.github/actions/rpm-delivery/action.yml
@@ -40,6 +40,9 @@ inputs:
   stability:
     description: "The package stability (stable, testing, unstable)"
     required: true
+  artifactory_token:
+    description: "Token for artifactory"
+    required: true
 
 runs:
   using: "composite"
@@ -60,6 +63,10 @@ runs:
 
     - name: Publish RPMS to Nexus
       run: |
+        PROJECT_LOCATIONS=""
+        INVALIDATION_PATHS=""
+        METADATAS=""
+
         FILES="*.rpm";
         echo "[DEBUG] - Rpm FILES: $FILES"
 
@@ -69,46 +76,77 @@ runs:
         for FILE in $FILES
         do
           echo "[DEBUG] - File: $FILE"
+
           VERSION=${{ inputs.version }}
-          DISTRIB=$(echo $FILE | grep -oP 'el[0-9]')
+
+          if [ -z "${{ inputs.distrib }}" ]; then
+            DISTRIB=$(echo $FILE | grep -oP 'el[0-9]' || echo '')
+          else
+            DISTRIB="${{ inputs.distrib }}"
+          fi
+          if [ -z "${DISTRIB}" ]; then
+            echo "package distribution not set"
+            exit 1
+          fi
+
           ARCH=$(echo $FILE | grep -oP '(x86_64|noarch)')
+
           echo "[DEBUG] - Version: $VERSION"
           echo "[DEBUG] - Distrib: $DISTRIB"
           echo "[DEBUG] - Arch: $ARCH"
 
           MAJOR=$VERSION
+          MINOR=${{ inputs.minor_version }}
+          RELEASE=${{ inputs.release }}
           DISTRIB=$DISTRIB
           REPOTYPE=${{ inputs.stability }}
           ARCH=$ARCH
           PROJECT=${{ inputs.module_name }}
-          FOLDER=$(basename $FILE .rpm)
           PROJECT_PATH="standard"
-          TARGET="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH/$PROJECT/$FOLDER"
-          PROJECT_LOCATION="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH/$PROJECT"
-          METADATAS="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH"
+
+          # Delivery with proper repository structure according to stability
+          if [ "${{ inputs.stability }}" == stable ]; then
+            TARGET="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH/RPMS"
+            curl -v -H "Authorization: Bearer ${{ inputs.artifactory_token }}" -X PUT "https://centreon.jfrog.io/artifactory/rpm/$PROJECT_PATH/$MAJOR/$DISTRIB/${{ inputs.stability }}/$ARCH/$FILE" -T "./$FILE"
+          else
+            FOLDER="centreon-$PROJECT-$MAJOR.$MINOR-$RELEASE"
+            TARGET="/srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH/$PROJECT/$FOLDER"
+            PROJECT_LOCATIONS="$PROJECT_LOCATIONS /srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH/$PROJECT"
+            curl -v -H "Authorization: Bearer ${{ inputs.artifactory_token }}" -X PUT "https://centreon.jfrog.io/artifactory/rpm/$PROJECT_PATH/$MAJOR/$DISTRIB/${{ inputs.stability }}/$ARCH/$PROJECT/$FOLDER/$FILE" -T "./$FILE"
+          fi
 
           echo "[DEBUG] - Folder: $FOLDER"
           echo "[DEBUG] - Project : $PROJECT"
           echo "[DEBUG] - Target : $TARGET"
-          echo "[DEBUG] - PROJECT_LOCATION : $PROJECT_LOCATION"
 
           ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" mkdir -p "$TARGET" 2>&-
           scp -o StrictHostKeyChecking=no "$FILE" "${{ inputs.yum_repo_address }}:$TARGET" 2>&-
-          #ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "ls -drc $PROJECT_LOCATION/* 2>&- | head -n -6 | xargs rm -rf"
+          METADATAS="$METADATAS /srv/centreon-yum/yum.centreon.com/$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH"
+          INVALIDATION_PATHS="$INVALIDATION_PATHS /$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH/*"
         done
 
-        ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "sh "${{ inputs.update_repo_path }}" $METADATAS" 2>&-
+        # Cleanup is done on unstable repository only
+        if [ "${{ inputs.stability }}" == unstable ]; then
+          PROJECT_LOCATIONS=`echo "$PROJECT_LOCATIONS" | xargs -n1 | sort -u | xargs`
+          for PROJECT_LOCATION in `echo $PROJECT_LOCATIONS`; do
+            ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "ls -drc $PROJECT_LOCATION/* 2>&- | head -n -1 | xargs rm -rf"
+          done
+        fi
 
+        # Invalidate cloudfront cache
         ID="${{ inputs.cloudfront_id }}"
-        PATHS="/$PROJECT_PATH/$MAJOR/$DISTRIB/$REPOTYPE/$ARCH/*"
+        # Remove duplicated invalidation paths
+        INVALIDATION_PATHS=`echo "$INVALIDATION_PATHS" | xargs -n1 | sort -u | xargs`
         ITERATIONS=1
 
-        until aws cloudfront create-invalidation --distribution-id "$ID" --paths "$PATHS"; do
-          if [ ${ITERATIONS} -eq 10 ]; then
-            return 0
-          fi
-          echo "couldn't invalidate cache, AWS quota might have been reached, retrying in 30 seconds..."
-          sleep 30s
-          ITERATIONS=$((ITERATIONS+1))
+        for INVALIDATION_PATH in `echo $INVALIDATION_PATHS`; do
+          until aws cloudfront create-invalidation --distribution-id "$ID" --paths "$INVALIDATION_PATH"; do
+            if [ ${ITERATIONS} -eq 10 ]; then
+              return 0
+            fi
+            echo "couldn't invalidate cache, AWS quota might have been reached, retrying in 30 seconds..."
+            sleep 30s
+            ITERATIONS=$((ITERATIONS+1))
+          done
         done
       shell: bash
