chore(ci): add repo esr to 22.10 rpm delivery

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -59,65 +59,68 @@ runs:
         if [[ ${{ inputs.github_ref_name }} == "master" ]]; then
           ROOT_REPO_PATH="rpm-standard-internal"
         else
-          ROOT_REPO_PATH="rpm-standard"
+          ROOT_REPO_PATH=("rpm-standard" "rpm-standard-esr")
         fi
 
-        # Search for testing packages candidate for promote
-        for ARCH in "noarch" "x86_64"; do
+        # Process both repo (double promote)
+        for ROOT_REPO_PATH in "${ROOT_REPO_PATHS[@]}";do
+          # Search for testing packages candidate for promote
+          for ARCH in "noarch" "x86_64"; do
 
-          # Build search path based on release_cloud and release_type values
-          # if cloud, search in testing-<release_type> path
-          # if non-cloud, search in the testing usual path
-          if [[ ${{ inputs.release_cloud }} -eq 1 && ${{ inputs.release_type }} == "hotfix" ]] || [[ ${{ inputs.release_cloud }} -eq 1 && ${{ inputs.release_type }} == "release" ]];then
-            SEARCH_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/testing-${{ inputs.release_type }}/$ARCH/${{ inputs.module }}"
-          elif [[ ${{ inputs.release_cloud }} -eq 0 ]];then
-            SEARCH_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}"
-          else
-            echo "Invalid combination of release_type and release_cloud"
-          fi
+            # Build search path based on release_cloud and release_type values
+            # if cloud, search in testing-<release_type> path
+            # if non-cloud, search in the testing usual path
+            if [[ ${{ inputs.release_cloud }} -eq 1 && ${{ inputs.release_type }} == "hotfix" ]] || [[ ${{ inputs.release_cloud }} -eq 1 && ${{ inputs.release_type }} == "release" ]];then
+              SEARCH_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/testing-${{ inputs.release_type }}/$ARCH/${{ inputs.module }}"
+            elif [[ ${{ inputs.release_cloud }} -eq 0 ]];then
+              SEARCH_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}"
+            else
+              echo "Invalid combination of release_type and release_cloud"
+            fi
 
-          echo "[DEBUG] - Get path of $ARCH testing artifacts to promote to stable."
-          SRC_PATHS=$(jf rt search --include-dirs $ROOT_REPO_PATH/$SEARCH_REPO_PATH/*.rpm | jq -r '.[].path')
+            echo "[DEBUG] - Get path of $ARCH testing artifacts to promote to stable."
+            SRC_PATHS=$(jf rt search --include-dirs $ROOT_REPO_PATH/$SEARCH_REPO_PATH/*.rpm | jq -r '.[].path')
 
-          if [[ ${SRC_PATHS[@]} ]]; then
-            for SRC_PATH in ${SRC_PATHS[@]}; do
-              echo "[DEBUG] - Source path found: $SRC_PATH"
+            if [[ ${SRC_PATHS[@]} ]]; then
+              for SRC_PATH in ${SRC_PATHS[@]}; do
+                echo "[DEBUG] - Source path found: $SRC_PATH"
+              done
+            else
+              echo "[DEBUG] - No source path found for $ARCH."
+              NO_PATHS_FOUND_IN_ARCH+=1
+            fi
+
+            if [[ $NO_PATHS_FOUND_IN_ARCH -eq 2 ]]; then
+              echo "[DEBUG] - No source path found in all architecture."
+              exit 1
+            fi
+
+            # Build target path based on ARCH
+            echo "[DEBUG] - Build $ARCH target path."
+            TARGET_PATH="$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/stable/$ARCH/RPMS/${{ inputs.module }}/"
+            echo "[DEBUG] - Target path: $TARGET_PATH"
+
+            # Download candidates for promote
+            echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
+            for ARTIFACT in ${SRC_PATHS[@]}; do
+              echo "[DEBUG] - Downloading $ARTIFACT from TESTING."
+              jf rt download $ARTIFACT --flat
             done
-          else
-            echo "[DEBUG] - No source path found for $ARCH."
-            NO_PATHS_FOUND_IN_ARCH+=1
-          fi
 
-          if [[ $NO_PATHS_FOUND_IN_ARCH -eq 2 ]]; then
-            echo "[DEBUG] - No source path found in all architecture."
-            exit 1
-          fi
+            DRY_RUN_FLAG="--dry-run"
+            if [ "${{ inputs.stability }}" == "stable" ]; then
+              DRY_RUN_FLAG=""
+            fi
 
-          # Build target path based on ARCH
-          echo "[DEBUG] - Build $ARCH target path."
-          TARGET_PATH="$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/stable/$ARCH/RPMS/${{ inputs.module }}/"
-          echo "[DEBUG] - Target path: $TARGET_PATH"
+            # Upload previously downloaded candidates to TARGET_PATH
+            for ARTIFACT_DL in $(dir|grep -E "*.rpm"); do
+              echo "[DEBUG] - Promoting (upload) $ARTIFACT_DL to stable $TARGET_PATH."
+              jf rt upload "$ARTIFACT_DL" "$TARGET_PATH" --flat $DRY_RUN_FLAG
+            done
 
-          # Download candidates for promote
-          echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
-          for ARTIFACT in ${SRC_PATHS[@]}; do
-            echo "[DEBUG] - Downloading $ARTIFACT from TESTING."
-            jf rt download $ARTIFACT --flat
+            # Cleanup before next round of candidates
+            rm -f *.rpm
           done
-
-          DRY_RUN_FLAG="--dry-run"
-          if [ "${{ inputs.stability }}" == "stable" ]; then
-            DRY_RUN_FLAG=""
-          fi
-
-          # Upload previously downloaded candidates to TARGET_PATH
-          for ARTIFACT_DL in $(dir|grep -E "*.rpm"); do
-            echo "[DEBUG] - Promoting (upload) $ARTIFACT_DL to stable $TARGET_PATH."
-            jf rt upload "$ARTIFACT_DL" "$TARGET_PATH" --flat $DRY_RUN_FLAG
-          done
-
-          # Cleanup before next round of candidates
-          rm -f *.rpm
         done
       shell: bash
 
