fix

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -71,7 +71,7 @@ runs:
         echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
         for ARCH in "noarch" "x86_64"; do
           echo "[DEBUG] - Get artifactory path of $ARCH testing artifacts to promote to stable."
-          SRC_PATHS=$(jf rt s --include-dirs rpm-standard/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}/*.rpm | jq -r '.[].path')
+          SRC_PATHS=$(jf rt search --include-dirs rpm-standard/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}/*.rpm | jq -r '.[].path')
           if [[ ${SRC_PATHS[@]} ]]; then
             for SRC_PATH in ${SRC_PATHS[@]}; do
               echo "[DEBUG] - Source path found: $SRC_PATH"
@@ -91,7 +91,43 @@ runs:
         done
       shell: bash
 
-    - name: Promote RPM packages to stable on yum.centreon.com
+    - name: Promote DEB package to stable
+      if: ${{ startsWith(inputs.distrib, 'bullseye') }}
+      run: |
+        set -x
+        echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
+        echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
+        echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
+        echo "[DEBUG] - Repository name: ${{ inputs.repository_name }}"
+
+        if [[ "${{ inputs.repository_name }}" == "standard" ]]; then
+          ROOT_REPO_PATH="apt-standard-${{ inputs.major_version }}"
+        else
+          echo "Invalid repository name: ${{ inputs.repository_name }}"
+          exit 1
+        fi
+
+        echo "[DEBUG] - Get path of testing DEB packages to promote to stable."
+        SRC_PATHS=$(jf rt search --include-dirs $ROOT_REPO_PATH-testing/pool/${{ inputs.module }}/*${{ inputs.major_version }}.${{ inputs.minor_version }}*.deb | jq -r '.[].path')
+        if [[ ${SRC_PATHS[@]} ]]; then
+          for SRC_PATH in ${SRC_PATHS[@]}; do
+            echo "[DEBUG] - Source path found: $SRC_PATH"
+          done
+        else
+          echo "[DEBUG] - No source path found."
+          continue
+        fi
+        echo "[DEBUG] - Build target path."
+        TARGET_PATH="$ROOT_REPO_PATH-${{ inputs.stability }}/pool/"
+        echo "[DEBUG] - Target path: $TARGET_PATH"
+        echo "[DEBUG] - Promoting DEB testing artifacts to stable."
+        for ARTIFACT in ${SRC_PATHS[@]}; do
+          echo "[DEBUG] - Promoting $ARTIFACT to stable."
+          #jf rt cp $ARTIFACT $TARGET_PATH --flat=true
+        done
+      shell: bash
+
+    - name: Promote RPMS packages to stable on yum.centreon.com
       if: ${{ startsWith(inputs.distrib, 'el') }}
       run: |
         set -x
@@ -131,12 +167,16 @@ runs:
           #TARGET_PATH="/srv/centreon-yum/yum.centreon.com/$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/canary/$ARCH/RPMS"
           echo "[DEBUG] - Target path: $TARGET_PATH"
           echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
+          ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" mkdir -p "$TARGET_PATH"
           for ARTIFACT in ${SRC_PATHS[@]}; do
+            echo "[DEBUG] - Promoting $ARTIFACT to $TARGET_PATH."
             ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" mkdir -p "$TARGET_PATH"
             #ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" cp $ARTIFACT $TARGET_PATH/
-            METADATAS="METADATAS /srv/centreon-yum/yum.centreon.com/$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH"
-            INVALIDATION_PATHS="$INVALIDATION_PATHS /$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/*"
           done
+
+          METADATAS="METADATAS /srv/centreon-yum/yum.centreon.com/$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH"
+          INVALIDATION_PATHS="$INVALIDATION_PATHS /$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/*"
+
         done
         # Update repository metadata
         METADATAS=`echo "$METADATAS" | xargs -n1 | sort -u | xargs`
@@ -157,40 +197,6 @@ runs:
             sleep 30s
             ITERATIONS=$((ITERATIONS+1))
           done
-        done
-      shell: bash
-
-    - name: Promote DEB package to stable
-      if: ${{ startsWith(inputs.distrib, 'bullseye') }}
-      run: |
-        set -x
-        echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
-        echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
-        echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
-        echo "[DEBUG] - Repository name: ${{ inputs.repository_name }}"
-        if [[ "${{ inputs.repository_name }}" == "standard" ]]; then
-          ROOT_REPO_PATH="apt-standard-${{ inputs.major_version }}"
-        else
-          echo "Invalid repository name: ${{ inputs.repository_name }}"
-          exit 1
-        fi
-        echo "[DEBUG] - Get path of testing DEB packages to promote to stable."
-        SRC_PATHS=$(jf rt search --include-dirs $ROOT_REPO_PATH-testing/pool/${{ inputs.module }}/*${{ inputs.major_version }}.${{ inputs.minor_version }}*.deb | jq -r '.[].path')
-        if [[ ${SRC_PATHS[@]} ]]; then
-          for SRC_PATH in ${SRC_PATHS[@]}; do
-            echo "[DEBUG] - Source path found: $SRC_PATH"
-          done
-        else
-          echo "[DEBUG] - No source path found."
-          continue
-        fi
-        echo "[DEBUG] - Build target path."
-        TARGET_PATH="$ROOT_REPO_PATH-${{ inputs.stability }}/pool/"
-        echo "[DEBUG] - Target path: $TARGET_PATH"
-        echo "[DEBUG] - Promoting DEB testing artifacts to stable."
-        for ARTIFACT in ${SRC_PATHS[@]}; do
-          echo "[DEBUG] - Promoting $ARTIFACT to stable."
-          #jf rt cp $ARTIFACT $TARGET_PATH --flat=true
         done
       shell: bash
 
@@ -228,7 +234,7 @@ runs:
             curl -JOs $SRC_PATH
             FILENAME=$(basename $SRC_PATH)
             echo "[DEBUG] - Promoting testing artifact $FILENAME to stable."
-            #curl -s -u "${{ inputs.nexus_username }}":"${{ inputs.nexus_password }}" -H "Content-Type: multipart/form-data" --data-binary "@./$FILENAME" $TARGET_PATH
+            #curl --fail -s -u "${{ inputs.nexus_username }}":"${{ inputs.nexus_password }}" -H "Content-Type: multipart/form-data" --data-binary "@./$FILENAME" $TARGET_PATH
             rm -f $FILENAME
             sleep 2
           done
