add promote to rpm

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -10,6 +10,12 @@ inputs:
   distrib:
     description: "The distribution used for packaging"
     required: true
+  nexus_username:
+    description: "Artifact Manager technical username"
+    required: true
+  nexus_password:
+    description: "Artifact Manager technical password"
+    required: true
   major_version:
     description: "Centreon packaged major version"
     required: true
@@ -34,6 +40,9 @@ inputs:
   yum_repo_key:
     description: "The repo key"
     required: true
+  token_download_centreon_com:
+    description: "The token for download.centreon.com"
+    required: true
 
 runs:
   using: "composite"
@@ -42,6 +51,13 @@ runs:
       env:
         JF_URL: https://centreon.jfrog.io
         JF_ACCESS_TOKEN: ${{ inputs.artifactory_token }}
+
+    - name: Setup awscli
+      run: |
+        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+        sudo unzip -q awscliv2.zip
+        sudo ./aws/install
+      shell: bash
 
     - name: Promote RPM packages to stable
       if: ${{ startsWith(inputs.distrib, 'el') }}
@@ -67,45 +83,80 @@ runs:
           echo "[DEBUG] - Build $ARCH artifactory target path."
           TARGET_PATH="rpm-standard/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/RPMS/"
           echo "[DEBUG] - Target path: $TARGET_PATH"
-          echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
 
+          echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
           for ARTIFACT in ${SRC_PATHS[@]}; do
             echo "[DEBUG] - Promoting $ARTIFACT to stable on artifactory."
-            jf rt cp $ARTIFACT $TARGET_PATH --flat=true
+            #jf rt cp $ARTIFACT $TARGET_PATH --flat=true
           done
+      shell: bash
 
-          # promote on old repos
-          echo "[DEBUG] - Get yum.centreon.com path of $ARCH testing artifacts to promote to stable."
-          LEGACY_SRC_FILES=$(dir /srv/centreon-yum/yum.centreon.com/standard/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}/centreon-${{ inputs.module }}-${{ inputs.major_version }}.${{ inputs.minor_version }}-1/)
-          LEGACY_TARGET_PATH="/srv/centreon-yum/yum.centreon.com/standard/${{ inputs.major_version }}/${{ inputs.distrib }}/stable/$ARCH/RPMS/"
+    - name: Promote RPM packages to stable on yum.centreon.com
+      if: ${{ startsWith(inputs.distrib, 'el') }}
+      run: |
+        set -x
+        echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
+        echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
+        echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
+        echo "[DEBUG] - Repository name: ${{ inputs.repository_name }}"
 
-          ssh -o StrictHostKeyChecking=no mkdir -p $LEGACY_TARGET_PATH
-          ssh -o "StrictHostKeyChecking=no" cp $LEGACY_SRC_FILES $LEGACY_TARGET_PATH
+        PROJECT_PATH="standard"
+        INVALIDATION_PATHS=""
+        METADATAS=""
 
-          METADATAS="$METADATAS /srv/centreon-yum/yum.centreon.com/standard/${{ inputs.major_version }}/${{ inputs.distrib }}/stable/$ARCH"
-          INVALIDATION_PATHS="$INVALIDATION_PATHS /standard/${{ inputs.major_version }}/${{ inputs.distrib }}/stable/*"
+        # Handle repositories.
+        if [ "${{ inputs.repository_name }}" == "standard" ]; then
+          ROOT_REPO_PATH="standard"
+        else
+          echo "Invalid repository name: ${{ inputs.repository_name }}"
+          exit 1
+        fi
 
-          ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "sh /home/cesync/scripts/updaterepo.sh $METADATAS"
+        # Prepare ssh-key
+        eval `ssh-agent`
+        ssh-add - <<< "${{ inputs.yum_repo_key }}"
 
-          METADATAS=`echo "$METADATAS" | xargs -n1 | sort -u | xargs`
-          for METADATA in `echo $METADATAS`; do
-            ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" "sh "${{ inputs.update_repo_path }}" $METADATA" 2>&-
-          done
+        # Promote testing packages to stable.
+        for ARCH in "noarch" "x86_64"; do
+          echo "[DEBUG] - Get path of $ARCH testing artifacts to promote to stable."
 
-          ID="${{ inputs.cloudfront_id }}"
-          # Remove duplicated invalidation paths
-          INVALIDATION_PATHS=`echo "$INVALIDATION_PATHS" | xargs -n1 | sort -u | xargs`
-          ITERATIONS=1
+          # Check if there are testing packages to promote.
+          DIR_RETURN_CODE=$(ssh -q -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" dir /srv/centreon-yum/yum.centreon.com/$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}**/*${{ inputs.major_version }}.${{ inputs.minor_version }}-1/*.rpm &> /dev/null && echo "yes" || echo "no")
 
-          for INVALIDATION_PATH in `echo $INVALIDATION_PATHS`; do
-            until aws cloudfront create-invalidation --distribution-id "$ID" --paths "$INVALIDATION_PATH"; do
-              if [ ${ITERATIONS} -eq 10 ]; then
-                return 0
-              fi
-              echo "couldn't invalidate cache, AWS quota might have been reached, retrying in 30 seconds..."
-              sleep 30s
-              ITERATIONS=$((ITERATIONS+1))
+          if [[ $DIR_RETURN_CODE == "yes" ]]; then
+            SRC_PATHS=$(ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" dir "/srv/centreon-yum/yum.centreon.com/$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}**/*${{ inputs.major_version }}.${{ inputs.minor_version }}-1/*.rpm")
+            for SRC_PATH in ${SRC_PATHS[@]}; do
+              echo "[DEBUG] - Source path found: $SRC_PATH"
             done
+          else
+            echo "[DEBUG] - No source path found."
+            continue
+          fi
+
+          echo "[DEBUG] - Build target path."
+          TARGET_PATH="/srv/centreon-yum/yum.centreon.com/$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/RPMS"
+          #TARGET_PATH="/srv/centreon-yum/yum.centreon.com/$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/canary/$ARCH/RPMS"
+          echo "[DEBUG] - Target path: $TARGET_PATH"
+
+          echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
+          for ARTIFACT in ${SRC_PATHS[@]}; do
+            ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" mkdir -p "$TARGET_PATH"
+            #ssh -o StrictHostKeyChecking=no "${{ inputs.yum_repo_address }}" cp $ARTIFACT $TARGET_PATH/
+
+            METADATAS="METADATAS /srv/centreon-yum/yum.centreon.com/$ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH"
+            INVALIDATION_PATHS=$INVALIDATION_PATHS /ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/${{ inputs.stability }}/$ARCH/*"
           done
         done
+      shell: bash
+
+    - name: Promote DEB package to stable
+      if: ${{ startsWith(inputs.distrib, 'el') }}
+      run: |
+
+      shell: bash
+
+    - name: Promote DEB package to stable on Nexus
+      if: ${{ startsWith(inputs.distrib, 'el') }}
+      run: |
+
       shell: bash
