enh(promote): handle debian package promotion for multiple distributi… (#3921)
Co-authored-by: Kevin Duret <kduret@centreon.com>
Co-authored-by: May <110405507+paul-oureib@users.noreply.github.com>

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -116,9 +116,10 @@ runs:
       shell: bash
 
     - name: Promote DEB packages to stable
-      if: ${{ startsWith(inputs.distrib, 'bullseye') }}
+      if: ${{ contains(fromJSON('["bullseye", "bookworm"]') , inputs.distrib) }}
       run: |
-        set -x
+        set -eux
+
         echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
         echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
         echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
@@ -154,6 +155,11 @@ runs:
 
         for ARTIFACT_DL in $(dir|grep -E "*.deb"); do
           ARCH=$(echo $ARTIFACT_DL | cut -d '_' -f3 | cut -d '.' -f1)
+          DISTRIB=$(echo $ARTIFACT_DL | cut -d '_' -f2 | cut -d '-' -f2)
+          if [[ "${{ inputs.distrib }}" != "$DISTRIB" ]]; then
+            echo "::error::Distrib [$DISTRIB] from package does not match distrib [${{ inputs.distrib }}] from input, aborting promotion."
+            exit 1
+          fi
           echo "[DEBUG] - Promoting (upload) $ARTIFACT_DL to stable $TARGET_PATH."
           jf rt upload "$ARTIFACT_DL" "$TARGET_PATH" --deb "${{ inputs.distrib }}/main/$ARCH" --flat
         done
