update promote action

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -25,6 +25,9 @@ inputs:
   release_type:
     description: "Type of release (hotfix, release)"
     required: true
+  release_cloud:
+    description: "Release context (cloud or not cloud)"
+    required: true
 
 runs:
   using: "composite"
@@ -37,10 +40,14 @@ runs:
     - name: Promote RPM packages to stable
       if: ${{ startsWith(inputs.distrib, 'el') }}
       run: |
-        set -x
+        set -eux
+
+        # DEBUG
         echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
         echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
         echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
+        echo "[DEBUG] - release_cloud: ${{ inputs.release_cloud }}"
+        echo "[DEBUG] - release_type: ${{ inputs.release_type }}"
 
         # Cloud specific promote
         # delivery by default to onprem, override to internal if base branch is master
@@ -50,9 +57,21 @@ runs:
           ROOT_REPO_PATH="rpm-standard"
         fi
 
+        # Build upload taget path based on release_cloud and release_type values
+        # if cloud, deliver to testing/<release_type>
+        # if non-cloud, delivery to testing as usual
+        if [[ ${{ inputs.release_cloud }} -eq 1 && ${{ release_type }} == "hotfix" ]] || [[ ${{ inputs.release_cloud }} -eq 1 && ${{ release_type }} == "release" ]] ;then
+          SEARCH_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/testing-${{ inputs.release_type }}/$ARCH/${{ inputs.module_name }}/"
+        elif [[ ${{ inputs.release_cloud }} -eq 0 ]];then
+          SEARCH_REPO_PATH="${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module_name }}/"
+        else
+          echo "Invalid combination of release_type and release_cloud"
+        fi
+
+        # Search for testing packages candidate for promote
         for ARCH in "noarch" "x86_64"; do
           echo "[DEBUG] - Get path of $ARCH testing artifacts to promote to stable."
-          SRC_PATHS=$(jf rt s --include-dirs $ROOT_REPO_PATH/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}/${{ inputs.release_type }}/*.rpm | jq -r '.[].path')
+          SRC_PATHS=$(jf rt s --include-dirs $ROOT_REPO_PATH/$SEARCH_REPO_PATH/*.rpm | jq -r '.[].path')
 
           if [[ ${SRC_PATHS[@]} ]]; then
             for SRC_PATH in ${SRC_PATHS[@]}; do
