fix

diff --git a/.github/actions/promote-to-stable/action.yml b/.github/actions/promote-to-stable/action.yml
--- a/.github/actions/promote-to-stable/action.yml
+++ b/.github/actions/promote-to-stable/action.yml
@@ -70,17 +70,24 @@ runs:
         echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
         echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
 
+        PATHS_FOUND_IN_ARCH=0
+
         for ARCH in "noarch" "x86_64"; do
           echo "[DEBUG] - Get artifactory path of $ARCH testing artifacts to promote to stable."
-          SRC_PATHS=$(jf rt s --include-dirs rpm-standard/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}/*.rpm | jq -r '.[].path')
+          SRC_PATHS=$(jf rt search --include-dirs rpm-standard/${{ inputs.major_version }}/${{ inputs.distrib }}/testing/$ARCH/${{ inputs.module }}/*.rpm | jq -r '.[].path')
 
           if [[ ${SRC_PATHS[@]} ]]; then
             for SRC_PATH in ${SRC_PATHS[@]}; do
               echo "[DEBUG] - Source path found: $SRC_PATH"
             done
           else
-            echo "[DEBUG] - No source path found."
-            continue
+            echo "[DEBUG] - No source path found for $ARCH."
+            PATHS_FOUND_IN_ARCH+=1
+          fi
+
+          if [[ $PATHS_FOUND_IN_ARCH -eq 2 ]]; then
+            echo "[DEBUG] - No source path found in all architecture."
+            exit 1
           fi
 
           echo "[DEBUG] - Build $ARCH artifactory target path."
@@ -90,8 +97,47 @@ runs:
           echo "[DEBUG] - Promoting $ARCH testing artifacts to stable."
           for ARTIFACT in ${SRC_PATHS[@]}; do
             echo "[DEBUG] - Promoting $ARTIFACT to stable on artifactory."
-            jf rt cp $ARTIFACT $TARGET_PATH --flat=true
+            jf rt copy $ARTIFACT $TARGET_PATH --flat=true
           done
+        done
+      shell: bash
+
+    - name: Promote DEB package to stable
+      if: ${{ startsWith(inputs.distrib, 'bullseye') }}
+      run: |
+        set -x
+        echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
+        echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
+        echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
+        echo "[DEBUG] - Repository name: ${{ inputs.repository_name }}"
+
+        if [[ "${{ inputs.repository_name }}" == "standard" ]]; then
+          ROOT_REPO_PATH="apt-standard-${{ inputs.major_version }}"
+        else
+          echo "Invalid repository name: ${{ inputs.repository_name }}"
+          exit 1
+        fi
+
+        echo "[DEBUG] - Get path of testing DEB packages to promote to stable."
+        SRC_PATHS=$(jf rt search --include-dirs $ROOT_REPO_PATH-testing/pool/${{ inputs.module }}/*${{ inputs.major_version }}.${{ inputs.minor_version }}*.deb | jq -r '.[].path')
+
+        if [[ ${SRC_PATHS[@]} ]]; then
+          for SRC_PATH in ${SRC_PATHS[@]}; do
+            echo "[DEBUG] - Source path found: $SRC_PATH"
+          done
+        else
+          echo "[DEBUG] - No source path found."
+          continue
+        fi
+
+        echo "[DEBUG] - Build target path."
+        TARGET_PATH="$ROOT_REPO_PATH-${{ inputs.stability }}/pool/"
+        echo "[DEBUG] - Target path: $TARGET_PATH"
+
+        echo "[DEBUG] - Promoting DEB testing artifacts to stable."
+        for ARTIFACT in ${SRC_PATHS[@]}; do
+          echo "[DEBUG] - Promoting $ARTIFACT to stable."
+          jf rt cp $ARTIFACT $TARGET_PATH --flat=true
         done
       shell: bash
 
@@ -172,45 +218,6 @@ runs:
             sleep 30s
             ITERATIONS=$((ITERATIONS+1))
           done
-        done
-      shell: bash
-
-    - name: Promote DEB package to stable
-      if: ${{ startsWith(inputs.distrib, 'bullseye') }}
-      run: |
-        set -x
-        echo "[DEBUG] - Major version: ${{ inputs.major_version }}"
-        echo "[DEBUG] - Minor version: ${{ inputs.minor_version }}"
-        echo "[DEBUG] - Distrib: ${{ inputs.distrib }}"
-        echo "[DEBUG] - Repository name: ${{ inputs.repository_name }}"
-
-        if [[ "${{ inputs.repository_name }}" == "standard" ]]; then
-          ROOT_REPO_PATH="apt-standard-${{ inputs.major_version }}"
-        else
-          echo "Invalid repository name: ${{ inputs.repository_name }}"
-          exit 1
-        fi
-
-        echo "[DEBUG] - Get path of testing DEB packages to promote to stable."
-        SRC_PATHS=$(jf rt search --include-dirs $ROOT_REPO_PATH-testing/pool/${{ inputs.module }}/*${{ inputs.major_version }}.${{ inputs.minor_version }}*.deb | jq -r '.[].path')
-
-        if [[ ${SRC_PATHS[@]} ]]; then
-          for SRC_PATH in ${SRC_PATHS[@]}; do
-            echo "[DEBUG] - Source path found: $SRC_PATH"
-          done
-        else
-          echo "[DEBUG] - No source path found."
-          continue
-        fi
-
-        echo "[DEBUG] - Build target path."
-        TARGET_PATH="$ROOT_REPO_PATH-${{ inputs.stability }}/pool/"
-        echo "[DEBUG] - Target path: $TARGET_PATH"
-
-        echo "[DEBUG] - Promoting DEB testing artifacts to stable."
-        for ARTIFACT in ${SRC_PATHS[@]}; do
-          echo "[DEBUG] - Promoting $ARTIFACT to stable."
-          jf rt cp $ARTIFACT $TARGET_PATH --flat=true
         done
       shell: bash
 
