fix(ci): fix release workflow and action issues

diff --git a/.github/actions/release/action.yml b/.github/actions/release/action.yml
--- a/.github/actions/release/action.yml
+++ b/.github/actions/release/action.yml
@@ -16,6 +16,9 @@ inputs:
   jira_webhook_url:
     description: "Jira release webhook"
     required: true
+  jira_base_url:
+    description: "Jira base url"
+    required: true
 
 runs:
   using: "composite"
@@ -25,7 +28,7 @@ runs:
 
     - name: Get released versions for components
       run: |
-        set -eu
+        set -eux
 
         # Variables
         COMPONENTS_OSS=("centreon-awie" "centreon-dsm" "centreon-gorgone" "centreon-ha" "centreon-open-tickets" "centreon-web")
@@ -41,11 +44,6 @@ runs:
 
         # Get previous and new version tags for components
         for component in ${COMPONENTS_OSS[@]}; do
-          if [[ $component == "centreon-web" ]]; then
-            COMPONENT_DIR="centreon"
-          else
-            COMPONENT_DIR=$component
-          fi
           MAJOR_VERSION=$(grep -E "MAJOR" .version | cut -d '=' -f2)
           MINOR_VERSION=$(grep -E "MINOR" $COMPONENT_DIR/.version | cut -d '=' -f2)
           # Previous stable tags array
@@ -68,20 +66,18 @@ runs:
 
     - name: Add new release tags to stable branch
       run: |
+        set -eux
+
         # Add new stable tags to stable branch
         echo "Configuring git."
         git config --global user.email "release@centreon.com"
         git config --global user.name "Centreon"
 
-        # Rebuild NEW_STABLE_TAGS as an array
-        for i in ${NEW_RELEASE_TAGS[@]}; do
-          NEW_RELEASE_TAGS+=("$i")
-        done
-
         # Create release tags on git for each release components
+        # Abort if no tags or existing tag
         echo "Creating release tags."
-        for TAG in ${NEW_RELEASE_TAGS[@]}; do
-          if [ -z $(git tag --list "$TAG" | head -n 1) ]; then
+        for TAG in ${NEW_STABLE_TAGS[@]}; do
+          if [ -z $(git tag --list "$TAG" | head -n 1) ] && [ -n $TAG ]; then
             git tag -a "$TAG" -m "$TAG"
             git push --follow-tags
             echo "::notice::Tagging stable branch with $TAG."
@@ -94,6 +90,8 @@ runs:
 
     - name: Create GITHUB releases from new release tags
       run: |
+        set -eux
+
         # Install gh cli
         echo "Installing GH CLI."
         if ! command -v gh &> /dev/null; then
@@ -108,16 +106,16 @@ runs:
           echo "GH CLI is already installed."
         fi
 
-        # Rebuild NEW_STABLE_TAGS as an array
-        for i in ${NEW_STABLE_TAGS[@]}; do
-          NEW_RELEASE_TAGS+=("$i")
-        done
-
         # Create GITHUB release for each release components
+        # Abort if no tags
         echo "Creating GITHUB releases."
-        for TAG in ${NEW_RELEASE_TAGS[@]}; do
-          echo "Creating GITHUB release with title $TAG for tag $TAG."
-          gh release create $TAG --target "${{ inputs.github_ref_name }}" --title "$TAG" --verify-tag
+        for TAG in ${NEW_STABLE_TAGS[@]}; do
+          if [ -n $TAG ]; then
+            echo "Creating GITHUB release with title $TAG for tag $TAG."
+            gh release create $TAG --target "${{ inputs.github_ref_name }}" --title "$TAG" --verify-tag
+          else
+            echo "::error::Release tag $TAG was empty, exiting."
+            exit 1
         done
       shell: bash
       env:
@@ -125,7 +123,7 @@ runs:
 
     - name: Create stable JIRA versions from new release tags
       run: |
-        set -eu
+        set -eux
 
         # Call JIRA to provide new jira versions to create
         # Webhook url
@@ -147,41 +145,53 @@ runs:
         JIRA_RELEASE_NAME=""
         JIRA_PROJECT_ID="${{ inputs.jira_project_id }}"
         JIRA_RELEASE_RELEASED="false"
+
         # Create JIRA version for each released component
         echo "Creating JIRA releases."
         for TAG in ${NEW_RELEASE_TAGS[@]}; do
-          echo "::notice::Creating JIRA release $TAG based on git release tag $TAG."
-          # Build JSON with release information for JIRA API
-          JIRA_RELEASE_DATA=$(jq -nc \
-            --arg archived "$JIRA_RELEASE_ARCHIVED" \
-            --arg description "$TAG" \
-            --arg releaseDate "$JIRA_RELEASE_DATE" \
-            --arg name "$TAG" \
-            --arg projectId "$JIRA_PROJECT_ID" \
-            --arg released "$JIRA_RELEASE_RELEASED" \
-            '$ARGS.named' )
-          # Send to JIRA API release
-          echo "Sending to JIRA API release: $JIRA_RELEASE_DATA"
-          curl --fail --request POST \
-            --url 'https://centreon.atlassian.net/rest/api/3/version' \
-            --user '${{ inputs.jira_user_email }}:${{ inputs.jira_api_token }}' \
-            --header 'Accept: application/json' \
-            --header 'Content-Type: application/json' \
-            --data "$JIRA_RELEASE_DATA"
+          if [ -n $TAG ]; then
+            echo "::notice::Creating JIRA release $TAG based on git release tag $TAG."
+            # Build JSON with release information for JIRA API
+            JIRA_RELEASE_DATA=$(jq -nc \
+              --arg archived "$JIRA_RELEASE_ARCHIVED" \
+              --arg description "$TAG" \
+              --arg releaseDate "$JIRA_RELEASE_DATE" \
+              --arg name "$TAG" \
+              --arg projectId "$JIRA_PROJECT_ID" \
+              --arg released "$JIRA_RELEASE_RELEASED" \
+              '$ARGS.named' )
+            # Send to JIRA API release
+            echo "Sending to JIRA API release: $JIRA_RELEASE_DATA"
+            curl --fail --request POST \
+              --url 'https://${{ inputs.jira_base_url }}/rest/api/3/version' \
+              --user '${{ inputs.jira_user_email }}:${{ inputs.jira_api_token }}' \
+              --header 'Accept: application/json' \
+              --header 'Content-Type: application/json' \
+              --data "$JIRA_RELEASE_DATA"
+          else
+            echo "::error::Release tag $TAG was empty, exiting."
+            exit 1
+          fi
         done
       shell: bash
 
     - name: Trigger release communication for new releases
       run: |
-        set -eu
+        set -eux
+
         MAJOR_VERSION=$CURRENT_STABLE_BRANCH_MAJOR_VERSION
 
         # Webhook url
         JIRA_INCOMING_WEBHOOK="${{ inputs.jira_webhook_url }}"
 
-        # Rebuild NEW_STABLE_TAGS as an array
+        # Rebuild NEW_STABLE_TAGS as an array (required to build a proper json)
         for i in ${NEW_STABLE_TAGS[@]}; do
-          NEW_RELEASE_TAGS+=("$i")
+          if [ -n "$i" ]; then
+            NEW_RELEASE_TAGS+=("$i")
+          else
+            echo "::error::Release tag $i was empty, exiting."
+            exit 1
+          fi
         done
 
         # Build JSON structure with released versions
