add release tag step and jira automation webhook trigger step

diff --git a/.github/actions/release/action.yml b/.github/actions/release/action.yml
--- a/.github/actions/release/action.yml
+++ b/.github/actions/release/action.yml
@@ -14,6 +14,9 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Checkout sources
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+
     - name: Get released versions
       run: |
         set -eux
@@ -59,7 +62,7 @@ runs:
           echo "Tagging branch with $tag."
         done
 
-        # Create new JIRA versions
+        # Create new JIRA versions (old way of doing it)
         # TODO: add a future capacity to determine wether the release is hotfix or standard (using TYPE)
 
         JIRA_VERSION_DATA="{\"archived\":false,\"releaseDate\":\"$(date +%Y-%m-%d)\",\"name\":\"centreon-${{ inputs.module_name }}-$NEW_VERSION\",\"description\":\"$TYPE:$RELEASE_ID\",\"projectId\":${{ inputs.jira_project_id }},\"released\":false}"
@@ -70,52 +73,21 @@ runs:
           --header 'Content-Type: application/json' \
           --data ''$VERSION_DATA''
 
-        ######################
-        NEW_VERSION=""
-        MAJOR_VERSION=$(echo $GITHUB_REF_NAME | grep -oP '([0-9]{2}\.[0-9]{2})')
-        echo "Major version: $MAJOR_VERSION"
-        HOTFIX=$(echo $GITHUB_REF_NAME | grep -oP '(hotfix|)')
-        echo "Hotfix: $HOTFIX"
-        RELEASE_ID=$(git log -1 --pretty=%B | grep -oP '(#[0-9]{4,}#)' | grep -oP '([0-9]+)')
-        echo "Release Id: $RELEASE_ID"
-
-        OLDV=$(git tag --sort=-v:refname --list "centreon-${{ inputs.module_name }}-$MAJOR_VERSION.*" | head -n 1)
-        echo "Old version: $OLDV"
-
-        git config --global user.email "release@centreon.com"
-        git config --global user.name "Centreon"
-
-        if [ -z "$OLDV" ]; then
-          echo "No existing version, starting at $MAJOR_VERSION.0"
-          NEW_VERSION="$MAJOR_VERSION.0"
-          git tag -a "centreon-${{ inputs.module_name }}-$NEW_VERSION" -m "version $NEW_VERSION"
-          git push --follow-tags
-        else
-          OLD_MINOR_VERSION=$(echo $OLDV | grep -oP '([0-9]+$)')
-          NEW_MINOR_VERSION=$(echo $((OLD_MINOR_VERSION + 1)))
-          NEW_VERSION=$MAJOR_VERSION.$NEW_MINOR_VERSION
-          git tag -a "centreon-${{ inputs.module_name }}-$NEW_VERSION" -m "version $NEW_VERSION"
-          git push --follow-tags
-        fi
-
-        if [ "$HOTFIX" == "hotfix" ]; then
-          TYPE=Hotfix
-        else
-          TYPE=Release
-        fi
-
-        VERSION_DATA="{\"archived\":false,\"releaseDate\":\"$(date +%Y-%m-%d)\",\"name\":\"centreon-${{ inputs.module_name }}-$NEW_VERSION\",\"description\":\"$TYPE:$RELEASE_ID\",\"projectId\":${{ inputs.jira_project_id }},\"released\":false}"
-
-        curl --fail --request POST \
-          --url 'https://centreon.atlassian.net/rest/api/3/version' \
-          --header 'Authorization: Basic ${{ inputs.jira_token }}' \
-          --header 'Accept: application/json' \
-          --header 'Content-Type: application/json' \
-          --data ''$VERSION_DATA''
-
       shell: bash
 
     - name: Add new release tags to stable branch
+      run: |
+        # Create release tags on git for each release components
+        for TAG in ${NEW_STABLE_TAGS[@]}; do
+          if [ -z $(git tag --list "$TAG" | head -n 1) ]; then
+            git tag -a "$TAG" -m "$TAG"
+            git push --follow-tags
+          else
+            echo "::error::Release tag $TAG already exists, exiting."
+            exit 1
+          fi
+        done
+      shell: bash
 
     - name: Create GITHUB releases from new release tags
 
@@ -125,6 +97,23 @@ runs:
         # Fetch ID of release JIRA issue
 
         # Call JIRA to provide new jira versions to create
+        # Webhook url
+        JIRA_INCOMING_WEBHOOK="${{ inputs.jira_webhook_url }}"
+
+        # Build JSON structure with released versions
+        RELEASE_JSON=$(jq -nc '{componentList: $ARGS.positional}' --args "${NEW_STABLE_TAGS[@]}")
+
+        # Call jira webhook to trigger the communication workflow
+        # and provide versions data for communication
+        curl \
+          $JIRA_INCOMING_WEBHOOK \
+          -X POST \
+          -H 'Content-type: application/json' \
+          --data $RELEASE_JSON
       shell: bash
 
     - name: Trigger release communication for new releases
+      run: |
+
+
+      shell: bash
