sync with centreon

diff --git a/.github/actions/create-jira-ticket/action.yml b/.github/actions/create-jira-ticket/action.yml
--- a/.github/actions/create-jira-ticket/action.yml
+++ b/.github/actions/create-jira-ticket/action.yml
@@ -103,40 +103,40 @@ runs:
         fi
       shell: bash
 
-    - name: Create Jira Issue
-      if: ${{ env.abort_ticket_creation != 'true' }}
-      run: |
-        # Creating a new incident ticket on Jira
-        DATA=$( cat <<-EOF
-        {
-          "fields": {
-            "summary": "${{ steps.get_context.outputs.ticket_summary }}",
-            "project": {"key": "MON"},
-            "issuetype": {"id": "10209"},
-            "parent": {"id": "${{ steps.get_context.outputs.parent_epic_id }}", "key": "${{ steps.get_context.outputs.parent_epic_key }}"},
-            "labels": ${{ inputs.ticket_labels }},
-            "components":[{"name": "${{ inputs.module_name }}"}],
-            "customfield_10902": {"id": "10524", "value": "DevSecOps"},
-            "customfield_10005": 1.0,
-            "description": $(cat ${{ steps.get_context.outputs.json_template_file }})
-          }
-        }
-        EOF
-        )
+    # - name: Create Jira Issue
+    #   if: ${{ env.abort_ticket_creation != 'true' }}
+    #   run: |
+    #     # Creating a new incident ticket on Jira
+    #     DATA=$( cat <<-EOF
+    #     {
+    #       "fields": {
+    #         "summary": "${{ steps.get_context.outputs.ticket_summary }}",
+    #         "project": {"key": "MON"},
+    #         "issuetype": {"id": "10209"},
+    #         "parent": {"id": "${{ steps.get_context.outputs.parent_epic_id }}", "key": "${{ steps.get_context.outputs.parent_epic_key }}"},
+    #         "labels": ${{ inputs.ticket_labels }},
+    #         "components":[{"name": "${{ inputs.module_name }}"}],
+    #         "customfield_10902": {"id": "10524", "value": "DevSecOps"},
+    #         "customfield_10005": 1.0,
+    #         "description": $(cat ${{ steps.get_context.outputs.json_template_file }})
+    #       }
+    #     }
+    #     EOF
+    #     )
 
-        response=$(curl \
-          --request POST \
-          --url "${{ inputs.jira_base_url }}/rest/api/3/issue" \
-          --user "${{ inputs.jira_user_email }}:${{ inputs.jira_api_token }}" \
-          --header 'Accept: application/json' \
-          --header 'Content-Type: application/json' \
-          --data "$DATA")
-        echo $response
-        if [ $? -ne 0 ]; then
-          echo "::error::Failed to create ticket: $response"
-          exit 1
-        fi
+    #     response=$(curl \
+    #       --request POST \
+    #       --url "${{ inputs.jira_base_url }}/rest/api/3/issue" \
+    #       --user "${{ inputs.jira_user_email }}:${{ inputs.jira_api_token }}" \
+    #       --header 'Accept: application/json' \
+    #       --header 'Content-Type: application/json' \
+    #       --data "$DATA")
+    #     echo $response
+    #     if [ $? -ne 0 ]; then
+    #       echo "::error::Failed to create ticket: $response"
+    #       exit 1
+    #     fi
 
-        ticket_key=$(echo "$response" | jq -r .key)
-        echo "::notice::Created ticket: $ticket_key"
-      shell: bash
+    #     ticket_key=$(echo "$response" | jq -r .key)
+    #     echo "::notice::Created ticket: $ticket_key"
+    #   shell: bash
