experiment with templating + apply feedback

diff --git a/.github/actions/create-jira-ticket/action.yml b/.github/actions/create-jira-ticket/action.yml
--- a/.github/actions/create-jira-ticket/action.yml
+++ b/.github/actions/create-jira-ticket/action.yml
@@ -21,22 +21,29 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
+
     - name: Get ticket elements from context
       id: get_context
       run: |
         # Change context elements (summary, parent epic, etc.) that is checked depending on the reason the ticket is created
         if [[ "${{ inputs.reason_for_ticket_creation }}" == "veracode" ]]; then
-            parent_epic_id=83818
-            parent_epic_key="AT-268"
-            ticket_summary="PR-${{ github.event.pull_request.number }} incident on ${{ inputs.module_name }}"
-            ticket_labels="[\"Veracode\", \"Pipeline\"]"
-            run_url="N/A"
+          parent_epic_id=83818
+          parent_epic_key="AT-268"
+          ticket_summary="PR-${{ github.event.pull_request.number }} incident on ${{ inputs.module_name }}"
+          ticket_labels="[\"Veracode\", \"Pipeline\"]"
+          run_url="N/A"
         elif [[ "${{ inputs.reason_for_ticket_creation }}" == "nightly" ]]; then
-            parent_epic_id=206242
-            parent_epic_key="MON-151547"
-            ticket_summary="$(date '+%Y-%m-%d') ${{ inputs.module_name }}-${{ github.ref_name }} nightly build failure"
-            ticket_labels="[\"Nightly\", \"Pipeline\"]"
-            run_url=$(gh run ls --json name,url --workflow web.yml --branch ${{ github.ref_name }} --limit 20 | jq --arg branch "${{ github.ref_name }}" '. | map(select(.name == "web nightly $branch")) | .[0].url')
+          parent_epic_id=206242
+          parent_epic_key="MON-151547"
+          ticket_summary="$(date '+%Y-%m-%d') ${{ inputs.module_name }}-${{ github.ref_name }} nightly build failure"
+          ticket_labels="[\"Nightly\", \"Pipeline\"]"
+          run_url=$(gh run ls --json name,url --workflow web.yml --branch ${{ github.ref_name }} --limit 20 | \
+            jq --arg module_name "${{ inputs.module_name }}" --arg branch "${{ github.ref_name }}" '. | map(select(.name == "$module_name nightly $branch")) | .[0].url')
+          if [ $? -ne 0 ] || [ "$run_url" == "null" ]; then
+            echo "::error::Failed to get nightly run URL"
+            exit 1
+          fi
         fi
 
         echo "parent_epic_id=$parent_epic_id" >> $GITHUB_OUTPUT
@@ -48,7 +55,7 @@ runs:
       env:
         GH_TOKEN: ${{ github.token }}
 
-    - name: Check if ticket exists already
+    - name: Check if the ticket already exists
       id: check_ticket
       run: |
         # Checking if an incident ticket already exists
@@ -79,52 +86,7 @@ runs:
     - name: Create Jira Issue
       if: ${{ env.abort_ticket_creation != 'true' }}
       run: |
-        if [[ "${{ inputs.reason_for_ticket_creation }}" == "veracode" ]]; then
-          ticket_description=$(cat <<-EOD
-          {"version": 1, "type": "doc", "content": [
-            {"type": "paragraph", "content": [
-              {"type": "text", "text": "This incident ticket relates to:"}
-            ]},
-            {"type": "bulletList", "content": [
-                {"type": "listItem", "content": [
-                  {"type": "paragraph", "content": [
-                    {"type": "text", "text": "Ref: "},
-                    {"type": "text", "text": "PR-${{ github.event.pull_request.number }}", "marks": [{"type": "link", "attrs": {"href": "${{ github.event.pull_request.html_url }}"}}]}
-                  ]
-                }]
-              }]
-            },
-            {"type": "paragraph", "content": []},
-              {"type": "bulletList", "content": [
-                {"type": "listItem", "content": [
-                  {"type": "paragraph", "content": [
-                    {"type": "text", "text": "Target: "},
-                    {"type": "text", "text": "${{ github.base_ref || github.ref_name }}", "marks": [{"type": "strong"}]}
-                  ]}
-                ]},
-                {"type": "listItem", "content": [
-                  {"type": "paragraph", "content": [
-                    {"type": "text", "text": "Link to the job", "marks": [{"type": "link", "attrs": {"href": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}"}}]}
-                  ]}
-                ]}
-              ]},
-            ]}
-        EOD
-          )
-        elif [[ "${{ inputs.reason_for_ticket_creation }}" == "nightly" ]]; then
-          ticket_description=$(cat <<-EOD
-          {"version": 1, "type": "doc", "content": [
-            {"type": "paragraph", "content": [
-              {"type": "text", "text": "This incident ticket relates to the ${{ inputs.module_name }} nightly on ${{ github.ref_name }} which failed on $(date '+%Y-%m-%d')."}
-            ]},
-            {"type": "paragraph","content": [
-              {"type": "text", "text": "Link to the failed nightly", "marks": [{"type": "link", "attrs": {"href": ${{ steps.get_context.outputs.run_url }} }}]}
-            ]}
-          ]}
-        EOD
-          )
-        fi
-
+        echo "Current path: $(ls -lah)"
         # Creating a new incident ticket on Jira
         DATA=$( cat <<-EOF
         {
@@ -137,7 +99,7 @@ runs:
             "components":[{"name": "${{ inputs.module_name }}"}],
             "customfield_10902": {"id": "10524", "value": "DevSecOps"},
             "customfield_10005": 1.0,
-            "description": $ticket_description
+            "description": $(cat ./centreon/.github/actions/create-jira-ticket/${{ inputs.reason_for_ticket_creation }}-ticket-template.json)
           }
         }
         EOF
