force 24.04 build

diff --git a/.github/actions/build-openapi-documentation/action.yml b/.github/actions/build-openapi-documentation/action.yml
--- a/.github/actions/build-openapi-documentation/action.yml
+++ b/.github/actions/build-openapi-documentation/action.yml
@@ -64,18 +64,14 @@ runs:
 
         cd ./$OPENAPI_FILE_PATH
 
-        if ! [[ $major_version =~ ^2[0-9]\.10$ ]] && [[ -f "$MODULE_PATH-cloud-api.yaml" ]]; then
-          doc_version="cloud"
-          export OPENAPI_FILE="$MODULE_PATH-cloud-api.yaml"
-          sed -i "s#version: 'latest'#version: 'Cloud'#" $OPENAPI_FILE
-        elif [[ $major_version =~ ^2[0-9]\.04$ ]] && [[ -f "$MODULE_PATH-api-v24.04.yaml" ]]; then
+        #if [[ $major_version =~ ^2[0-9]\.04$ ]] && [[ -f "$MODULE_PATH-api-v24.04.yaml" ]]; then
           doc_version=$major_version
           export OPENAPI_FILE="centreon-api-v24.04.yaml"
           sed -i "s#version: 'latest'#version: '$doc_version'#" $OPENAPI_FILE
-        else
-          echo "::error::OpenAPI file not found"
-          exit 1
-        fi
+        #else
+        #  echo "::error::OpenAPI file not found"
+        #  exit 1
+        #fi
         echo "doc_version=$doc_version" >> $GITHUB_OUTPUT
 
         echo "Building API doc from $OPENAPI_FILE"
