refactoception

diff --git a/.github/actions/build-openapi-documentation/action.yml b/.github/actions/build-openapi-documentation/action.yml
--- a/.github/actions/build-openapi-documentation/action.yml
+++ b/.github/actions/build-openapi-documentation/action.yml
@@ -8,9 +8,6 @@ inputs:
   openapi_file_reference:
     description: "Reference (tag or branch) on which the files are fetched"
     required: false
-  is_cloud:
-    description: "Release context (cloud or not cloud)"
-    required: true
 outputs:
   doc_version:
     description: Version of the documentation
@@ -46,31 +43,26 @@ runs:
     - name: Build OpenAPI documentation
       id: build_documentation
       run: |
-        if [[ "${{ inputs.is_cloud }}" == "true" && -f "centreon-cloud-api.yaml" ]]; then
+        source ../../../.version
+        major_version=${MAJOR}
+
+        if ! [[ $major_version =~ ^2[0-9]\.10$ ]] && [[ -f "centreon-cloud-api.yaml" ]]; then
+          doc_version=$major_version
           OPENAPI_FILE="centreon-cloud-api.yaml"
-        elif [[ -f "centreon-api.yaml" ]]; then
-          OPENAPI_FILE="centreon-api.yaml"
+          sed -i "s#version: 'latest'#version: '$doc_version'#" $OPENAPI_FILE
+        elif [[ -f "${{ inputs.module_name == 'centreon-web' && 'centreon' || inputs.module_name }}-api.yaml" ]]; then
+          doc_version="cloud"
+          OPENAPI_FILE="${{ inputs.module_name == 'centreon-web' && 'centreon' || inputs.module_name }}-api.yaml"
+          sed -i "s#version: 'latest'#version: 'Cloud'#" $OPENAPI_FILE
         else
-          echo "::error::openapi file not found"
+          echo "::error::OpenAPI file not found"
           exit 1
         fi
 
         echo "Building API doc from $OPENAPI_FILE"
         pnpm run build $OPENAPI_FILE
-
-        source ../../../.version
-        major_version=${MAJOR}
-        if [[ $major_version =~ ^2[0-9]\.(04|10)$ ]]; then
-          doc_version=$major_version
-          sed -i "s#version: 'latest'#version: '$doc_version'#" $OPENAPI_FILE
-        else
-          doc_version="cloud"
-          sed -i "s#version: 'latest'#version: 'Cloud'#" $OPENAPI_FILE
-        fi
         echo "doc_version=$doc_version" >> $GITHUB_OUTPUT
 
-        echo "Building API doc from $OPENAPI_FILE"
-        pnpm run redoc-latest
       shell: bash
       working-directory: ${{ inputs.openapi_file_reference || github.ref_name }}/${{ inputs.module_name == 'centreon-web' && 'centreon' || inputs.module_name }}/doc/API
 
