Fix versions comparison

diff --git a/.github/actions/check-package-version/action.yml b/.github/actions/check-package-version/action.yml
--- a/.github/actions/check-package-version/action.yml
+++ b/.github/actions/check-package-version/action.yml
@@ -42,5 +42,5 @@ runs:
           compare-to: ${{ env.NEW_VERSION }}
 
       - name: Result comparison
-        run: '[[ "<" == "${{ steps.check-versions.outputs.comparison-result }}" ]] && echo "The version is valid" || (echo "The version is invalid. Please upgrade your package.json to ${{ env.BASE_VERSION }}" && exit 1)'
+        run: '[[ "<" == "${{ steps.check-versions.outputs.comparison-result }}" || "=" == "${{ steps.check-versions.outputs.comparison-result }}" ]] && echo "The version is valid" || (echo "The version is invalid. Please upgrade your package.json to ${{ env.BASE_VERSION }}" && exit 1)'
         shell: bash
