enh(CI): Add action to publish beta packages (#224)
Co-authored-by: Thebarda <Thebarda@users.noreply.github.com>
Co-authored-by: technique-ci <technique-ci@centreon.com>

diff --git a/.github/actions/check-package-version/action.yml b/.github/actions/check-package-version/action.yml
--- a/.github/actions/check-package-version/action.yml
+++ b/.github/actions/check-package-version/action.yml
@@ -41,6 +41,6 @@ runs:
           version: ${{ env.BASE_VERSION }}
           compare-to: ${{ env.NEW_VERSION }}
 
-      - name: Result
-        run: '[[ "<" == "${{ steps.check-versions.outputs.comparison-result }}" ]]'
+      - name: Result comparison
+        run: '[[ "<" == "${{ steps.check-versions.outputs.comparison-result }}" || "=" == "${{ steps.check-versions.outputs.comparison-result }}" ]] && echo "The version is valid" || (echo "The version is invalid. Please upgrade your package.json to ${{ env.BASE_VERSION }}" && exit 1)'
         shell: bash
