add conditionsin action

diff --git a/.github/actions/check-version/action.yml b/.github/actions/check-version/action.yml
--- a/.github/actions/check-version/action.yml
+++ b/.github/actions/check-version/action.yml
@@ -24,21 +24,31 @@ runs:
       # Make sure version is NOT the same as the current stable.
       # If it is, abort any job beyond this point
 
-      CURRENT_STABLE_TAG=$(git tag -l 'centreon-${{ inputs.module_name }}-${{ inputs.major_version }}-${{ inputs.minor_version }}')
       CURRENT_STABLE_VERSION=$(git tag -l 'centreon-${{ inputs.module_name }}-${{ inputs.major_version }}-${{ inputs.minor_version }}' | awk -F '-' '{print $3}' )
-      REF_VERSION="${{ inputs.major_version }}.${{ inputs.minor_version }}"
+      CURRENT_STABLE_MAJOR_VERSION=$(awk -F '.' '{printf "%s.%s",$1,$2}' <<< $CURRENT_STABLE_VERSION)
+      CURRENT_STABLE_MINOR_VERSION=$(awk -F '.' '{print $3}' <<< "$CURRENT_STABLE_VERSION")
+      BRANCH_VERSION="${{ inputs.major_version }}.${{ inputs.minor_version }}"
+      BRANCH_MAJOR_VERSION="${{ inputs.major_version }}"
+      BRANCH_MINOR_VERSION="${{ inputs.minor_version }}"
+
       echo "Current stable tag is: $CURRENT_STABLE_TAG"
       echo "Current stable version is: $CURRENT_STABLE_VERSION"
+      echo "Branch version is: "$BRANCH_VERSION"
 
       # Compare current stable version with ref version
+      # CURRENT_STABLE_VERSION = REF_VERSION => FAILURE
+      # CURRENT_STABLE_VERSION >= REF_VERSION+2 => FAILURE
 
-      if [[ "$CURRENT_STABLE_VERSION" == "$REF_VERSION" ]];then
-        echo "Current stable version is the same as version of this branch, action required, aborting."
+      if [[ "$CURRENT_STABLE_VERSION" == "$BRANCH_VERSION" ]];then
+        echo "Current stable version $CURRENT_STABLE_VERSION is the same as version of release branch $BRANCH_VERSION, action required, aborting."
         exit 1
-      elif [[ "$CURRENT_STABLE_VERSION" -lt "$REF_VERSION" ]]
-        echo "Current stable version is lesser than branch version."
+      elif [[ "$BRANCH_MINOR_VERSION" -lt "$CURRENT_STABLE_MINOR_VERSION" ]];then
+        echo "Current branch minor version $BRANCH_MINOR_VERSION is smaller than stable version $CURRENT_STABLE_MINOR_VERSION, action required, aborting."
+        exit 1
+      elif [[ "$BRANCH_MINOR_VERSION" -gt $(($CURRENT_STABLE_MINOR_VERSION+1)) ]];then
+        echo "Release branch version $BRANCH_MINOR_VERSION is larger than stable version + 1 ($(($CURRENT_STABLE_MINOR_VERSION+1))), action required, aborting."
       else
-        echo "Invalid version."
+        echo "Release branch version is ok."
       fi
 
     shell: bash
