some fix

diff --git a/.github/actions/cypress-e2e-testing/action.yml b/.github/actions/cypress-e2e-testing/action.yml
--- a/.github/actions/cypress-e2e-testing/action.yml
+++ b/.github/actions/cypress-e2e-testing/action.yml
@@ -83,40 +83,24 @@ runs:
       run: mkdir -p ${{ inputs.module }}/tests/e2e/results/cucumber-logs/
       shell: bash
 
-    # - name: Rename JSON report
-    #   if: ${{ always() }}
-    #   run: |
-    #     feature_name=$(basename "${{ inputs.feature_file_path }}")
-    #     report_path="${{ inputs.module }}/tests/e2e/results/cucumber-logs/report.json"
-    #     report_path_updated="${{ inputs.module }}/tests/e2e/results/cucumber-logs/${feature_name}-report.json"
-
-    #     if [ -f "$report_path" ]; then
-    #       jq 'if length > 0 then .[0] |= (.tags |= map(if .name | startswith("@REQ_MON-") then .name |= "@${{ inputs.test_execution_key }}" else . end)) | (.[] |= (if has("elements") then .elements[].tags |= map(if .name | startswith("@REQ_MON-") then .name |= "@${{ inputs.test_execution_key }}" else . end) else . end)) else . end' "$report_path" > "$report_path_updated"
-    #       rm "$report_path"
-
-    #       # Show the content of the modified file
-    #       echo "::group::${feature_name}-report.json"
-    #       cat "$report_path_updated"
-    #       echo "::endgroup::"
-
-    #     else
-    #       echo "Report file not found: $report_path"
-    #       exit 1
-    #     fi
-    #   shell: bash
-
-    - name: Check for test retries
-      id: check_retries
+    - name: Rename JSON report
+      if: ${{ always() }}
       run: |
-        if [ -f "e2e/results/hasRetries.json" ]; then
-          retries=$(jq '.' e2e/results/hasRetries.json)
-          echo "Test retries: $retries"
-          echo "$retries" > hasRetries.json
-          mkdir -p ${{ github.workspace }}/artifacts
-          mv hasRetries.json ${{ github.workspace }}/artifacts/hasRetries.json
-          echo "retries_artifact=${{ github.workspace }}/artifacts/hasRetries.json" >> $GITHUB_ENV
+        feature_name=$(basename "${{ inputs.feature_file_path }}")
+        report_path="${{ inputs.module }}/tests/e2e/results/cucumber-logs/report.json"
+        report_path_updated="${{ inputs.module }}/tests/e2e/results/cucumber-logs/${feature_name}-report.json"
+
+        if [ -f "$report_path" ]; then
+          jq 'if length > 0 then .[0] |= (.tags |= map(if .name | startswith("@REQ_MON-") then .name |= "@${{ inputs.test_execution_key }}" else . end)) | (.[] |= (if has("elements") then .elements[].tags |= map(if .name | startswith("@REQ_MON-") then .name |= "@${{ inputs.test_execution_key }}" else . end) else . end)) else . end' "$report_path" > "$report_path_updated"
+          rm "$report_path"
+
+          # Show the content of the modified file
+          echo "::group::${feature_name}-report.json"
+          cat "$report_path_updated"
+          echo "::endgroup::"
+
         else
-          echo "hasRetries.json not found!"
-          echo "retries_artifact=${{ github.workspace }}/artifacts/hasRetries.json" >> $GITHUB_ENV
+          echo "Report file not found: $report_path"
+          exit 1
         fi
       shell: bash
