feat(ci): allow parallel delivery of release and hotfix

diff --git a/.github/workflows/awie.yml b/.github/workflows/awie.yml
--- a/.github/workflows/awie.yml
+++ b/.github/workflows/awie.yml
@@ -7,12 +7,12 @@ concurrency:
 on:
   workflow_dispatch:
   pull_request:
-    # paths:
-    #   - ".version"
-    #   - ".version.centreon-awie"
-    #   - "centreon-awie/**"
-    #   - "!centreon-awie/features/**"
-    #   - "!centreon-awie/behat.yml"
+    paths:
+      - ".version"
+      - ".version.centreon-awie"
+      - "centreon-awie/**"
+      - "!centreon-awie/features/**"
+      - "!centreon-awie/behat.yml"
   push:
     branches:
       - develop
@@ -104,139 +104,138 @@ jobs:
           has_backend_changes: ${{ steps.filter.outputs.has_backend_changes || true }}
           has_test_changes: ${{ steps.filter.outputs.has_test_changes || true }}
 
-  # backend-lint:
-  #   runs-on: ubuntu-24.04
-  #   needs: [changes, get-environment]
-  #   if: |
-  #     needs.get-environment.outputs.skip_workflow == 'false' &&
-  #     needs.changes.outputs.has_backend_changes == 'true' &&
-  #     needs.get-environment.outputs.stability != 'stable'
-  #   steps:
-  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  backend-lint:
+    runs-on: ubuntu-24.04
+    needs: [changes, get-environment]
+    if: |
+      needs.get-environment.outputs.skip_workflow == 'false' &&
+      needs.changes.outputs.has_backend_changes == 'true' &&
+      needs.get-environment.outputs.stability != 'stable'
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-  #     - name: Setup PHP
-  #       uses: shivammathur/setup-php@ccf2c627fe61b1b4d924adfcbd19d661a18133a0 # v2.35.2
-  #       with:
-  #         php-version: 8.2
-  #         coverage: none
-  #       env:
-  #         runner: ubuntu-24.04
+      - name: Setup PHP
+        uses: shivammathur/setup-php@ccf2c627fe61b1b4d924adfcbd19d661a18133a0 # v2.35.2
+        with:
+          php-version: 8.2
+          coverage: none
+        env:
+          runner: ubuntu-24.04
 
-      # - name: Install dependencies for PHP quality tools
-      #   run: composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --quiet --no-scripts
-      #   working-directory: php-tools
-      #   shell: bash
+      - name: Install dependencies for PHP quality tools
+        run: composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --quiet --no-scripts
+        working-directory: php-tools
+        shell: bash
 
-      # - name: Install dependencies for centreon-awie
-      #   run: composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --quiet --no-scripts
-      #   working-directory: centreon-awie
-      #   shell: bash
+      - name: Install dependencies for centreon-awie
+        run: composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --quiet --no-scripts
+        working-directory: centreon-awie
+        shell: bash
 
-  #     - name: 🛠️ Rector checks
-  #       working-directory: centreon-awie
-  #       run: |
-  #         echo "Run of these Rector tests: rector:legacy" && set -e
+      - name: 🛠️ Rector checks
+        working-directory: centreon-awie
+        run: |
+          echo "Run of these Rector tests: rector:legacy" && set -e
 
-  #         pids=()
-  #         statuses=()
+          pids=()
+          statuses=()
 
-  #         run_task() {
-  #           name=$1
-  #           shift
-  #           "$@" -- --no-progress-bar
-  #           result=$?
-  #           if [ $result -eq 0 ]; then
-  #             echo "✅ Rector $name: Success"
-  #           else
-  #             echo "❌ Rector $name: Failed"
-  #           fi
-  #           return $result
-  #         }
+          run_task() {
+            name=$1
+            shift
+            "$@" -- --no-progress-bar
+            result=$?
+            if [ $result -eq 0 ]; then
+              echo "✅ Rector $name: Success"
+            else
+              echo "❌ Rector $name: Failed"
+            fi
+            return $result
+          }
 
-  #         # Start tasks in background
-  #         run_task legacy composer rector:legacy & pids+=($!)
+          # Start tasks in background
+          run_task legacy composer rector:legacy & pids+=($!)
 
-  #         # Wait for all, and record if any failed
-  #         exit_code=0
-  #         for pid in "${pids[@]}"; do
-  #           if ! wait "$pid"; then
-  #             exit_code=1
-  #           fi
-  #         done
+          # Wait for all, and record if any failed
+          exit_code=0
+          for pid in "${pids[@]}"; do
+            if ! wait "$pid"; then
+              exit_code=1
+            fi
+          done
 
-  #         exit $exit_code
+          exit $exit_code
 
-  #     - name: 🧹 PHP-CS-Fixer checks
-  #       working-directory: centreon-awie
-  #       run: |
-  #         echo "Run of these PHP-CS-Fixer tests: cs:legacy" && set -e
+      - name: 🧹 PHP-CS-Fixer checks
+        working-directory: centreon-awie
+        run: |
+          echo "Run of these PHP-CS-Fixer tests: cs:legacy" && set -e
 
-  #         pids=()
-  #         statuses=()
+          pids=()
+          statuses=()
 
-  #         run_task() {
-  #           name=$1
-  #           shift
-  #           "$@" -- --format=txt --show-progress=none
-  #           result=$?
-  #           if [ $result -eq 0 ]; then
-  #             echo "✅ PHP-CS-Fixer $name: Success"
-  #           else
-  #             echo "❌ PHP-CS-Fixer $name: Failed"
-  #           fi
-  #           return $result
-  #         }
+          run_task() {
+            name=$1
+            shift
+            "$@" -- --format=txt --show-progress=none
+            result=$?
+            if [ $result -eq 0 ]; then
+              echo "✅ PHP-CS-Fixer $name: Success"
+            else
+              echo "❌ PHP-CS-Fixer $name: Failed"
+            fi
+            return $result
+          }
 
-  #         # Start tasks in background
-  #         run_task legacy composer cs:legacy & pids+=($!)
+          # Start tasks in background
+          run_task legacy composer cs:legacy & pids+=($!)
 
-  #         # Wait for all, and record if any failed
-  #         exit_code=0
-  #         for pid in "${pids[@]}"; do
-  #           if ! wait "$pid"; then
-  #             exit_code=1
-  #           fi
-  #         done
+          # Wait for all, and record if any failed
+          exit_code=0
+          for pid in "${pids[@]}"; do
+            if ! wait "$pid"; then
+              exit_code=1
+            fi
+          done
 
-  #         exit $exit_code
+          exit $exit_code
 
-  #     - name: 🔍 PHPStan checks
-  #       working-directory: centreon-awie
-  #       run: |
-  #         echo "Run of these PHPStan tests: stan:legacy" && set -e
+      - name: 🔍 PHPStan checks
+        working-directory: centreon-awie
+        run: |
+          echo "Run of these PHPStan tests: stan:legacy" && set -e
 
-  #         pids=()
-  #         statuses=()
+          pids=()
+          statuses=()
 
-  #         run_task() {
-  #           name=$1
-  #           shift
-  #           "$@" -- --no-progress
-  #           result=$?
-  #           if [ $result -eq 0 ]; then
-  #             echo "✅ PHPStan $name: Success"
-  #           else
-  #             echo "❌ PHPStan $name: Failed"
-  #           fi
-  #           return $result
-  #         }
+          run_task() {
+            name=$1
+            shift
+            "$@" -- --no-progress
+            result=$?
+            if [ $result -eq 0 ]; then
+              echo "✅ PHPStan $name: Success"
+            else
+              echo "❌ PHPStan $name: Failed"
+            fi
+            return $result
+          }
 
-  #         # Start tasks in background
-  #         run_task legacy composer stan:legacy & pids+=($!)
+          # Start tasks in background
+          run_task legacy composer stan:legacy & pids+=($!)
 
-  #         # Wait for all, and record if any failed
-  #         exit_code=0
-  #         for pid in "${pids[@]}"; do
-  #           if ! wait "$pid"; then
-  #             exit_code=1
-  #           fi
-  #         done
+          # Wait for all, and record if any failed
+          exit_code=0
+          for pid in "${pids[@]}"; do
+            if ! wait "$pid"; then
+              exit_code=1
+            fi
+          done
 
-  #         exit $exit_code
+          exit $exit_code
 
   package:
-    # needs: [get-environment, check-version-consistency, backend-lint]
-    needs: [get-environment, check-version-consistency]
+    needs: [get-environment, check-version-consistency, backend-lint]
     if: |
       needs.get-environment.outputs.skip_workflow == 'false' &&
       needs.get-environment.outputs.stability != 'stable' &&
@@ -291,46 +290,42 @@ jobs:
           rpm_gpg_signing_passphrase: ${{ secrets.RPM_GPG_SIGNING_PASSPHRASE }}
           stability: ${{ needs.get-environment.outputs.stability }}
 
-  # deliver-sources:
-  #   runs-on: centreon-common
-  #   needs: [get-environment, package]
-  #   if: |
-  #     needs.get-environment.outputs.skip_workflow == 'false' &&
-  #     contains(fromJson('["stable"]'), needs.get-environment.outputs.stability) &&
-  #     github.event_name != 'workflow_dispatch' &&
-  #     ! cancelled() &&
-  #     ! contains(needs.*.result, 'failure') &&
-  #     ! contains(needs.*.result, 'cancelled') &&
-  #     github.repository == 'centreon/centreon'
+  deliver-sources:
+    runs-on: centreon-common
+    needs: [get-environment, package]
+    if: |
+      needs.get-environment.outputs.skip_workflow == 'false' &&
+      contains(fromJson('["stable"]'), needs.get-environment.outputs.stability) &&
+      github.event_name != 'workflow_dispatch' &&
+      ! cancelled() &&
+      ! contains(needs.*.result, 'failure') &&
+      ! contains(needs.*.result, 'cancelled') &&
+      github.repository == 'centreon/centreon'
 
-  #   steps:
-  #     - name: Checkout sources
-  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-  #     - name: Deliver sources
-  #       uses: ./.github/actions/release-sources
-  #       with:
-  #         bucket_directory: centreon-awie
-  #         module_directory: centreon-awie
-  #         module_name: centreon-awie
-  #         major_version: ${{ needs.get-environment.outputs.major_version }}
-  #         minor_version: ${{ needs.get-environment.outputs.minor_version }}
-  #         token_download_centreon_com: ${{ secrets.TOKEN_DOWNLOAD_CENTREON_COM }}
+      - name: Deliver sources
+        uses: ./.github/actions/release-sources
+        with:
+          bucket_directory: centreon-awie
+          module_directory: centreon-awie
+          module_name: centreon-awie
+          major_version: ${{ needs.get-environment.outputs.major_version }}
+          minor_version: ${{ needs.get-environment.outputs.minor_version }}
+          token_download_centreon_com: ${{ secrets.TOKEN_DOWNLOAD_CENTREON_COM }}
 
   deliver-rpm:
     needs: [changes, get-environment, package]
     if: |
+      needs.get-environment.outputs.skip_workflow == 'false' &&
+      contains(fromJson('["testing", "unstable"]'), needs.get-environment.outputs.stability) &&
+      needs.changes.outputs.trigger_delivery == 'true' &&
       ! cancelled() &&
       ! contains(needs.*.result, 'failure') &&
-      ! contains(needs.*.result, 'cancelled')
-    # if: |
-    #   needs.get-environment.outputs.skip_workflow == 'false' &&
-    #   contains(fromJson('["testing", "unstable"]'), needs.get-environment.outputs.stability) &&
-    #   needs.changes.outputs.trigger_delivery == 'true' &&
-    #   ! cancelled() &&
-    #   ! contains(needs.*.result, 'failure') &&
-    #   ! contains(needs.*.result, 'cancelled') &&
-    #   github.repository == 'centreon/centreon'
+      ! contains(needs.*.result, 'cancelled') &&
+      github.repository == 'centreon/centreon'
     runs-on: centreon-common
 
     strategy:
@@ -358,18 +353,14 @@ jobs:
   deliver-deb:
     needs: [changes, get-environment, package]
     if: |
+      needs.get-environment.outputs.skip_workflow == 'false' &&
+      contains(fromJson('["testing", "unstable"]'), needs.get-environment.outputs.stability) &&
+      needs.changes.outputs.trigger_delivery == 'true' &&
       ! cancelled() &&
       ! contains(needs.*.result, 'failure') &&
-      ! contains(needs.*.result, 'cancelled')
-    # if: |
-    #   needs.get-environment.outputs.skip_workflow == 'false' &&
-    #   contains(fromJson('["testing", "unstable"]'), needs.get-environment.outputs.stability) &&
-    #   needs.changes.outputs.trigger_delivery == 'true' &&
-    #   ! cancelled() &&
-    #   ! contains(needs.*.result, 'failure') &&
-    #   ! contains(needs.*.result, 'cancelled') &&
-    #   github.repository == 'centreon/centreon' &&
-    #   (needs.get-environment.outputs.is_cloud == 'false' || needs.get-environment.outputs.stability == 'unstable')
+      ! contains(needs.*.result, 'cancelled') &&
+      github.repository == 'centreon/centreon' &&
+      (needs.get-environment.outputs.is_cloud == 'false' || needs.get-environment.outputs.stability == 'unstable')
     runs-on: centreon-common
 
     strategy:
@@ -394,14 +385,13 @@ jobs:
 
   promote:
     needs: [get-environment, deliver-rpm, deliver-deb]
-    # if: ${{ false }}
-    # if: |
-    #   needs.get-environment.outputs.skip_workflow == 'false' &&
-    #   (contains(fromJson('["stable", "testing"]'), needs.get-environment.outputs.stability) && github.event_name != 'workflow_dispatch') &&
-    #   ! cancelled() &&
-    #   ! contains(needs.*.result, 'failure') &&
-    #   ! contains(needs.*.result, 'cancelled') &&
-    #   github.repository == 'centreon/centreon'
+    if: |
+      needs.get-environment.outputs.skip_workflow == 'false' &&
+      (contains(fromJson('["stable", "testing"]'), needs.get-environment.outputs.stability) && github.event_name != 'workflow_dispatch') &&
+      ! cancelled() &&
+      ! contains(needs.*.result, 'failure') &&
+      ! contains(needs.*.result, 'cancelled') &&
+      github.repository == 'centreon/centreon'
     runs-on: centreon-common
     strategy:
       matrix:
@@ -425,11 +415,11 @@ jobs:
           release_type: ${{ needs.get-environment.outputs.release_type }}
           is_cloud: ${{ needs.get-environment.outputs.is_cloud }}
 
-  # set-skip-label:
-  #   needs: [get-environment, deliver-rpm, deliver-deb, promote]
-  #   if: |
-  #     needs.get-environment.outputs.skip_workflow == 'false' &&
-  #     ! cancelled() &&
-  #     ! contains(needs.*.result, 'failure') &&
-  #     ! contains(needs.*.result, 'cancelled')
-  #   uses: ./.github/workflows/set-pull-request-skip-label.yml
+  set-skip-label:
+    needs: [get-environment, deliver-rpm, deliver-deb, promote]
+    if: |
+      needs.get-environment.outputs.skip_workflow == 'false' &&
+      ! cancelled() &&
+      ! contains(needs.*.result, 'failure') &&
+      ! contains(needs.*.result, 'cancelled')
+    uses: ./.github/workflows/set-pull-request-skip-label.yml
