fix

diff --git a/.github/workflows/check-status.yml b/.github/workflows/check-status.yml
--- a/.github/workflows/check-status.yml
+++ b/.github/workflows/check-status.yml
@@ -18,9 +18,15 @@ jobs:
   check-status:
     runs-on: ubuntu-24.04
     steps:
-      - uses: actions/github-script@v7
+      - name: Check workflow statuses and display token usage
+        run: |
+          echo "current token usage :"
+          curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit | jq .rate
+          echo ""
+
+      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         env:
-          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PR_NUMBER: ${{ github.event.number }}
         with:
           script: |
@@ -58,77 +64,86 @@ jobs:
                 console.log(`${name} => ${state}`);
               });
 
-              core.info("All jobs are ok")
-              return;
+              if (pending.length === 0) {
+                core.setFailed(`${failure.length} job(s) failed: ${failure.join(', ')}`);
+                return;
+              }
 
               if (failure.length > 0) {
-                core.error(`${failure.length} job(s) failed: ${failure.join(', ')}`);
+                core.setFailed(`${failure.length} job(s) failed: ${failure.join(', ')}`);
                 return;
               }
 
               if (pending.length === 1) {
-                core.info("All jobs are ok")
+                core.info("All jobs are ok");
                 return;
               }
 
-              // throw new Error('failed !!!!');
               await exec.exec("sleep 1s");
             }
+
+            core.setFailed("Timeout: some jobs are still in progress");
 
       - name: Check workflow statuses and display token usage
         run: |
           echo "current token usage :"
-          curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" https://api.github.com/rate_limit | jq .rate
+          curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit | jq .rate
           echo ""
 
-          # sleep 30s
+      # - name: Check workflow statuses and display token usage
+      #   run: |
+      #     echo "current token usage :"
+      #     curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" https://api.github.com/rate_limit | jq .rate
+      #     echo ""
 
-          ITERATIONS=1
-          while [[ $ITERATIONS -le 60 ]]; do
-            PR_CHECKS=$(gh pr checks ${{ env.PR_NUMBER }} --json name,state)
-              # display_token_usage
-              # echo "api"
-              # CHECK_SUITES=$(gh api -H "Accept: application/vnd.github+json" /repos/centreon/centreon/commits/${{ github.event.pull_request.head.sha }}/check-suites | jq '. | .check_suites[] | select(.app.slug == "github-actions")' | jq -r '.conclusion // "pending"') || true
-              # display_token_usage
-              # echo "gh cli"
-              # gh pr checks ${{ env.PR_NUMBER }} --json name,state
-              # display_token_usage
+      #     # sleep 30s
 
-              if [ $(echo "$CHECK_SUITES" | grep -o -i 'pending' | wc -l) -eq 0 ]; then
-                  echo "Cannot get pull request check status"
-                  exit 1
-              fi
+      #     ITERATIONS=1
+      #     while [[ $ITERATIONS -le 60 ]]; do
+      #       PR_CHECKS=$(gh pr checks ${{ env.PR_NUMBER }} --json name,state)
+      #         # display_token_usage
+      #         # echo "api"
+      #         # CHECK_SUITES=$(gh api -H "Accept: application/vnd.github+json" /repos/centreon/centreon/commits/${{ github.event.pull_request.head.sha }}/check-suites | jq '. | .check_suites[] | select(.app.slug == "github-actions")' | jq -r '.conclusion // "pending"') || true
+      #         # display_token_usage
+      #         # echo "gh cli"
+      #         # gh pr checks ${{ env.PR_NUMBER }} --json name,state
+      #         # display_token_usage
 
-              if [ $(echo "$CHECK_SUITES" | wc -w) -eq 1 ]; then
-                  echo "this job is the only triggered one"
-                  exit 0
-              fi
+      #         if [ $(echo "$CHECK_SUITES" | grep -o -i 'pending' | wc -l) -eq 0 ]; then
+      #             echo "Cannot get pull request check status"
+      #             exit 1
+      #         fi
 
-              if [ $(echo "$CHECK_SUITES" | grep -o -i 'failure' | wc -l) -gt 0 ]; then
-                  echo "some jobs have failed"
-                  exit 1
-              fi
+      #         if [ $(echo "$CHECK_SUITES" | wc -w) -eq 1 ]; then
+      #             echo "this job is the only triggered one"
+      #             exit 0
+      #         fi
 
-              # only remaining pending job should be check-status itself
-              if [ $(echo "$CHECK_SUITES" | grep -o -i 'pending' | wc -l) -eq 1 ]; then
-                  echo "all jobs have passed"
-                  exit 0
-              fi
+      #         if [ $(echo "$CHECK_SUITES" | grep -o -i 'failure' | wc -l) -gt 0 ]; then
+      #             echo "some jobs have failed"
+      #             exit 1
+      #         fi
 
-              if [ $ITERATIONS -lt 60 ]; then
-                  echo "some jobs are still in progress, next try in 60 seconds... (tries: $ITERATIONS/60)"
-                  sleep 30s
-                  display_token_usage
-                  sleep 30s
-                  display_token_usage
-              fi
+      #         # only remaining pending job should be check-status itself
+      #         if [ $(echo "$CHECK_SUITES" | grep -o -i 'pending' | wc -l) -eq 1 ]; then
+      #             echo "all jobs have passed"
+      #             exit 0
+      #         fi
 
-              ITERATIONS=$((ITERATIONS+1))
-          done
+      #         if [ $ITERATIONS -lt 60 ]; then
+      #             echo "some jobs are still in progress, next try in 60 seconds... (tries: $ITERATIONS/60)"
+      #             sleep 30s
+      #             display_token_usage
+      #             sleep 30s
+      #             display_token_usage
+      #         fi
 
-          echo "Timeout : some jobs are still in progress"
-          exit 1
-        shell: bash
-        env:
-          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          PR_NUMBER: ${{ github.event.number }}
+      #         ITERATIONS=$((ITERATIONS+1))
+      #     done
+
+      #     echo "Timeout : some jobs are still in progress"
+      #     exit 1
+      #   shell: bash
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+      #     PR_NUMBER: ${{ github.event.number }}
