test

diff --git a/.github/workflows/check-status.yml b/.github/workflows/check-status.yml
--- a/.github/workflows/check-status.yml
+++ b/.github/workflows/check-status.yml
@@ -21,24 +21,16 @@ jobs:
       - uses: actions/checkout@v3
 
       - run: |
-          sleep 10s
+          sleep 30s
 
           ITERATIONS=1
           while [[ $ITERATIONS -le 60 ]]; do
-              #CHECKS=$(gh api -H "Accept: application/vnd.github+json" /repos/centreon/centreon/commits/$(git rev-parse HEAD)/check-suites | jq '. | .check_suites[] | select(.app.slug == "github-actions")' | jq -r .conclusion // "pending")
-              #echo before
-              #echo $CHECKS
-              #echo after
-              #echo $(gh api -H "Accept: application/vnd.github+json" /repos/centreon/centreon/commits/$(git rev-parse HEAD)/check-suites)
-              #CHECKS="$(gh pr checks ${{ github.event.number }})" || true
-              #echo $CHECKS
+              CHECK_SUITES=$(gh api -H "Accept: application/vnd.github+json" /repos/centreon/centreon/commits/${{ github.event.pull_request.head.sha }}/check-suites | jq '. | .check_suites[] | select(.app.slug == "github-actions")' | jq -r '.conclusion // "pending"') || true
 
-              #echo $CHECKS | grep -E -i -c '\s+success\s+'
-
-              #gh api -H "Accept: application/vnd.github+json" /repos/centreon/centreon/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq -r '.check_runs[] | .conclusion // "pending"'
-
-              CHECK_SUITES=$(gh api -H "Accept: application/vnd.github+json" /repos/centreon/centreon/commits/${{ github.event.pull_request.head.sha }}/check-suites | jq '. | .check_suites[] | select(.app.slug == "github-actions")' | jq -r '.conclusion // "pending"')
-              echo $CHECK_SUITES
+              if [ $(echo $CHECK_SUITES | grep -o -i 'pending' | wc -l) -eq 0 ]; then
+                  echo "Cannot get pull request check status"
+                  exit 1
+              fi
 
               if [ $(echo $CHECK_SUITES | wc -w) -eq 1 ]; then
                   echo "this job is the only triggered one"
@@ -55,20 +47,6 @@ jobs:
                   echo "all jobs are passed"
                   exit 0
               fi
-
-              #if [ $(echo $CHECK_SUITES | grep -E -i -c '(^|\s+)pending\s+') -eq 1 ]; then
-              #    CHECK_RUNS=$(gh api -H "Accept: application/vnd.github+json" /repos/centreon/centreon/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq -r '.check_runs[] | .conclusion // "pending"')
-              #    if [ $(echo $CHECK_RUNS | grep -E -i -c '\s+fail\s+') -gt 0 ]; then
-              #        echo "some jobs are failed"
-              #        exit 1
-              #    fi
-
-                  # only remaining pending job should be check-status itself
-              #    if [ $(echo $CHECKS | grep -E -i -c '\s+pending\s+') -eq 1 ]; then
-              #        echo "all jobs are passed"
-              #        exit 0
-              #    fi
-              #fi
 
               if [ $ITERATIONS -lt 60 ]; then
                   echo "some jobs are still in progress, next try in 60 seconds... (tries: $ITERATIONS/30)"
