enh(ci): add workflow to check pr status

diff --git a/.github/workflows/check-status.yml b/.github/workflows/check-status.yml
--- a/.github/workflows/check-status.yml
+++ b/.github/workflows/check-status.yml
@@ -15,17 +15,30 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - run: |
-          #gh pr checks
-          #gh pr view --json checks
+          # defer check
+          sleep 10s
+
           ITERATIONS=1
-          until [ $(gh pr checks | grep -E -i '\s+(fail|pending)\s+') | wc -l) -eq 1 ]; do
-            if [ ${ITERATIONS} -eq 10 ]; then
+          until [ ${ITERATIONS} -le 10 ]; do
+            CHECKS="$(gh pr checks | grep -E -i '\s+(fail|pending)\s+'))"
+            if [ $($CHECKS | grep -E -i '\s+fail\s+' | wc -l) -gt 0 ]; then
+              echo "some jobs are failed"
               exit 1
             fi
 
-            echo "could not invalidate cache, AWS quota might have been reached, retrying in 30 seconds... (tries: ${ITERATIONS}/10)"
-            sleep 30s
+            # only remaining pending job should be check-status itself
+            if [ $($CHECKS | grep -E -i '\s+pending\s+' | wc -l) -eq 1 ]; then
+              echo "all jobs are passed"
+              exit 0
+            fi
+
+            if [ ${ITERATIONS} -lt 10 ]; then
+              echo "some jobs are still in progress, next try in 60 seconds... (tries: ${ITERATIONS}/10)"
+              sleep 60s
+            fi
 
             ITERATIONS=$((ITERATIONS+1))
           done
+
+          exit 1
         shell: bash
