fix

diff --git a/.github/workflows/check-status.yml b/.github/workflows/check-status.yml
--- a/.github/workflows/check-status.yml
+++ b/.github/workflows/check-status.yml
@@ -27,6 +27,8 @@ jobs:
 
               CHECKS=$(gh pr checks ${{ github.event.number }})
               echo $CHECKS
+              echo $CHECKS | grep -E -i '\\s+fail\\s+' | wc -l
+              exit 2
               if [ $(echo $CHECKS | grep -E -i '\\s+fail\\s+' | wc -l) -gt 0 ]; then
                   echo "some jobs are failed"
                   exit 1
