fix(artifacts): add check for existing artifacts before deletion dev-25.10.X (#8882)

diff --git a/.github/workflows/cypress-e2e-parallelization.yml b/.github/workflows/cypress-e2e-parallelization.yml
--- a/.github/workflows/cypress-e2e-parallelization.yml
+++ b/.github/workflows/cypress-e2e-parallelization.yml
@@ -398,19 +398,101 @@ jobs:
       matrix:
         type_of_report: [test-results, test-reports, xray-reports]
     steps:
+      - name: Check artifacts exist before merge
+        id: check_artifacts_for_merge
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          pattern="${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}"
+          run_id=${{ github.run_id }}
+          found=false
+          timeout=80       # maximum wait time in seconds
+          interval=5       # interval between each check
+          elapsed=0
+
+          while [ $elapsed -lt $timeout ]; do
+            # Retrieve artifact names of the current run without quotes
+            artifacts=$(gh api repos/${{ github.repository }}/actions/artifacts \
+            --jq ".artifacts[] | select(.workflow_run.id == $run_id) | .name" | tr -d '"')
+
+            merge_list=""
+            while read -r artifact; do
+              echo "Checking artifact: $artifact"
+              if [[ "$artifact" == *"$pattern"* ]]; then
+                merge_list="$merge_list $artifact"
+              fi
+            done <<< "$artifacts"
+
+            if [ -n "$merge_list" ]; then
+              echo "Found artifact(s): $merge_list"
+              found=true
+              break
+            fi
+
+            echo "Artifacts not found yet, waiting $interval seconds..."
+            sleep $interval
+            elapsed=$((elapsed + interval))
+          done
+
+          echo "DEBUG: found='$found'"
+          echo "found=$found" >> $GITHUB_OUTPUT
+        shell: bash
+
       - name: Merge Artifacts
         uses: actions/upload-artifact/merge@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
-        if: ${{ ( contains(needs.cypress-e2e-test-run.result, 'failure') && ( matrix.type_of_report == 'test-results' || matrix.type_of_report == 'test-reports' ) ) || matrix.type_of_report == 'xray-reports' }}
+        if: steps.check_artifacts_for_merge.outputs.found == 'true' &&
+            (( contains(needs.cypress-e2e-test-run.result, 'failure') &&
+              (matrix.type_of_report == 'test-results' || matrix.type_of_report == 'test-reports') ) ||
+            matrix.type_of_report == 'xray-reports')
         with:
           name: ${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}
           pattern: ${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}-*
-          delete-merged: false # cannot be set to true due to random fails: Failed to DeleteArtifact: Unable to make request: ECONNRESET
+          delete-merged: false
           retention-days: 1
+
+      - name: Check if artifact exists
+        id: check_artifact
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          echo "Checking artifact: ${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}-*"
+          artifacts=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[].name')
+          if echo "$artifacts" | grep -q "${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}"; then
+            echo "found=true" >> $GITHUB_OUTPUT
+          else
+            echo "found=false" >> $GITHUB_OUTPUT
+          fi
+        shell: bash
+
+      - name: Wait until artifacts are ready for deletion
+        id: wait_artifacts
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+            pattern="${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}"
+            found=false
+            timeout=60       # maximum wait time in seconds
+            interval=5       # interval between each check
+            elapsed=0
+
+            while [ $elapsed -lt $timeout ]; do
+              artifacts=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[].name')
+              if echo "$artifacts" | grep -q "$pattern"; then
+                found=true
+                break
+              fi
+              echo "Artifacts not ready yet, waiting $interval seconds..."
+              sleep $interval
+              elapsed=$((elapsed + interval))
+            done
+
+            echo "found=$found" >> $GITHUB_OUTPUT
+        shell: bash
 
       - name: Delete merged artifacts
         if: |
-          success() ||
-          ( failure() && matrix.type_of_report == 'test-results' )
+          ( success() || ( failure() && matrix.type_of_report == 'test-results' ) ) &&
+          steps.check_artifact.outputs.found == 'true'
         uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
         with:
           name: ${{ inputs.name }}-${{ inputs.os }}-${{ matrix.type_of_report }}-*
