fix(ci): merge cypress-e2e-testing reusable into cypress-e2e-parallelization workflow

diff --git a/.github/workflows/cypress-e2e-parallelization.yml b/.github/workflows/cypress-e2e-parallelization.yml
--- a/.github/workflows/cypress-e2e-parallelization.yml
+++ b/.github/workflows/cypress-e2e-parallelization.yml
@@ -205,22 +205,46 @@ jobs:
       - name: Cypress end-to-end testing
         uses: cypress-io/github-action@b8ba51a856ba5f4c15cf39007636d4ab04f23e3c # v6.10.2
         with:
-          name: ${{ inputs.name }}
-          database_image: ${{ inputs.database_image }}
-          web_image_os: ${{ inputs.os }}
-          web_image_version: ${{ env.IMAGE_TAG }}
-          openid_image_version: ${{ inputs.major_version }}
-          saml_image_version: ${{ inputs.major_version }}
-          module: centreon
-          feature_file_path: ${{ matrix.feature }}
-          test_tags: ${{ inputs.test_tags }}
-          dependencies_lock_file: ${{ inputs.dependencies_lock_file }}
-          test_execution_key: ${{ steps.get-test-execution-key.outputs.test_execution_key }}
-          stability: ${{ inputs.stability }}
-          target_stability: ${{ inputs.target_stability }}
-          is_cloud: ${{ inputs.is_cloud }}
-          artifactory_internal_repo_username: ${{ secrets.artifactory_internal_repo_username }}
-          artifactory_internal_repo_password: ${{ secrets.artifactory_internal_repo_password }}
+          command: pnpm run cypress:run --browser electron --spec features/**/${{ matrix.feature }} --env tags="${{ inputs.test_tags }}"
+          install: false
+          working-directory: ${{ inputs.module_name }}/tests/e2e
+        env:
+          CYPRESS_VERIFY_TIMEOUT: "60000"
+          CYPRESS_DATABASE_IMAGE: ${{ inputs.database_image }}
+          CYPRESS_WEB_IMAGE_OS: ${{ inputs.os }}
+          CYPRESS_WEB_IMAGE_VERSION: ${{ env.IMAGE_TAG }}
+          CYPRESS_OPENID_IMAGE_VERSION: ${{ inputs.major_version }}
+          CYPRESS_SAML_IMAGE_VERSION: ${{ inputs.major_version }}
+          CYPRESS_STABILITY: ${{ inputs.stability }}
+          CYPRESS_TARGET_STABILITY: ${{ inputs.target_stability }}
+          CYPRESS_IS_CLOUD: ${{ inputs.is_cloud }}
+          CYPRESS_INTERNAL_REPO_USERNAME: ${{ secrets.artifactory_internal_repo_username }}
+          CYPRESS_INTERNAL_REPO_PASSWORD: ${{ secrets.artifactory_internal_repo_password }}
+
+      - name: Ensure logs directory exists
+        run: mkdir -p ${{ inputs.module_name }}/tests/e2e/results/cucumber-logs/
+        shell: bash
+
+      - name: Rename JSON report
+        if: ${{ always() }}
+        run: |
+          feature_name=$(basename "${{ matrix.feature }}")
+          report_path="${{ inputs.module_name }}/tests/e2e/results/cucumber-logs/report.json"
+          report_path_updated="${{ inputs.module_name }}/tests/e2e/results/cucumber-logs/${feature_name}-report.json"
+
+          if [ -f "$report_path" ]; then
+            jq 'if length > 0 then .[0] |= (.tags |= map(if .name | startswith("@REQ_MON-") then .name |= "@${{ steps.get-test-execution-key.outputs.test_execution_key }}" else . end)) | (.[] |= (if has("elements") then .elements[].tags |= map(if .name | startswith("@REQ_MON-") then .name |= "@${{ steps.get-test-execution-key.outputs.test_execution_key }}" else . end) else . end)) else . end' "$report_path" > "$report_path_updated"
+            rm "$report_path"
+
+            # Show the content of the modified file
+            echo "::group::${feature_name}-report.json"
+            cat "$report_path_updated"
+            echo "::endgroup::"
+          else
+            echo "Report file not found: $report_path"
+            exit 1
+          fi
+        shell: bash
 
       - name: Replace / with - in the feature path
         id: feature-path
