add copout for 24.04

diff --git a/.github/workflows/docker-stable.yml b/.github/workflows/docker-stable.yml
--- a/.github/workflows/docker-stable.yml
+++ b/.github/workflows/docker-stable.yml
@@ -93,8 +93,8 @@ jobs:
             echo "is_cloud=false" >> $GITHUB_OUTPUT
             case "${major_version}" in
               24.04)
-                DISTRIBS=("alma8" "alma9" "bullseye" "bookworm" "jammy")
-                ;;
+                echo "::error::The workflow does not work on 24.04 version."
+                exit 1
               24.10)
                 DISTRIBS=("alma8" "alma9" "bookworm" "noble")
                 ;;
