fix

diff --git a/.github/workflows/gorgone.yml b/.github/workflows/gorgone.yml
--- a/.github/workflows/gorgone.yml
+++ b/.github/workflows/gorgone.yml
@@ -113,6 +113,68 @@ jobs:
           rpm_gpg_signing_key_id: ${{ secrets.RPM_GPG_SIGNING_KEY_ID }}
           rpm_gpg_signing_passphrase: ${{ secrets.RPM_GPG_SIGNING_PASSPHRASE }}
 
+  dockerize:
+    runs-on: ubuntu-22.04
+    needs: [get-version, package]
+
+    strategy:
+      fail-fast: false
+      matrix:
+        os: ${{ fromJson(needs.get-version.outputs.dockerize_matrix) }}
+
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v4
+
+      - name: Generate information according to matrix os
+        id: matrix_include
+        run: |
+          if [ "${{ matrix.os }}" = "alma8" ]; then
+            DISTRIB=el8
+            PACKAGE_EXTENSION=rpm
+          elif [ "${{ matrix.os }}" = "alma9" ]; then
+            DISTRIB=el9
+            PACKAGE_EXTENSION=rpm
+          elif [ "${{ matrix.os }}" = "bullseye" ]; then
+            DISTRIB=bullseye
+            PACKAGE_EXTENSION=deb
+          else
+            echo "::error::${{ matrix.os }} is not managed"
+            exit 1
+          fi
+
+          echo "distrib=$DISTRIB" >> $GITHUB_OUTPUT
+          echo "package_extension=$PACKAGE_EXTENSION" >> $GITHUB_OUTPUT
+        shell: bash
+
+      - name: Login to registry
+        uses: docker/login-action@v2
+        with:
+          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
+          username: ${{ secrets.DOCKER_REGISTRY_ID }}
+          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
+
+      - name: Restore ${{ steps.matrix_include.outputs.package_extension }} files
+        uses: actions/cache/restore@v3
+        with:
+          path: ./*.${{ steps.matrix_include.outputs.package_extension }}
+          key: cache-${{ github.sha }}-${{ steps.matrix_include.outputs.package_extension }}-centreon-gorgone-${{ steps.matrix_include.outputs.distrib }}-${{ github.head_ref || github.ref_name }}
+          fail-on-cache-miss: true
+
+      - uses: docker/setup-buildx-action@v2
+
+      - name: Build and push fresh image
+        uses: docker/build-push-action@v3
+        with:
+          file: .github/docker/centreon-gorgone/${{ matrix.os }}/Dockerfile
+          context: .
+          build-args: |
+            "REGISTRY_URL=${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}"
+            "VERSION=${{ needs.get-version.outputs.major_version }}"
+          pull: true
+          push: false
+          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/centreon-gorgone-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
+
   deliver-sources:
     runs-on: [self-hosted, common]
     needs: [get-version, package]
