test new changes

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -67,7 +67,7 @@ jobs:
 
   associate-test-cases:
     runs-on: ubuntu-22.04
-    # if: ${{ contains(fromJson('["testing","unstable"]'), inputs.stability) }}
+    if: ${{ contains(fromJson('["canary","stable"]'), inputs.stability) }}
 
     outputs:
       test_execution_id: ${{ steps.get-test-ids.outputs.test_execution_id }}
@@ -116,7 +116,7 @@ jobs:
           echo "Response from Get Test Plan:"
           echo "$response"
 
-          # Parsing and processing tests id
+          # Parsing and processing test IDs
           issue_ids=($(echo "$response" | jq -r '.data.getTestPlan.tests.results[] | select(.testType.name == "API") | .issueId'))
 
           summaries=()
@@ -152,6 +152,8 @@ jobs:
             }
           }'
 
+          existing_test_case_ids=("${issue_ids[@]}")
+
           for collection_file in "${collections[@]}"; do
             collection_name=$(basename "$collection_file" .postman_collection.json)
             collection_name_sanitized="${collection_name//[^a-zA-Z0-9]/_}"
@@ -159,7 +161,7 @@ jobs:
             if [[ " ${summaries[@]} " =~ " ${collection_name_sanitized} " ]]; then
               echo "The test case for $collection_name_sanitized already exists in the test plan."
             else
-              # Adding new test case
+              # Adding a new test case
               response=$(curl --request POST \
                 --url 'https://centreon.atlassian.net/rest/api/2/issue' \
                 --user '${{ secrets.jira_user }}:${{ secrets.jira_token_test }}' \
@@ -186,26 +188,30 @@ jobs:
                 echo "Failed to create the test case within the specified time."
               else
                 test_case_id=$(echo "$response" | jq -r '.id')
-                test_case_ids+=("$test_case_id")
 
-                echo "Created Test Case with ID: $test_case_id"
-                summaries+=("$collection_name_sanitized")
+                # Checking if the test case is a new one
+                if [[ ! " ${existing_test_case_ids[@]} " =~ " ${test_case_id} " ]]; then
+                  echo "New Test Case with ID: $test_case_id"
+                  summaries+=("$collection_name_sanitized")
 
-                # Update GraphQL query to add this test to the test plan
-                xray_graphql_AddingTestsToTestPlan_variables=$(echo "$xray_graphql_AddingTestsToTestPlan" | jq --arg test_case_id "$test_case_id" '.variables.testIssueIds += [$test_case_id]')
+                  # Update GraphQL query to add this test to the test plan
+                  xray_graphql_AddingTestsToTestPlan_variables=$(echo "$xray_graphql_AddingTestsToTestPlan" | jq --arg test_case_id "$test_case_id" '.variables.testIssueIds += [$test_case_id]')
 
-                # Execute GraphQL mutation to update the testType
-                testType_mutation_response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token }}" --data '{"query": "mutation { updateTestType(issueId: \"'$test_case_id'\", testType: {name: \"API\"} ) { issueId testType { name kind } } }"}' "https://xray.cloud.getxray.app/api/v2/graphql")
+                  # Execute the GraphQL mutation to update the testType only for new test cases
+                  testType_mutation_response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token }}" --data '{"query": "mutation { updateTestType(issueId: \"'$test_case_id'\", testType: {name: \"API\"} ) { issueId testType { name kind } } }"}' "https://xray.cloud.getxray.app/api/v2/graphql")
 
-                # Check if the mutation was successful
-                if [ "$(echo "$testType_mutation_response" | jq -r '.data.updateTestType')" != "null" ]; then
-                  echo "Successfully updated testType to API for Test Case with ID: $issue_id"
+                  # Checking if the mutation was successful
+                  if [ "$(echo "$testType_mutation_response" | jq -r '.data.updateTestType')" != "null" ]; then
+                    echo "Successfully updated testType to API for Test Case with ID: $test_case_id"
+                  else
+                    echo "Failed to update testType for Test Case with ID: $test_case_id"
+                  fi
+
+                  # Execute the GraphQL mutation to add tests to the test plan
+                  response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$xray_graphql_AddingTestsToTestPlan_variables" "https://xray.cloud.getxray.app/api/v2/graphql")
                 else
-                  echo "Failed to update testType for Test Case with ID: $issue_id"
+                  echo "Test Case with ID $test_case_id already exists in the test plan."
                 fi
-
-                # Execute GraphQL mutation to add tests to the test plan
-                response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$xray_graphql_AddingTestsToTestPlan_variables" "https://xray.cloud.getxray.app/api/v2/graphql")
               fi
             fi
           done
@@ -363,7 +369,7 @@ jobs:
           done
 
       - name: Change test execution status
-        if: ${{ contains(fromJson('["canary", "stable"]'), inputs.stability) || failure() }}
+        if: ${{ contains(fromJson('["canary","stable"]'), inputs.stability) || failure() }}
         run: |
           for summary_file in ./postman_summaries/*.json; do
           test_execution_id=${{ needs.associate-test-cases.outputs.test_execution_id }}
@@ -446,7 +452,7 @@ jobs:
             done
 
       - name: Perform Jira Transitions
-        if: ${{ contains(fromJson('["canary", "stable"]'), inputs.stability) }}
+        if: ${{ contains(fromJson('["canary","stable"]'), inputs.stability) }}
         run: |
               test_plan_id=${{ needs.associate-test-cases.outputs.test_plan_id }}
               transition_ids=("61" "81" "21" "31")
