Adding some rectifications

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -91,18 +91,18 @@ jobs:
 
     - name: Run Postman Tests and Generate HTML Report
       run: |
-        set -e
         collection_file="collections/${{ matrix.feature }}"
         collection_name=$(basename "$collection_file" .postman_collection.json)
         collection_directory="$(dirname "$collection_file")"
         environment_file="$collection_directory/Environment-Collection.json"
-        if [ -f "$environment_file" ]; then
-          pnpm newman run "$collection_file" -e "$environment_file" --reporters cli,htmlextra,json-summary --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html" --reporter-summary-json-export "postman_summaries/${collection_name}-summary.json"
-        else
-          echo "The file Environment-Collection.json was not found in the same directory as $collection_file"
-          exit 1
+        test_result=$(pnpm newman run "$collection_file" -e "$environment_file" --reporters cli,htmlextra,json-summary --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html" --reporter-summary-json-export "postman_summaries/${collection_name}-summary.json" --bail)
+        if [[ $test_result == *"failed"* ]]; then
+          echo "Some tests have failed."
+          exit 1  
+          echo "All tests have passed."
         fi
-
+      continue-on-error: true
+        
     - name: Upload HTML Reports
       uses: actions/upload-artifact@v3
       with:
