get newman summary

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -54,9 +54,21 @@ jobs:
         run: |
           environment_path="collections/Environment-for-Refactored-API-Test-Collection.json"
           collection_path="collections"
+          report_directory="centreon/tests/rest_api/newman"
 
           # Create a directory to store HTML reports
-          mkdir -p newman
+          mkdir -p "$report_directory"
+
+          # Initialize variables to store test results
+          tests_passed=0
+          tests_failed=0
+          tests_skipped=0
+
+          # Create a summary file (Markdown ou HTML) containing the Newman reports content
+          echo "Robot Results" > newman_reports_summary.md
+          echo "✅ Passed	❌ Failed	⏭️ Skipped	Total	Pass %" >> newman_reports_summary.md
+          echo "397	6	0	403	98.51" >> newman_reports_summary.md
+          echo "Failed Tests" >> newman_reports_summary.md
 
           # Iterate over each Postman collection file in the specified directory
           for collection_file in "$collection_path"/*.postman_collection.json; do
@@ -64,9 +76,30 @@ jobs:
             collection_name=$(basename "$collection_file" .postman_collection.json)
 
             # Run Newman with the current collection file and generate an HTML report
-            pnpm newman run "$collection_file" -e "$environment_path" --reporters cli,htmlextra --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html"  || true
+            pnpm newman run "$collection_file" -e "$environment_path" --reporters cli,htmlextra,json --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "$report_directory/${collection_name}.html" --reporter-json-export "$report_directory/${collection_name}.json" || true
+
+            # Extract test results from the JSON report and update variables
+            current_results=$(jq -r '.run.stats.tests' "$report_directory/${collection_name}.json")
+            current_passed=$(echo "$current_results" | jq -r '.passed')
+            current_failed=$(echo "$current_results" | jq -r '.failed')
+            current_skipped=$(echo "$current_results" | jq -r '.skipped')
+            
+            tests_passed=$((tests_passed + current_passed))
+            tests_failed=$((tests_failed + current_failed))
+            tests_skipped=$((tests_skipped + current_skipped))
+
+            # Create a summary file for the current collection
+            echo "" >> newman_reports_summary.md
+            echo "Collection: $collection_name" >> newman_reports_summary.md
+            echo "Tests Passed: $current_passed" >> newman_reports_summary.md
+            echo "Tests Failed: $current_failed" >> newman_reports_summary.md
+            echo "Tests Skipped: $current_skipped" >> newman_reports_summary.md
           done
-        working-directory: centreon/tests/rest_api  
+
+          # Set the Newman reports summary content as a GitHub environment variable
+          echo "newman_reports_summary=$(cat newman_reports_summary.md)" >> $GITHUB_ENV
+
+        working-directory: centreon/tests/rest_api
 
       - name: Upload HTML Reports
         uses: actions/upload-artifact@v2
@@ -79,3 +112,6 @@ jobs:
       - name: Continue to Next Collection
         if: ${{ always() }}
         run: echo "Continuing to the next collection..."
+
+      - name: Display Newman Reports Summary
+        run: echo "## Newman Reports Summary\n\n${{ env.newman_reports_summary }}" >> $GITHUB_ENV
