some changements

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -128,11 +128,24 @@ jobs:
           echo "Found XML file: $file"
           cat "$file"
         done
+    - name: Generate Xray Token
+      id: generate-xray-token
+      run: |
+          set -x
+          client_id='DB1C58D167BC4BE798DCFB8CA1C712B9'
+          client_secret='296443a35f9c668c86c362f57d3b87ef9327d75825d3aa7f22426bcaf9e874cf'
 
-    - name: Verify CLIENT_ID Secret
-      run: "echo CLIENT_ID: ${{ secrets.CLIENT_ID }}"
+          token_response=$(curl -H "Content-Type: application/json" -X POST --data "{\"client_id\": \"$client_id\", \"client_secret\": \"$client_secret\"}" "https://xray.cloud.getxray.app/api/v1/authenticate" | jq -r '.access_token')
 
+          if [[ -z "$token_response" ]]; then
+            echo "Failed to retrieve Xray token"
+            exit 1
+          fi
 
+          xray_token=$(echo "$token_response" | sed -n 's/."\(.\)".*/\1/p')
+          echo "this is the xray token : $xray_token"
+          echo "xray_token=$xray_token" >> $GITHUB_ENV  # Stocke la variable dans l'environnement
+      shell: bash
     # - name: Import results to Xray
     #   uses: mikepenz/xray-action@v3.0.2
     #   with:
@@ -146,15 +159,12 @@ jobs:
     #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
     #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
 
+    - name: Debug GraphQL Request
+      run: |
+        echo "${{ steps.generate-xray-token.outputs.xray_token }}"
 
     - name: Associate Test Cases with Test Execution
       run: |
-        token_response=$(curl -H "Content-Type: application/json" -X POST --data "{\"client_id\": \"${{ secrets.CLIENT_ID }}\", \"client_secret\": \"${{ secrets.CLIENT_SECRET }}\"}" "https://xray.cloud.getxray.app/api/v1/authenticate")
-        xray_token=$(echo "$token_response" | sed -n 's/."\(.\)".*/\1/p')
-        echo "this is the xray token : $xray_token"
-        echo "xray_token=$xray_token"
-
-
         collections=($(find ./collections -type f -name "*.postman_collection.json"))
         for collection_file in "${collections[@]}"; do
           collection_name=$(basename "$collection_file" .postman_collection.json)
@@ -190,8 +200,9 @@ jobs:
               "testIssueIds": ["23208"]
             }
           }'
-          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $xray_token" --data "${xray_graphql_mutation}" "https://xray.cloud.getxray.app/api/v2/graphql"
-        done
+          xray_token="${{ env.xray_token }}"
+          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $xray_token" --data "$xray_graphql_mutation" "https://xray.cloud.getxray.app/api/v2/graphql"
+          done
 
     - name: Extract and Store Summaries
       if: failure()
