Adding some rectifications

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -136,28 +136,26 @@ jobs:
 
     - name: Generate and Display Summaries
       run: |
-        has_failures=false
+        summaries=""
+        has_failures=false 
         for summary_file in ./postman_summaries/*.json; do
             collection_name=$(jq -r '.Collection.Info.Name' "$summary_file")
             total_requests=$(jq -r '.Run.Stats.Requests.total' "$summary_file")
             pending_requests=$(jq -r '.Run.Stats.Requests.pending' "$summary_file")
             failed_requests=$(jq -r '.Run.Stats.Requests.failed' "$summary_file")
             failed_assertions=$(jq -r '.Run.Stats.Assertions.failed' "$summary_file")
-        
             summary_content=$(cat "$summary_file" | jq -c '{Name: .Collection.Info.Name, Stats: .Run.Stats, Failures: .Run.Failures}')
-        
             if [ "$failed_requests" -gt 0 ] || [ "$failed_assertions" -gt 0 ]; then
                 has_failures=true  # Set has_failures to true if there are failures
                 summaries+="<table>"
                 summaries+="<tr><th>Collection Name</th><th>Total Requests</th><th>⏭️ Skipped requests</th><th>❌ Failed Requests</th><th>❌ Failed Assertions</th></tr>"
                 summaries+="<tr><td>$collection_name</td><td>$total_requests</td><td>$pending_requests</td><td>$failed_requests</td><td>$failed_assertions</td></tr>"
-                summaries+="<tr><td colspan='5'><strong>Failed Iterations:</strong></td></tr>"
-        
+                
                 for failure in $(jq -c '.Failures[]' <<< "$summary_content"); do
-                    failure_message=$(jq -r '.Error.Message' <<< "$failure")
-                    test_name=$(jq -r '.Test' <<< "$failure")
-                    summaries+="<tr><td colspan='5'>$test_name: $failure_message</td></tr>"
-                done
+                failure_message=$(jq -r '.Error.Message' <<< "$failure")
+                test_name=$(jq -r '.Test' <<< "$failure")
+                summaries+="<tr><td colspan='5'>$test_name: $failure_message</td></tr>"
+            done
                 summaries+="</table>"
             fi
             echo "Processing summary file: $summary_file"
@@ -168,5 +166,5 @@ jobs:
         fi
         
         if [ "$has_failures" = true ]; then
-            exit 1
+           exit 1
         fi
