Adding some rectifications

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -137,6 +137,7 @@ jobs:
       run: |
         summaries=""
         has_failures=false 
+        
         for summary_file in ./postman_summaries/*.json; do
             collection_name=$(jq -r '.Collection.Info.Name' "$summary_file")
             total_requests=$(jq -r '.Run.Stats.Requests.total' "$summary_file")
@@ -144,30 +145,34 @@ jobs:
             failed_requests=$(jq -r '.Run.Stats.Requests.failed' "$summary_file")
             failed_assertions=$(jq -r '.Run.Stats.Assertions.failed' "$summary_file")
             failures=$(jq -r '.Run.Failures' "$summary_file")
-            echo "$failures"   
-             if [ "$failed_requests" -gt 0 ] || [ "$failed_assertions" -gt 0 ]; then
+        
+            # Vérifier si la variable failures n'est pas vide
+            if [ -n "$failures" ] && ( [ "$failed_requests" -gt 0 ] || [ "$failed_assertions" -gt 0 ] ); then
                 has_failures=true   
                 summaries+="<table>"
                 summaries+="<tr><th>Collection Name</th><th>Total Requests</th><th>⏭️ Skipped requests</th><th>❌ Failed Requests</th><th>❌ Failed Assertions</th></tr>"
                 summaries+="<tr><td>$collection_name</td><td>$total_requests</td><td>$pending_requests</td><td>$failed_requests</td><td>$failed_assertions</td></tr>"
-                summaries+="<tr><td colspan='5'>"
-                for failure in $(echo "$failures" | jq -r '.[]'); do
-                  parent_name=$(echo "$failure" | jq -r '.Parent.Name')
-                  source_name=$(echo "$failure" | jq -r '.Source.Name')
-                  error_message=$(echo "$failure" | jq -r '.Error.Message')
-                  echo "$parent_name "
-                  summaries+="<tr><td><strong>Parent Name:</strong> $parent_name<br><strong>Source Name:</strong> $source_name<br><strong>Error Message:</strong> $error_message</td></tr>"
-                done
-                summaries+="</td></tr>"
+                summaries+="<tr><td colspan='5'><table>"
+        
+                while IFS= read -r failure; do
+                    parent_name=$(echo "$failure" | jq -r '.Parent.Name')
+                    source_name=$(echo "$failure" | jq -r '.Source.Name')
+                    error_message=$(echo "$failure" | jq -r '.Error.Message')
+        
+                    summaries+="<tr><td><strong>Parent Name:</strong> $parent_name<br><strong>Source Name:</strong> $source_name<br><strong>Error Message:</strong> $error_message</td></tr>"
+                done <<< "$failures"
+        
+                summaries+="</table></td></tr>"
                 summaries+="</table>"
             fi
+        
             echo "Processing summary file: $summary_file"
-         done
+        done
         
         if [ -n "$summaries" ]; then
             echo -e "$summaries" >> $GITHUB_STEP_SUMMARY
         fi
         
         if [ "$has_failures" = true ]; then
-           exit 1
+          exit 1
         fi
