Adding some rectifications

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -143,11 +143,25 @@ jobs:
             pending_requests=$(jq -r '.Run.Stats.Requests.pending' "$summary_file")
             failed_requests=$(jq -r '.Run.Stats.Requests.failed' "$summary_file")
             failed_assertions=$(jq -r '.Run.Stats.Assertions.failed' "$summary_file")
-            if [ "$failed_requests" -gt 0 ] || [ "$failed_assertions" -gt 0 ]; then
+            
+            # Ajoutez cette ligne pour extraire les échecs
+            failures=$(jq -c '.Run.Failures' "$summary_file")
+            
+            if [ "$failed_requests" -gt 0 ] || [ "$failed_assertions" -gt 0 ] || [ "$failures" != "[]" ]; then
                 has_failures=true  # Set has_failures to true if there are failures
                 summaries+="<table>"
-                summaries+="<tr><th>Collection Name</th><th>Total Requests</th><th>⏭️ Skipped requests</th><th>❌ Failed Requests</th><th>❌ Failed Assertions</th></tr>"
-                summaries+="<tr><td>$collection_name</td><td>$total_requests</td><td>$pending_requests</td><td>$failed_requests</td><td>$failed_assertions</td></tr>"
+                summaries+="<tr><th>Collection Name</th><th>Total Requests</th><th>⏭️ Skipped requests</th><th>❌ Failed Requests</th><th>❌ Failed Assertions</th><th>Failures</th></tr>"
+                summaries+="<tr><td>$collection_name</td><td>$total_requests</td><td>$pending_requests</td><td>$failed_requests</td><td>$failed_assertions</td><td>"
+                
+                # Parcourez la liste des échecs et ajoutez-les au tableau
+                for failure in $(jq -c '.Run.Failures[]' "$summary_file"); do
+                    parent_name=$(jq -r '.Parent.Name' <<< "$failure")
+                    source_name=$(jq -r '.Source.Name' <<< "$failure")
+                    error_message=$(jq -r '.Error.Message' <<< "$failure")
+                    summaries+="<p><strong>Parent Name:</strong> $parent_name<br><strong>Source Name:</strong> $source_name<br><strong>Error Message:</strong> $error_message</p>"
+                done
+                
+                summaries+="</td></tr>"
                 summaries+="</table>"
             fi
             echo "Processing summary file: $summary_file"
@@ -158,5 +172,5 @@ jobs:
         fi
         
         if [ "$has_failures" = true ]; then
-           exit 1
+          exit 1
         fi
