adding some fixes

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -57,8 +57,8 @@ jobs:
   associate-test-cases:
       runs-on: ubuntu-22.04
       outputs:
-        test_exec: ${{ steps.xray-newman.outputs.test_exec }}
-        test_plan_id: ${{ steps.get-testPlan-id.outputs.testPlan_id }}
+        test_execution_id: ${{ steps.xray-newman.outputs.test_execution-id }}
+        test_plan_id: ${{ steps.get-test-plan-id.outputs.test_plan_id }}
 
       defaults:
        run:
@@ -109,12 +109,12 @@ jobs:
             echo "testPlanKey=$testPlanKey" >> $GITHUB_OUTPUT
 
         - name: Get TestPlan ID
-          id: get-testPlan-id
+          id: get-test-plan-id
           run: |
               jira_url="https://centreon.atlassian.net/rest/api/2/issue/${{ steps.determine-testplan-key.outputs.testPlanKey }}"
               testPlan_id=$(curl -u "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_TOKEN_TEST }}" -X GET -s "$jira_url" | jq -r '.id')
               echo "this is the testPlan ID : $testPlan_id"
-              echo "testPlan_id=$testPlan_id" >> $GITHUB_OUTPUT
+              echo "test_plan_id=$testPlan_id" >> $GITHUB_OUTPUT
 
         - name: Associate Test Cases with Test plan
           id: xray-newman
@@ -122,7 +122,7 @@ jobs:
             xray_graphql_getTestPlan='{
               "query": "query GetTestPlan($issueId: String) { getTestPlan(issueId: $issueId) { issueId tests(limit: 100) { results { issueId testType { name } } } } }",
               "variables": {
-                "issueId": "${{ steps.get-testPlan-id.outputs.testPlan_id }}"
+                "issueId": "${{ steps.get-test-plan-id.outputs.test_plan_id }}"
               }
             }'
 
@@ -147,7 +147,7 @@ jobs:
               summary=$(echo "$response" | jq -r '.fields.summary')
 
               if [ "$response_code" -eq 404 ]; then
-               echo "The issue with ID $issue_id does not exist or you do not have permission to see it."
+                echo "The issue with ID $issue_id does not exist or you do not have permission to see it."
                 break
               else
                 echo "The issue with ID $issue_id exists."
@@ -161,7 +161,7 @@ jobs:
             xray_graphql_AddingTestsToTestPlan='{
               "query": "mutation AddTestsToTestPlan($issueId: String!, $testIssueIds: [String]!) { addTestsToTestPlan(issueId: $issueId, testIssueIds: $testIssueIds) { addedTests warning } }",
               "variables": {
-                "issueId": "${{ steps.get-testPlan-id.outputs.testPlan_id }}",
+                "issueId": "${{ steps.get-test-plan-id.outputs.test_plan_id }}",
                 "testIssueIds": []
               }
             }'
@@ -246,21 +246,21 @@ jobs:
             echo "$response"
 
             # Extract the ID of the new test run
-            test_execution_id=$(echo "$response" | jq -r '.data.createTestExecution.testExecution.issueId')
+            test-execution-id=$(echo "$response" | jq -r '.data.createTestExecution.testExecution.issueId')
 
             # Check if ID is null or not
-            if [ "$test_execution_id" == "null" ]; then
+            if [ "$test-execution-id" == "null" ]; then
               echo "Failed to create the Test Execution. Check the response for errors."
             else
-              echo "Created Test Execution with ID: $test_execution_id"
-              echo "test_exec=$test_execution_id" >> $GITHUB_OUTPUT
+              echo "Created Test Execution with ID: $test-execution-id"
+              echo "test_execution_id=$test-execution-id" >> $GITHUB_OUTPUT
               fi
 
             xray_graphql_addTestExecutionsToTestPlan='{
               "query": "mutation AddTestExecutionsToTestPlan($issueId: String!, $testExecIssueIds: [String]!) { addTestExecutionsToTestPlan(issueId: $issueId, testExecIssueIds: $testExecIssueIds) { addedTestExecutions warning } }",
               "variables": {
-                "issueId": "${{ steps.get-testPlan-id.outputs.testPlan_id }}",
-                "testExecIssueIds": ["'$test_execution_id'"]
+                "issueId": "${{ steps.get-test-plan-id.outputs.test_plan_id }}",
+                "testExecIssueIds": ["'$test-execution-id'"]
               }
             }'
             response=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$xray_graphql_addTestExecutionsToTestPlan" -v "https://xray.cloud.getxray.app/api/v2/graphql")
@@ -337,10 +337,10 @@ jobs:
         environment_file=$(find "$collection_directory" -maxdepth 1 -type f -name "*.postman_environment.json")
         if [ -f "$environment_file" ]; then
           echo "Environment: $environment_file"
-           pnpm newman run "$collection_file" -e "$environment_file" --reporters cli,htmlextra,json-summary --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html" --reporter-summary-json-export "postman_summaries/${collection_name}-summary.json"
+            pnpm newman run "$collection_file" -e "$environment_file" --reporters cli,htmlextra,json-summary --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html" --reporter-summary-json-export "postman_summaries/${collection_name}-summary.json"
           else
-          echo "The file Environment-Collection.json was not found in the same directory as $collection_file"
-          exit 1
+            echo "The file Environment-Collection.json was not found in the same directory as $collection_file"
+            exit 1
         fi
 
     - name: Upload HTML Reports
@@ -369,7 +369,7 @@ jobs:
       if: always()
       run: |
         for summary_file in ./postman_summaries/*.json; do
-            test_execution_id=${{ needs.associate-test-cases.outputs.test_exec }}
+            test_execution_id=${{ needs.associate-test-cases.outputs.test_execution_id }}
             test_plan_id=${{ needs.associate-test-cases.outputs.test_plan_id }}
             filename=$(basename "$summary_file")
             collection_name="${filename%-summary.json}"
@@ -464,7 +464,7 @@ jobs:
               }
             }'
 
-            test_execution_id=${{ needs.associate-test-cases.outputs.test_exec }}
+            test_execution_id=${{ needs.associate-test-cases.outputs.test_execution_id }}
             for transition_id_exec in "${transition_ids_test_exec[@]}"; do
               echo "Performing Jira transition with transition ID: $transition_ids_test_exec"
               curl --request POST \
