some fix

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -70,7 +70,7 @@ jobs:
 
   associate-test-cases:
     runs-on: ubuntu-22.04
-    if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
+    # if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
     outputs:
       test_execution_id: ${{ steps.get-test-ids.outputs.test_execution_id }}
       test_plan_id: ${{ steps.get-test-ids.outputs.test_plan_id }}
@@ -91,8 +91,8 @@ jobs:
           test_plan_id=$(echo '${{ inputs.xray_keys_and_ids }}' | jq -r '.test_plan_id_'${{ inputs.os }})
           echo "The Test Execution ID : $test_execution_id"
           echo "The Test Plan ID : $test_plan_id"
-          echo "test_plan_id=$test_plan_id" >> $GITHUB_OUTPUT
-          echo "test_execution_id=$test_execution_id" >> $GITHUB_OUTPUT
+          echo "test_plan_id=122082" >> $GITHUB_OUTPUT
+          echo "test_execution_id=171300" >> $GITHUB_OUTPUT
         shell: bash
 
       - name: Generate Xray Token
@@ -560,79 +560,84 @@ jobs:
           done
 
       - name: Change test execution status
-        if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
+        # if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
         run: |
-          for summary_file in newman-json-test-reports/*.json; do
-              test_execution_id=${{ needs.associate-test-cases.outputs.test_execution_id }}
-              test_plan_id=${{ needs.associate-test-cases.outputs.test_plan_id }}
-              issue_ids=${{ needs.associate-test-cases.outputs.issue_list_ids }}
-              echo "issue_ids content: $issue_ids"
+            for summary_file in newman-json-test-reports/*.json; do
+                test_execution_id=${{ needs.associate-test-cases.outputs.test_execution_id }}
+                test_plan_id=${{ needs.associate-test-cases.outputs.test_plan_id }}
+                issue_ids=${{ needs.associate-test-cases.outputs.issue_list_ids }}
+                echo "issue_ids content: $issue_ids"
 
-              filename=$(basename "$summary_file")
-              collection_name="${filename%-summary.json}"
-              collection_name="${collection_name//-/_}"
-              echo "Contenu de collection_name : $collection_name"
+                filename=$(basename "$summary_file")
+                collection_name="${filename%-summary.json}"
+                collection_name="${collection_name//-/_}"
+                echo "Contenu de collection_name : $collection_name"
 
-              failed_requests=$(jq -r '.Run.Stats.Requests.failed' "$summary_file")
-              failed_assertions=$(jq -r '.Run.Stats.Assertions.failed' "$summary_file")
-              failures=$(jq -r '.Run.Failures' "$summary_file")
+                failed_requests=$(jq -r '.Run.Stats.Requests.failed' "$summary_file")
+                failed_assertions=$(jq -r '.Run.Stats.Assertions.failed' "$summary_file")
+                failures=$(jq -r '.Run.Failures' "$summary_file")
 
-              summaries=()
-              for issue_id in "${issue_ids[@]}"; do
-                echo "Processing issue ID: $issue_id"
-                jira_issue_url="https://centreon.atlassian.net/rest/api/2/issue/$issue_id"
+                summaries=()
+                for issue_id in "${issue_ids[@]}"; do
+                    echo "Processing issue ID: $issue_id"
+                    jira_issue_url="https://centreon.atlassian.net/rest/api/2/issue/$issue_id"
 
-                response=$(curl --request GET --url "$jira_issue_url" --user "${{ secrets.jira_user }}:${{ secrets.jira_token_test }}" --header 'Accept: application/json')
+                    response=$(curl --request GET --url "$jira_issue_url" --user "${{ secrets.jira_user }}:${{ secrets.jira_token_test }}" --header 'Accept: application/json')
+                    response_code=$(echo "$response" | jq -r '.statusCode')
 
-                if [ "$response_code" -eq 404 ]; then
-                echo "The issue with ID $issue_id does not exist or you do not have permission to see it."
-                else
-                  echo "The issue with ID $issue_id exists."
-                  summary=$(echo "$response" | jq -r '.fields.summary')
-                  echo "Summary: $summary"
-                  echo "Collection Name: $collection_name"
-                  if [ "$summary" == "$collection_name" ]; then
-                    echo "Matching issue ID: $issue_id with Collection Name: $collection_name"
-                    if [ "$failed_requests" -gt 0 ] || [ "$failed_assertions" -gt 0 ]; then
-                      newStatus="FAILED"
+                    if [ "$response_code" -eq 404 ]; then
+                        echo "The issue with ID $issue_id does not exist or you do not have permission to see it."
                     else
-                      newStatus="PASSED"
+                        echo "The issue with ID $issue_id exists."
+                        summary=$(echo "$response" | jq -r '.fields.summary')
+                        echo "Summary: $summary"
+                        echo "Collection Name: $collection_name"
+                        if [ "$summary" == "$collection_name" ]; then
+                            echo "Matching issue ID: $issue_id with Collection Name: $collection_name"
+                            if [ "$failed_requests" -gt 0 ] || [ "$failed_assertions" -gt 0 ]; then
+                                newStatus="FAILED"
+                            else
+                                newStatus="PASSED"
+                            fi
+                            xray_graphql_getTestRunIDs='{
+                              "query": "query GetTestRuns($testIssueIds: [String], $testExecIssueIds: [String], $limit: Int!) { getTestRuns(testIssueIds: $testIssueIds, testExecIssueIds: $testExecIssueIds, limit: $limit) { total limit start results { id status { name color description } gherkin examples { id status { name color description } } test { issueId } testExecution { issueId } } } }",
+                              "variables": {
+                                "testIssueIds": ["'"$issue_id"'"],
+                                "testExecIssueIds": ["'"$test_execution_id"'"],
+                                "limit": 100
+                              }
+                            }'
+                            echo "$xray_graphql_getTestRunIDs"
+                            response_getTestRun=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$xray_graphql_getTestRunIDs" -v "https://xray.cloud.getxray.app/api/v2/graphql")
+                            echo "$response_getTestRun"
+
+                            if echo "$response_getTestRun" | jq -e '.error' > /dev/null; then
+                                echo "Error in response: $(echo "$response_getTestRun" | jq -r '.error.text')"
+                                echo "Retrying after a delay..."
+                                sleep 30
+                                continue
+                            fi
+
+                            test_run_id=$(echo "$response_getTestRun" | jq -r ".data.getTestRuns.results[] | select(.test.issueId == \"$issue_id\") | .id")
+
+                            if [ -n "$test_run_id" ]; then
+                                echo "Found Test Run ID $test_run_id for Issue ID $issue_id and Collection Name $collection_name"
+
+                                graphqlMutation="{\"query\": \"mutation { updateTestRunStatus(id: \\\"$test_run_id\\\", status: \\\"$newStatus\\\") }\"}"
+                                echo "$graphqlMutation"
+                                curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$graphqlMutation" -v "https://xray.cloud.getxray.app/api/v2/graphql"
+
+                                sleep 2
+                            else
+                                echo "Test Run ID not found for Issue ID $issue_id and Collection Name $collection_name."
+                            fi
+                        fi
                     fi
-                    xray_graphql_getTestRunIDs='{
-                      "query": "query GetTestRuns($testIssueIds: [String], $testExecIssueIds: [String], $limit: Int!) { getTestRuns(testIssueIds: $testIssueIds, testExecIssueIds: $testExecIssueIds, limit: $limit) { total limit start results { id status { name color description } gherkin examples { id status { name color description } } test { issueId } testExecution { issueId } } } }",
-                      "variables": {
-                        "testIssueIds": ["'"$issue_id"'"],
-                        "testExecIssueIds": ["'"$test_execution_id"'"],
-                        "limit": 100
-                      }
-                    }'
-                    echo "$xray_graphql_getTestRunIDs"
-                    response_getTestRun=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$xray_graphql_getTestRunIDs" -v "https://xray.cloud.getxray.app/api/v2/graphql")
-                    echo "$response_getTestRun"
-
-                    # Analyze the JSON response to extract the test run ID corresponding to the issue ID
-                    test_run_id=$(echo "$response_getTestRun" | jq -r ".data.getTestRuns.results[] | select(.test.issueId == \"$issue_id\") | .id")
-
-                    # Check if a corresponding testRunId was found
-                    if [ -n "$test_run_id" ]; then
-                      echo "Found Test Run ID $test_run_id for Issue ID $issue_id and Collection Name $collection_name"
-
-                      # Use the test_run_id to execute the mutation
-                      graphqlMutation="{\"query\": \"mutation { updateTestRunStatus(id: \\\"$test_run_id\\\", status: \\\"$newStatus\\\") }\"}"
-                      echo "$graphqlMutation"
-                      curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$graphqlMutation" -v "https://xray.cloud.getxray.app/api/v2/graphql"
-
-                      # You can add checks to handle the response as needed.
-                    else
-                      echo "Test Run ID not found for Issue ID $issue_id and Collection Name $collection_name."
-                    fi
-                  fi
-                fi
-              done
+                done
             done
 
       - name: Perform Jira Transitions
-        if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
+        # if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
         run: |
           issue_ids=${{ needs.associate-test-cases.outputs.issue_list_ids }}
           transition_ids=("61" "81" "21" "31")
