some fix

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -562,6 +562,28 @@ jobs:
       - name: Change test execution status
         # if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
         run: |
+            retry_command() {
+              local max_attempts=$1
+              local command=$2
+              local attempt=0
+              local exit_code=0
+              local wait_time=1
+
+              until [ $attempt -ge $max_attempts ]; do
+                attempt=$(( attempt + 1 ))
+                eval "$command"
+                exit_code=$?
+                if [ $exit_code -eq 0 ]; then
+                  break
+                fi
+                echo "Attempt $attempt/$max_attempts failed. Retrying in $wait_time seconds..."
+                sleep $wait_time
+                wait_time=$(( wait_time * 2 ))
+              done
+
+              return $exit_code
+            }
+
             for summary_file in newman-json-test-reports/*.json; do
                 test_execution_id=${{ needs.associate-test-cases.outputs.test_execution_id }}
                 test_plan_id=${{ needs.associate-test-cases.outputs.test_plan_id }}
@@ -582,14 +604,15 @@ jobs:
                     echo "Processing issue ID: $issue_id"
                     jira_issue_url="https://centreon.atlassian.net/rest/api/2/issue/$issue_id"
 
-                    response=$(curl --request GET --url "$jira_issue_url" --user "${{ secrets.jira_user }}:${{ secrets.jira_token_test }}" --header 'Accept: application/json')
-                    response_code=$(echo "$response" | jq -r '.statusCode')
+                    command="curl --request GET --url '$jira_issue_url' --user '${{ secrets.jira_user }}:${{ secrets.jira_token_test }}' --header 'Accept: application/json' -o response.json"
+                    retry_command 5 "$command"
+                    response_code=$(jq -r '.statusCode' response.json)
 
                     if [ "$response_code" -eq 404 ]; then
                         echo "The issue with ID $issue_id does not exist or you do not have permission to see it."
                     else
                         echo "The issue with ID $issue_id exists."
-                        summary=$(echo "$response" | jq -r '.fields.summary')
+                        summary=$(jq -r '.fields.summary' response.json)
                         echo "Summary: $summary"
                         echo "Collection Name: $collection_name"
                         if [ "$summary" == "$collection_name" ]; then
@@ -599,6 +622,7 @@ jobs:
                             else
                                 newStatus="PASSED"
                             fi
+
                             xray_graphql_getTestRunIDs='{
                               "query": "query GetTestRuns($testIssueIds: [String], $testExecIssueIds: [String], $limit: Int!) { getTestRuns(testIssueIds: $testIssueIds, testExecIssueIds: $testExecIssueIds, limit: $limit) { total limit start results { id status { name color description } gherkin examples { id status { name color description } } test { issueId } testExecution { issueId } } } }",
                               "variables": {
@@ -608,13 +632,23 @@ jobs:
                               }
                             }'
                             echo "$xray_graphql_getTestRunIDs"
-                            response_getTestRun=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$xray_graphql_getTestRunIDs" -v "https://xray.cloud.getxray.app/api/v2/graphql")
-                            echo "$response_getTestRun"
+                            retry_attempts=0
+                            max_attempts=5
+                            while [ $retry_attempts -lt $max_attempts ]; do
+                                response_getTestRun=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$xray_graphql_getTestRunIDs" -v "https://xray.cloud.getxray.app/api/v2/graphql")
+                                echo "$response_getTestRun"
 
-                            if echo "$response_getTestRun" | jq -e '.error' > /dev/null; then
-                                echo "Error in response: $(echo "$response_getTestRun" | jq -r '.error.text')"
-                                echo "Retrying after a delay..."
-                                sleep 30
+                                if echo "$response_getTestRun" | jq -e '.error' > /dev/null; then
+                                    echo "Error in response: $(echo "$response_getTestRun" | jq -r '.error.text')"
+                                    echo "Retrying after a delay..."
+                                    retry_attempts=$((retry_attempts + 1))
+                                else
+                                    break
+                                fi
+                            done
+
+                            if [ $retry_attempts -ge $max_attempts ]; then
+                                echo "Failed after $max_attempts attempts"
                                 continue
                             fi
 
@@ -625,9 +659,8 @@ jobs:
 
                                 graphqlMutation="{\"query\": \"mutation { updateTestRunStatus(id: \\\"$test_run_id\\\", status: \\\"$newStatus\\\") }\"}"
                                 echo "$graphqlMutation"
-                                curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}" --data "$graphqlMutation" -v "https://xray.cloud.getxray.app/api/v2/graphql"
-
-                                sleep 2
+                                command="curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{ steps.generate-xray-token.outputs.xray_token}}' --data '$graphqlMutation' -v 'https://xray.cloud.getxray.app/api/v2/graphql'"
+                                retry_command 5 "$command"
                             else
                                 echo "Test Run ID not found for Issue ID $issue_id and Collection Name $collection_name."
                             fi
@@ -637,7 +670,7 @@ jobs:
             done
 
       - name: Perform Jira Transitions
-        # if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
+        if: ${{ inputs.os == 'alma9' && contains(fromJson('["testing", "unstable"]'), inputs.stability) && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_nightly == 'true')) }}
         run: |
           issue_ids=${{ needs.associate-test-cases.outputs.issue_list_ids }}
           transition_ids=("61" "81" "21" "31")
