adding debuggers

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -108,12 +108,15 @@ jobs:
         collection_name=$(basename "$collection_file" .postman_collection.json)
         collection_directory="$(dirname "$collection_file")"
         environment_file=$(find "$collection_directory" -maxdepth 1 -type f -name "*.postman_environment.json")
-          if [ -f "$environment_file" ]; then
-           echo "Commande newman : pnpm newman run \"$collection_file\" -e \"$environment_file\" --reporters cli,junitxray,json-summary --reporter-junitxray-export \"newman/${collection_name}.xml\" --reporter-summary-json-export \"postman_summaries/${collection_name}-summary.json\""
-          else
-            echo "The file Environment-Collection.json was not found in the same directory as $collection_file"
-            exit 1
-          fi
+        if [ -f "$environment_file" ]; then
+          echo "Generating reports for: $collection_name"
+          echo "Collection: $collection_file"
+          echo "Environment: $environment_file"
+          pnpm newman run "$collection_file" -e "$environment_file" --reporters cli,junitxray,json-summary --reporter-junitxray-export "newman/${collection_name}.xml" --reporter-summary-json-export "postman_summaries/${collection_name}-summary.json"
+        else
+          echo "The file Environment-Collection.json was not found in the same directory as $collection_file"
+          exit 1
+        fi
 
     - name: Import results to Xray
       uses: mikepenz/xray-action@v3.0.2
