Change the sleep step

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -22,32 +22,37 @@ jobs:
       - name: Login to registry
         uses: docker/login-action@v2
         with:
-          registry: ${{ secrets.DOCKER_INTERNAL_REGISTRY_URL }}
+          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
           username: ${{ secrets.DOCKER_REGISTRY_ID }}
           password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
 
-      - name: Start Centreon Web Container
+      - name : start centreon web container
         run: docker run --name centreon -d -p 4000:80 docker.centreon.com/centreon/centreon-web-alma9:develop
 
       - name: Wait for Centreon Web Container to Start
+        env:
+          MAX_RETRIES: 30
+          RETRY_INTERVAL: 10
+          CHECK_URL: http://localhost:4000/centreon/login
         run: |
-          max_retries=30 
-          retry_interval=10
+            for ((i=1; i<=$MAX_RETRIES; i++)); do
+              HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$CHECK_URL")
+              if [ $HTTP_STATUS -eq 200 ]; then
+                echo "Centreon web application is ready!"
+                break
+              elif [ $HTTP_STATUS -eq 404 ]; then
+                echo "Centreon web application is not found (404)."
+                exit 1
+              else
+                echo "Retrying in $RETRY_INTERVAL seconds..."
+                sleep $RETRY_INTERVAL
+              fi
+           done
 
-          for ((i=1; i<=$max_retries; i++)); do
-            http_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4000/centreon/login)
-            if [ $http_status -eq 200 ]; then
-              echo "Centreon web application is ready!"
-              break
-            fi
-            echo "Retrying in $retry_interval seconds..."
-            sleep $retry_interval
-          done
-
-          if [ $http_status -ne 200 ]; then
-            echo "Centreon web application did not start successfully."
-            exit 1
-          fi
+           if [ $HTTP_STATUS -ne 200 ]; then
+             echo "Centreon web application did not start successfully."
+             exit 1
+           fi
 
       - name: Run Postman Tests and Generate HTML Report
         run: |
