add some changements

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -57,8 +57,8 @@ jobs:
   associate-test-cases:
       runs-on: ubuntu-22.04
       outputs:
-        test_exec: ${{ steps.xray-newman.outputs.test_exec }}
-        test_plan_id: ${{ steps.get-testPlan-id.outputs.testPlan_id }}
+        test_exec_id: ${{ steps.xray-newman.outputs.test_exec_id }}
+        test_plan_id: ${{ steps.get-test-plan-id.outputs.test_plan_id }}
 
       defaults:
        run:
@@ -109,11 +109,11 @@ jobs:
             echo "testPlanKey=$testPlanKey" >> $GITHUB_OUTPUT
 
         - name: Get TestPlan ID
-          id: get-testPlan-id
+          id: get-test-plan-id
           run: |
               jira_url="https://centreon.atlassian.net/rest/api/2/issue/${{ steps.determine-testplan-key.outputs.testPlanKey }}"
               testPlan_id=$(curl -u "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_TOKEN_TEST }}" -X GET -s "$jira_url" | jq -r '.id')
-              echo "this is the testPlan ID : $testPlan_id"
+              echo "this is the testPlan ID : $test_plan_id"
               echo "testPlan_id=$testPlan_id" >> $GITHUB_OUTPUT
 
         - name: Associate Test Cases with Test plan
@@ -122,7 +122,7 @@ jobs:
             xray_graphql_getTestPlan='{
               "query": "query GetTestPlan($issueId: String) { getTestPlan(issueId: $issueId) { issueId tests(limit: 100) { results { issueId testType { name } } } } }",
               "variables": {
-                "issueId": "${{ steps.get-testPlan-id.outputs.testPlan_id }}"
+                "issueId": "${{ steps.get-test-plan-id.outputs.testPlan_id }}"
               }
             }'
 
@@ -147,7 +147,7 @@ jobs:
               summary=$(echo "$response" | jq -r '.fields.summary')
 
               if [ "$response_code" -eq 404 ]; then
-               echo "The issue with ID $issue_id does not exist or you do not have permission to see it."
+                echo "The issue with ID $issue_id does not exist or you do not have permission to see it."
                 break
               else
                 echo "The issue with ID $issue_id exists."
@@ -161,7 +161,7 @@ jobs:
             xray_graphql_AddingTestsToTestPlan='{
               "query": "mutation AddTestsToTestPlan($issueId: String!, $testIssueIds: [String]!) { addTestsToTestPlan(issueId: $issueId, testIssueIds: $testIssueIds) { addedTests warning } }",
               "variables": {
-                "issueId": "${{ steps.get-testPlan-id.outputs.testPlan_id }}",
+                "issueId": "${{ steps.get-test-plan-id.outputs.testPlan_id }}",
                 "testIssueIds": []
               }
             }'
@@ -259,7 +259,7 @@ jobs:
             xray_graphql_addTestExecutionsToTestPlan='{
               "query": "mutation AddTestExecutionsToTestPlan($issueId: String!, $testExecIssueIds: [String]!) { addTestExecutionsToTestPlan(issueId: $issueId, testExecIssueIds: $testExecIssueIds) { addedTestExecutions warning } }",
               "variables": {
-                "issueId": "${{ steps.get-testPlan-id.outputs.testPlan_id }}",
+                "issueId": "${{steps.get-test-plan-id.outputs.testPlan_id }}",
                 "testExecIssueIds": ["'$test_execution_id'"]
               }
             }'
@@ -336,11 +336,11 @@ jobs:
         collection_directory="$(dirname "$collection_file")"
         environment_file=$(find "$collection_directory" -maxdepth 1 -type f -name "*.postman_environment.json")
         if [ -f "$environment_file" ]; then
-          echo "Environment: $environment_file"
+           echo "Environment: $environment_file"
            pnpm newman run "$collection_file" -e "$environment_file" --reporters cli,htmlextra,json-summary --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html" --reporter-summary-json-export "postman_summaries/${collection_name}-summary.json"
           else
-          echo "The file Environment-Collection.json was not found in the same directory as $collection_file"
-          exit 1
+           echo "The file Environment-Collection.json was not found in the same directory as $collection_file"
+           exit 1
         fi
 
     - name: Upload HTML Reports
@@ -369,7 +369,7 @@ jobs:
       if: always()
       run: |
         for summary_file in ./postman_summaries/*.json; do
-            test_execution_id=${{ needs.associate-test-cases.outputs.test_exec }}
+            test_execution_id=${{ needs.associate-test-cases.outputs.test_exec_id }}
             test_plan_id=${{ needs.associate-test-cases.outputs.test_plan_id }}
             filename=$(basename "$summary_file")
             collection_name="${filename%-summary.json}"
@@ -464,7 +464,7 @@ jobs:
               }
             }'
 
-            test_execution_id=${{ needs.associate-test-cases.outputs.test_exec }}
+            test_execution_id=${{ needs.associate-test-cases.outputs.test_exec_id }}
             for transition_id_exec in "${transition_ids_test_exec[@]}"; do
               echo "Performing Jira transition with transition ID: $transition_ids_test_exec"
               curl --request POST \
