Adding some rectifications

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -120,11 +120,10 @@ jobs:
         
     - name: Extract and Store Summaries
       run: |
-        declare -A json_info
         for summary_file in ./postman_summaries/*.json; do
           echo "Summary file: $summary_file"
-          cat "$summary_file"
-          summary_content=$(cat "$summary_file" | jq -c '{Name: .Collection.Info.Name, Stats: .Run.Stats}')
+          cat "$summary_file" 
+          summary_content=$(jq -c '{Name: .Collection.Info.Name, Stats: .Run.Stats, Failures: .Run.Failures}' "$summary_file")
           filename=$(basename "$summary_file" .json)
           clean_filename="${filename// /_}"
           clean_filename="${clean_filename//-/_}"
@@ -145,12 +144,23 @@ jobs:
             pending_requests=$(jq -r '.Run.Stats.Requests.pending' "$summary_file")
             failed_requests=$(jq -r '.Run.Stats.Requests.failed' "$summary_file")
             failed_assertions=$(jq -r '.Run.Stats.Assertions.failed' "$summary_file")
-    
+            
+            summary_content=$(cat "$summary_file" | jq -c '{Name: .Collection.Info.Name, Stats: .Run.Stats, Failures: .Run.Failures}')
+            
             if [ "$failed_requests" -gt 0 ] || [ "$failed_assertions" -gt 0 ]; then
                 has_failures=true  # Set has_failures to true if there are failures
                 summaries+="<table>"
                 summaries+="<tr><th>Collection Name</th><th>Total Requests</th><th>⏭️ Skipped requests</th><th>❌ Failed Requests</th><th>❌ Failed Assertions</th></tr>"
                 summaries+="<tr><td>$collection_name</td><td>$total_requests</td><td>$pending_requests</td><td>$failed_requests</td><td>$failed_assertions</td></tr>"
+                summaries+="<tr><td colspan='5'><strong>Failed Iterations:</strong></td></tr>"
+                
+                # Extract and add information about failed iterations
+                for failure in $(jq -c '.Failures[]' <<< "$summary_content"); do
+                    failure_message=$(jq -r '.Error.Message' <<< "$failure")
+                    test_name=$(jq -r '.Test' <<< "$failure")
+                    summaries+="<tr><td colspan='5'>$test_name: $failure_message</td></tr>"
+                done
+                
                 summaries+="</table>"
             fi
             echo "Processing summary file: $summary_file"
@@ -161,5 +171,5 @@ jobs:
         fi
         
         if [ "$has_failures" = true ]; then
-           exit 1
+          exit 1
         fi
