Adding some rectifications

diff --git a/.github/workflows/newman.yml b/.github/workflows/newman.yml
--- a/.github/workflows/newman.yml
+++ b/.github/workflows/newman.yml
@@ -95,7 +95,7 @@ jobs:
         collection_directory="$(dirname "$collection_file")"
         environment_file="$collection_directory/Environment-Collection.json"
         if [ -f "$environment_file" ]; then
-          pnpm newman run "$collection_file" -e "$environment_file" --reporters cli,htmlextra,json-summary --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html" --reporter-summary-json-export "postman_summaries/${collection_name}-summary.json" --bail
+          pnpm newman run "$collection_file" -e "$environment_file" --reporters cli,htmlextra,json-summary --reporter-htmlextra-title "$collection_name" --reporter-htmlextra-title "${collection_name// /_}" --reporter-htmlextra-export "newman/${collection_name}.html" --reporter-summary-json-export "postman_summaries/${collection_name}-summary.json" || true
         else
           echo "The file Environment-Collection.json was not found in the same directory as $collection_file"
           exit 1
@@ -145,4 +145,7 @@ jobs:
         if [ -n "$summaries" ]; then
           echo -e "$summaries" >> $GITHUB_STEP_SUMMARY
         fi
-        
+
+    - name: Continue to Next Step
+      if: failure()
+      run: echo "This step will only run if the previous step failed."
