some fix

diff --git a/.github/workflows/performance-testing.yml b/.github/workflows/performance-testing.yml
--- a/.github/workflows/performance-testing.yml
+++ b/.github/workflows/performance-testing.yml
@@ -119,14 +119,21 @@ jobs:
       - name: Install JMeter
         run: |
           java -version
-          wget -q https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.zip
-          unzip -q apache-jmeter-5.4.1.zip
-          rm apache-jmeter-5.4.1.zip  # Nettoyage pour éviter d'occuper trop d'espace
+          echo "Downloading JMeter..."
+          wget -q https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.4.1.zip -O jmeter.zip || { echo "Download failed!"; exit 1; }
+
+          echo "Checking if the file exists..."
+          ls -lah jmeter.zip || { echo "File not found!"; exit 1; }
+
+          echo "Unzipping JMeter..."
+          unzip -q jmeter.zip || { echo "Unzip failed!"; exit 1; }
+
+          rm jmeter.zip
           echo "JMeter installed successfully!"
 
       - name: Install JMeter Plugins
         run: |
-          cd $GITHUB_WORKSPACE/apache-jmeter-5.4.1
+          cd $GITHUB_WORKSPACE/centreon/tests/performanceTesting/apache-jmeter-5.4.1
           wget -q --no-check-certificate https://jmeter-plugins.org/files/packages/jpgc-dummy-0.4.zip
           unzip -o jpgc-dummy-0.4.zip
           rm jpgc-dummy-0.4.zip  # Nettoyage après installation
@@ -135,7 +142,7 @@ jobs:
       - name: Run JMX Scripts
         run: |
           cd $GITHUB_WORKSPACE/apache-jmeter-5.4.1/bin
-          mkdir -p $GITHUB_WORKSPACE/jmeter_results  # Créer le dossier de résultats
+          mkdir -p $GITHUB_WORKSPACE/centreon/tests/performanceTesting/jmeter_results  # Créer le dossier de résultats
           for i in $GITHUB_WORKSPACE/*.jmx; do
               echo "Running test: $i"
               ./jmeter -n -t "$i" -l $GITHUB_WORKSPACE/jmeter_results/results_$(basename "$i" .jmx).jtl
