enh(release): enhance release trigger builds with selective triggers and commit list

diff --git a/.github/workflows/release-trigger-builds.yml b/.github/workflows/release-trigger-builds.yml
--- a/.github/workflows/release-trigger-builds.yml
+++ b/.github/workflows/release-trigger-builds.yml
@@ -5,15 +5,16 @@ on:
   workflow_dispatch:
     inputs:
       dispatch_target_release_branch:
-        description: "Cloud release branch to trigger"
+        description: "Release or hotfix branch to trigger"
         required: true
       dispatch_content:
-        description: "Regular (only centreon named components) or Full (every component, including docker builders, php and extra libs)"
+        description: "Dispatch content (what workflow is going to be triggered)"
         required: true
         type: choice
         options:
-          - REGULAR
-          - FULL
+          - REGULAR # Centreon components only without libs
+          - CHANGED_ONLY # Anything that received a change
+          - FULL # Centreon components + libs
 
 jobs:
   release-trigger-builds:
@@ -21,6 +22,8 @@ jobs:
     runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+        with:
+          fetch-depth: 0
 
       - name: Install Github CLI
         run: |
@@ -39,44 +42,276 @@ jobs:
           fi
         shell: bash
 
-      - name: Trigger selected branches
+      - name: Get and set references information
+        id: get_and_set_references_information
+        run: |
+          set -eux
+          # VARS
+          OWNER="centreon"
+          REPO="centreon"
+          NEW_BRANCH="${{ inputs.dispatch_target_release_branch }}" #Possible valid values release-29.10-next or hotfix-29.10-next
+          NEW_BRANCH_SHA="" # sha of the head of NEW_BRANCH
+          BASE_REF=""
+          BASE_REF_SHA=""
+          RELEASE_BRANCH_MAJOR_VERSION=""
+          RELEASE_SCOPE=""
+          RELEASE_TYPE=""
+          PREVIOUS_STABLE_BUNDLE_TAG="" # bundle tag
+          PREVIOUS_STABLE_BUNDLE_TAG_COMMIT_SHA="" # sha of the commit pointed by PREVIOUS_STABLE_BUNDLE_TAG
+          # Extract RELEASE_BRANCH_MAJOR_VERSION
+          RELEASE_BRANCH_MAJOR_VERSION="$(echo ${{ inputs.dispatch_target_release_branch }} | cut -d "-" -f2)"
+          echo "Major version detected: $RELEASE_BRANCH_MAJOR_VERSION"
+          # Deduce RELEASE_SCOPE from RELEASE_BRANCH_MAJOR_VERSION
+          if [[ "$RELEASE_BRANCH_MAJOR_VERSION" =~ ^[0-9]{2}\.(04|10)$ ]]; then
+            RELEASE_SCOPE="onprem"
+            echo "Release scope detected: onprem"
+          elif [[ ! "$RELEASE_BRANCH_MAJOR_VERSION" =~ ^[0-9]{2}\.(04|10)$ ]]; then
+            RELEASE_SCOPE="cloud"
+            echo "Release scope detected: cloud"
+          else
+            echo "Invalid release branch major version: $RELEASE_BRANCH_MAJOR_VERSION. Either RELEASE_BRANCH is invalid or version in it is invalid."
+            exit 1
+          fi
+          # Set RELEASE_TYPE based on dispatch_target_release_branch prefix (release or hotfix)
+          RELEASE_TYPE="$(echo ${{ inputs.dispatch_target_release_branch }} | cut -d "-" -f1)"
+          echo "Release type detected: $RELEASE_TYPE"
+          # Get previous stable release bundle tags
+          # Previous release bundle tag
+          if [[ "$RELEASE_SCOPE" == "cloud" ]]; then
+            PREVIOUS_STABLE_BUNDLE_TAG=$(git tag -l --sort=-version:refname "release-cloud-*-${RELEASE_BRANCH_MAJOR_VERSION}" | head -n 1)
+          elif [[ "$RELEASE_SCOPE" == "onprem" ]]; then
+            PREVIOUS_STABLE_BUNDLE_TAG=$(git tag -l --sort=-version:refname "release-onprem-*-${RELEASE_BRANCH_MAJOR_VERSION}" | head -n 1)
+          else
+            echo "Invalid release_scope: $RELEASE_SCOPE"
+          fi
+          # Check if a tag was found
+          if [ -z "$PREVIOUS_STABLE_BUNDLE_TAG" ]; then
+            echo "Previous stable bundle tag not found: $PREVIOUS_STABLE_BUNDLE_TAG, exiting."
+            exit 1
+          else
+            echo "Previous stable bundle tag found: $PREVIOUS_STABLE_BUNDLE_TAG"
+          fi
+          # Setting BASE_REF based on RELEASE_BRANCH_MAJOR_VERSION in dispatch_target_release_branch
+          # BASE_REF is the ref to create the NEW_BRANCH from
+          # if RELEASE_TYPE is release AND RELEASE_SCOPE is cloud => create from develop + use version XX.YY of dispatch_target_release_branch
+          if [[ "$RELEASE_TYPE" == "release" && "$RELEASE_SCOPE" == "cloud" ]]; then
+            echo "Release type detected: $RELEASE_TYPE with release scope: $RELEASE_SCOPE"
+            BASE_REF="develop"
+          # if RELEASE_TYPE is release => create from dev-XX.YY.x + use version XX.YY of dispatch_target_release_branch
+          elif [[ "$RELEASE_TYPE" == "release" ]]; then
+            echo "Release type detected: $RELEASE_TYPE with release scope: $RELEASE_SCOPE"
+            BASE_REF="dev-$RELEASE_BRANCH_MAJOR_VERSION.x"
+          # if RELEASE_TYPE is hotfix => create from latest stable bundle tag + use version XX.YY of dispatch_target_release_branch
+          # bundle tag format is "release-<scope>-YYYYMMNN-XX.YY" with
+          # YYYY is a year (ex: 2029)
+          # MM is a month (ex: 01)
+          # XX.YY is a major version (ex: 29.10)
+          elif [[ "$RELEASE_TYPE" == "hotfix" ]]; then
+            echo "Release type detected: $RELEASE_TYPE with release scope: $RELEASE_SCOPE"
+            BASE_REF="$PREVIOUS_STABLE_BUNDLE_TAG"
+          else
+            echo "Either $RELEASE_TYPE or $RELEASE_SCOPE or $RELEASE_BRANCH_MAJOR_VERSION were not valid combination."
+            exit 1
+          fi
+          # Check if NEW_BRANCH already exists and exit with error if it does
+          echo "Checking if branch $NEW_BRANCH already exists..."
+          GH_API_RESPONSE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
+            -H "Authorization: Bearer $GH_TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/centreon/centreon/git/ref/heads/$NEW_BRANCH")
+          if [[ "$GH_API_RESPONSE_STATUS" == "200" ]]; then
+            echo "Branch '$NEW_BRANCH' already exists. Exiting."
+            exit 1
+          elif [[ "$GH_API_RESPONSE_STATUS" == "404" ]]; then
+            echo "Branch '$NEW_BRANCH' does not exist. Branch '$NEW_BRANCH' will be created."
+          else
+            echo "Unexpected GitHub API response status: $GH_API_RESPONSE_STATUS"
+            exit 1
+          fi
+          #
+          # Resolve BASE_REF_SHA pointed by $BASE_REF
+          # If RELEASE_TYPE is release, this means BASE_REF is a dev branch => use "ref/heads/$BASE_REF"
+          # If RELEASE_TYPE is hotfix, this means BASE_REF is a tag => use "ref/tags/$BASE_REF"
+          GITHUB_API_REF_TYPE=""
+          if [[ "$RELEASE_TYPE" == "release" ]]; then
+            GITHUB_API_REF_TYPE="heads"
+          else
+            GITHUB_API_REF_TYPE="tags"
+          fi
+          echo "Resolving BASE_REF_SHA for $BASE_REF..."
+          BASE_REF_SHA=$(curl -sS \
+            -H "Authorization: Bearer $GH_TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/centreon/centreon/git/ref/$GITHUB_API_REF_TYPE/$BASE_REF" \
+            | jq -r '.object.sha')
+          if [[ -z "$BASE_REF_SHA" || "$BASE_REF_SHA" == "null" ]]; then
+            echo "BASE_REF_SHA is : $BASE_REF_SHA"
+            echo "Could not resolve BASE_REF_SHA for $BASE_REF"
+            exit 1
+          fi
+          echo "Using BASE_REF_SHA $BASE_REF_SHA from BASE_REF $BASE_REF."
+          # Get PREVIOUS_STABLE_BUNDLE_TAG_SHA data
+          PREVIOUS_STABLE_BUNDLE_TAG_DATA=$(curl -sS \
+          -H "Authorization: Bearer $GH_TOKEN" \
+          -H "Accept: application/vnd.github+json" \
+          "https://api.github.com/repos/centreon/centreon/git/ref/tags/${PREVIOUS_STABLE_BUNDLE_TAG}")
+          PREVIOUS_STABLE_BUNDLE_TAG_OBJ_SHA=$(echo "$PREVIOUS_STABLE_BUNDLE_TAG_DATA" | jq -r '.object.sha')
+          PREVIOUS_STABLE_BUNDLE_TAG_OBJ_TYPE=$(echo "$PREVIOUS_STABLE_BUNDLE_TAG_DATA" | jq -r '.object.type')
+          # Resolve tag SHA (lightweight or annotated)
+          # if annotated (release-something-version), follow tag up to commit sha
+          # if lightweight (XX.YY-latest), nothing special
+          # TYPE OF OBJECT (tag or not a tag)
+          if [ "$PREVIOUS_STABLE_BUNDLE_TAG_OBJ_TYPE" = "tag" ]; then
+            PREVIOUS_STABLE_BUNDLE_TAG_COMMIT_SHA=$(curl -sS \
+              -H "Authorization: Bearer $GH_TOKEN" \
+              "https://api.github.com/repos/centreon/centreon/git/tags/${PREVIOUS_STABLE_BUNDLE_TAG_OBJ_SHA}" \
+              | jq -r '.object.sha')
+          else
+            PREVIOUS_STABLE_BUNDLE_TAG_COMMIT_SHA="$PREVIOUS_STABLE_BUNDLE_TAG_OBJ_SHA"
+          fi
+          echo "Setting SHA for PREVIOUS_STABLE_BUNDLE_TAG_COMMIT as PREVIOUS_STABLE_BUNDLE_TAG_COMMIT_SHA: $PREVIOUS_STABLE_BUNDLE_TAG_COMMIT_SHA."
+          # Output the vars
+          # BASE_REF
+          echo "base_ref=$BASE_REF" >> $GITHUB_OUTPUT
+          # BASE_REF_SHA
+          echo "base_ref_sha=$BASE_REF_SHA" >> $GITHUB_OUTPUT
+          # PREVIOUS_STABLE_BUNDLE_TAG
+          echo "previous_stable_bundle_tag=$PREVIOUS_STABLE_BUNDLE_TAG" >> $GITHUB_OUTPUT
+          # PREVIOUS_STABLE_BUNDLE_TAG_SHA
+          echo "previous_stable_bundle_tag_sha=$PREVIOUS_STABLE_BUNDLE_TAG_COMMIT_SHA" >> $GITHUB_OUTPUT
+          # NEW_BRANCH
+          echo "new_branch=$NEW_BRANCH" >> $GITHUB_OUTPUT
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create requested release/hotfix branch
+        id: create_requested_release_hotfix_branch
+        run: |
+          set -eux
+          # Check the previous values
+          echo "${{ steps.get_and_set_references_information.outputs.base_ref }}"
+          echo "${{ steps.get_and_set_references_information.outputs.base_ref_sha }}"
+          echo "${{ steps.get_and_set_references_information.outputs.previous_stable_bundle_tag }}"
+          echo "${{ steps.get_and_set_references_information.outputs.previous_stable_bundle_tag_sha }}"
+          echo "${{ steps.get_and_set_references_information.outputs.new_branch }}"
+          # Commented until tests are made with fine grained token
+          # Create the NEW_BRANCH
+          # If RELEASE_TYPE is release, this means BASE_REF is a dev branch => use "ref/heads/$BASE_REF" (base_ref_sha) to create NEW_BRANCH
+          # If RELEASE_TYPE is hotfix, this means BASE_REF is a tag => use "ref/tags/$BASE_REF" to create NEW_BRANCH
+          # Get release type
+          RELEASE_TYPE="$(echo ${{ inputs.dispatch_target_release_branch }} | cut -d "-" -f1)"
+          if [[ "$RELEASE_TYPE" == "release" ]]; then
+            echo "Creating requested release/hotfix branch with name ${{ steps.get_and_set_references_information.outputs.new_branch }} from ${{ steps.get_and_set_references_information.outputs.base_ref }}."
+            PAYLOAD=$(jq -n --arg ref "refs/heads/${{ steps.get_and_set_references_information.outputs.new_branch }}" --arg sha "${{ steps.get_and_set_references_information.outputs.base_ref_sha }}" \
+              '{ref: $ref, sha: $sha}')
+          elif [[ "$RELEASE_TYPE" == "hotfix" ]]; then
+            echo "Creating requested release/hotfix branch with name ${{ steps.get_and_set_references_information.outputs.new_branch }} from ${{ steps.get_and_set_references_information.outputs.base_ref }}."
+            PAYLOAD=$(jq -n --arg ref "refs/heads/${{ steps.get_and_set_references_information.outputs.new_branch }}" --arg sha "${{ steps.get_and_set_references_information.outputs.previous_stable_bundle_tag_sha }}" \
+              '{ref: $ref, sha: $sha}')
+          fi
+          # DEBUG
+          echo "$PAYLOAD"
+          # Create the NEW_BRANCH using API and fine grained
+          API_RESPONSE_BODY=$(curl \
+            -w "\n%{http_code}" \
+            -H "Authorization: Bearer $GH_TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            -X POST -H "Content-Type: application/json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d "$PAYLOAD" \
+            "https://api.github.com/repos/centreon/centreon/git/refs")
+          API_HTTP_CODE=$(echo API_HTTP_CODE: "$API_RESPONSE_BODY" | tail -n1)
+          API_RESPONSE=$(echo "API_RESPONSE: $API_RESPONSE_BODY" | sed '$d')
+          echo "Create ref HTTP status: $API_HTTP_CODE"
+          echo "Create ref response: $API_RESPONSE"
+          # # Create the NEW_BRANCH using git
+          # # Branch protection does not allow usage of API for this
+          # echo "Cloning to repository."
+          # git clone git@github.com:centreon/centreon.git
+          # echo "Branch created: ${{ steps.get_and_set_references_information.outputs.new_branch }}"
+          # Resolve branch SHA
+          NEW_BRANCH_SHA=$(
+            curl -sS \
+              -H "Authorization: Bearer $GH_TOKEN" \
+              -H "Accept: application/vnd.github+json" \
+              "https://api.github.com/repos/centreon/centreon/git/ref/heads/${{ steps.get_and_set_references_information.outputs.new_branch }}" \
+              | jq -r '.object.sha'
+          )
+          # Exit if NEW_BRANC_SHA is not set at all
+          if [[ -z "$NEW_BRANCH_SHA" || "$NEW_BRANCH_SHA" == "null" ]]; then
+            echo "[ERROR] NEW_BRANCH_SHA could not be resolved and set, exiting."
+            exit 1
+          fi
+          # Always the current release or hotfix branch sha
+          echo "Setting SHA for NEW_BRANCH ${{ steps.get_and_set_references_information.outputs.new_branch }} as NEW_BRANCH_SHA: $NEW_BRANCH_SHA."
+          # Output the vars
+          # NEW_BRANCH_SHA
+          echo "new_branch_sha=$NEW_BRANCH_SHA" >> $GITHUB_OUTPUT
+        env:
+          GH_TOKEN: ${{ secrets.TEST_GH_FINE_GRAINED_TOKEN }}
+
+      # Detect changes since last stable tag (ex: 25.10-latest)
+      - name: Detect changed components since last stable release bundle tag
+        uses: ./.github/actions/release-detect-changed-components
+        with:
+          #base_ref: ${{ steps.get_and_set_references_information.outputs.previous_stable_bundle_tag }}
+          base_sha: ${{ steps.get_and_set_references_information.outputs.previous_stable_bundle_tag_sha }}
+          head_sha: ${{ steps.create_requested_release_hotfix_branch.outputs.new_branch_sha }}
+
+      - name: Trigger changed components on selected branches
         run: |
           set -eux
 
           # VARS
           # names defined in workflow files per components
-          COMPONENTS_OSS=("awie" "dsm" "ha" "open-tickets" "web")
+          # these are the default component_list values, they can be overriden further in the code
+          COMPONENTS_OSS_REGULAR=("awie" "dsm" "ha" "open-tickets" "web")
           COMPONENTS_OSS_EXTRA=("docker-keycloak" "docker-packaging" "docker-translation" "docker-web-dependencies")
           COMPONENTS_OSS_FULL=("awie" "dsm" "ha" "open-tickets" "web")
+          COMPONENTSS_OSS_CHANGED=("")
           #COMPONENTS_MODULES=("anomaly-detection" "autodiscovery" "bam" "cloud-business-extensions" "cloud-extensions" "it-edition-extensions" "lm" "map" "mbi" "ppm")
           #COMPONENTS_MODULES_FULL=("anomaly-detection" "autodiscovery" "bam" "cloud-business-extensions" "cloud-extensions" "it-edition-extensions" "lm" "map" "mbi" "ppm" "php-pecl-gnupg" "sourceguardian-loader")
           #COMPONENTS_COLLECT=("Centreon collect")
           RUNS_URL=""
 
-          # Accept release prefixed or develop branches, nothing else
-          if [[ ${{ inputs.dispatch_target_release_branch }} =~ ^release-2[0-9]\.[0-9]+-next$ ]] || [[ ${{ inputs.dispatch_target_release_branch }} == "develop" ]];then
+          # Accept the branche types listed below, nothing else
+          # release prefixed branches: standard release type (release-xxxxx)
+          # hotfix prefixed branches: hotfix release type (hotfix-xxxxx)
+          # develop: start of a new major version (not a release) (develop)
+          # Build link to list of runs for selected branch
+          if [[ ${{ inputs.dispatch_target_release_branch }} =~ ^release-2[0-9]\.[0-9]+-next$ ]] || [[ ${{ inputs.dispatch_target_release_branch }} == "develop" ]] || [[ ${{ inputs.dispatch_target_release_branch }} =~ ^hotfix-2[0-9]\.[0-9]+-next$ ]];then
             echo "Using ${{ inputs.dispatch_target_release_branch }} as branch to build testing packages."
             RUNS_URL="https://github.com/centreon/centreon/actions?query=branch%3A${{ inputs.dispatch_target_release_branch }}"
           else
-            echo "::error::Invalid release branch name, please check the release branch name."
+            echo "::error::Invalid release branch name selected ${{ inputs.dispatch_target_release_branch }}, please check the release branch name in the input."
             exit 1
           fi
 
-          if [[ "${{ inputs.dispatch_content }}" == "FULL" ]]; then
-            echo "Requested ${{ inputs.dispatch_content }} content, triggering all component workflows."
-            for COMPONENT in "${COMPONENTS_OSS_FULL[@]}"; do
-              gh workflow run $COMPONENT -r ${{ inputs.dispatch_target_release_branch }}
+          # Handle the limited cases of dispatch_content
+          echo "Requested ${{ inputs.dispatch_content }} content."
+          case ${{ inputs.dispatch_content }} in
+            "FULL")
+            echo "Triggering all components, docker builders, php and extra libs."
+              for COMPONENT in "${COMPONENTS_OSS_FULL[@]}"; do
+                echo "Dispatching trigger to $COMPONENT workflow."
+                # gh workflow run "$COMPONENT" -r ${{ inputs.dispatch_target_release_branch }}
+              done
+            ;;
+           "REGULAR")
+            echo "Triggering all components only."
+            for COMPONENT in "${COMPONENTS_OSS_REGULAR[@]}"; do
+              echo "Dispatching trigger to $COMPONENT workflow."
+              # gh workflow run "$COMPONENT" -r ${{ inputs.dispatch_target_release_branch }}
             done
-            echo "Requested ${{ inputs.dispatch_content }} content, triggering all component workflows and extra docker builders and libs."
-            for COMPONENT in "${COMPONENTS_OSS_EXTRA[@]}"; do
-              gh workflow run $COMPONENT -r ${{ inputs.dispatch_target_release_branch }}
+            ;;
+            "CHANGED_ONLY")
+            echo "Triggering components that received at least one change since last stable release bundle tag."
+            for COMPONENT in "${COMMPONENTS_OSS_CHANGED[@]}"; do
+              echo "Dispatching trigger to $COMPONENT workflow."
+              # gh workflow run "$COMPONENT" -r ${{ inputs.dispatch_target_release_branch }}
             done
-          else
-            echo "Requested ${{ inputs.dispatch_content }} content, triggering centreon named components only."
-            for COMPONENT in "${COMPONENTS_OSS[@]}"; do
-              gh workflow run $COMPONENT -r ${{ inputs.dispatch_target_release_branch }}
-            done
-          fi
+            ;;
+          esac
 
           echo "Dispatch was successfully triggered. Runs can be found at ${RUNS_URL}"
         shell: bash
