disable check base ref for release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -19,7 +19,7 @@ on:
 
 jobs:
   release:
-    if: ${{ github.event.pull_request.merged == true }}
+    #if: ${{ github.event.pull_request.merged == true }}
     runs-on: ubuntu-22.04
     steps:
       - name: Check base_ref
@@ -28,12 +28,12 @@ jobs:
 
           # Check if github.base_ref is either master or any of the supported version ones
           # This must never run on any other than master and supported version base_ref
-          if [[ "${{ github.base_ref }}" == 'master' || "${{ github.base_ref }}" =~ ^[2-9][0-9].[0-9][0-9].x ]];then
-            echo "[DEBUG] base_ref is valid: ${{ github.base_ref }}"
-          else
-            echo "::error::base_ref is not valid (${{ github.base_ref }}), exiting."
-            exit 1
-          fi
+          # if [[ "${{ github.base_ref }}" == 'master' || "${{ github.base_ref }}" =~ ^[2-9][0-9].[0-9][0-9].x ]];then
+          #   echo "[DEBUG] base_ref is valid: ${{ github.base_ref }}"
+          # else
+          #   echo "::error::base_ref is not valid (${{ github.base_ref }}), exiting."
+          #   exit 1
+          # fi
         shell: bash
 
       - name: Checkout sources
