trigger test run for release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,12 +28,12 @@ jobs:
 
           # Check if github.base_ref is either master or any of the supported version ones
           # This must never run on any other than master and supported version base_ref
-          if [[ "${{ github.base_ref }}" == 'master' || "${{ github.base_ref }}" =~ ^[2-9][0-9].[0-9][0-9].x ]];then
-            echo "[DEBUG] base_ref is valid: ${{ github.base_ref }}"
-          else
-            echo "::error::base_ref is not valid (${{ github.base_ref }}), exiting."
-            exit 1
-          fi
+          # if [[ "${{ github.base_ref }}" == 'master' || "${{ github.base_ref }}" =~ ^[2-9][0-9].[0-9][0-9].x ]];then
+          #   echo "[DEBUG] base_ref is valid: ${{ github.base_ref }}"
+          # else
+          #   echo "::error::base_ref is not valid (${{ github.base_ref }}), exiting."
+          #   exit 1
+          # fi
         shell: bash
 
       - name: Checkout sources
@@ -45,7 +45,7 @@ jobs:
         id: release
         uses: ./.github/actions/release
         with:
-          github_ref_name: ${{ github.head_ref || github.ref_name }}
+          github_ref_name: "master"
           jira_project_id: ${{ secrets.JIRA_PROJECT_ID }}
           jira_user_email: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
           jira_api_token: ${{ secrets.XRAY_JIRA_TOKEN }}
