force promote 25.03.1

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,19 +21,19 @@ jobs:
     if: ${{ github.event.pull_request.merged == true }}
     runs-on: ubuntu-24.04
     steps:
-      - name: Check base_ref
-        run: |
-          set -eu
+      # - name: Check base_ref
+      #   run: |
+      #     set -eu
 
-          # Check if github.base_ref is either master or any of the supported version ones
-          # This must never run on any other than master and supported version base_ref
-          if [[ "${{ github.base_ref }}" == 'master' || "${{ github.base_ref }}" =~ ^[2-9][0-9].[0-9][0-9].x ]];then
-            echo "[DEBUG] base_ref is valid: ${{ github.base_ref }}"
-          else
-            echo "::error::base_ref is not valid (${{ github.base_ref }}), exiting."
-            exit 1
-          fi
-        shell: bash
+      #     # Check if github.base_ref is either master or any of the supported version ones
+      #     # This must never run on any other than master and supported version base_ref
+      #     if [[ "${{ github.base_ref }}" == 'master' || "${{ github.base_ref }}" =~ ^[2-9][0-9].[0-9][0-9].x ]];then
+      #       echo "[DEBUG] base_ref is valid: ${{ github.base_ref }}"
+      #     else
+      #       echo "::error::base_ref is not valid (${{ github.base_ref }}), exiting."
+      #       exit 1
+      #     fi
+      #   shell: bash
 
       - name: Checkout sources
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -44,7 +44,7 @@ jobs:
         id: release
         uses: ./.github/actions/release
         with:
-          github_ref_name: ${{ github.base_ref }}
+          github_ref_name: master
           jira_project_id: ${{ secrets.JIRA_PROJECT_ID }}
           jira_user_email: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
           jira_api_token: ${{ secrets.XRAY_JIRA_TOKEN }}
