to revert test

diff --git a/.github/workflows/veracode-analysis.yml b/.github/workflows/veracode-analysis.yml
--- a/.github/workflows/veracode-analysis.yml
+++ b/.github/workflows/veracode-analysis.yml
@@ -106,265 +106,12 @@ jobs:
     steps:
       - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
 
-      - name: Get build binary
-        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
-        with:
-          path: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
-          key: "${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary"
-          fail-on-cache-miss: true
-
-      - name: Get baseline files
-        run: |
-          set -e
-          # Install aws cli
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          sudo unzip -q awscliv2.zip
-          sudo ./aws/install
-
-          # Find baseline file
-          baseline_file_path=""
-          create_baseline_from=""
-          BUCKET="s3://centreon-veracode-reports/${{ inputs.module_name }}"
-          if [[ "${{ inputs.stability }}" == "testing" ]] || [[ ${{ github.base_ref || github.ref_name }} =~ ^hotfix-[2-9][0-9].[0-9][0-9]-next ]]; then
-            TARGETS=( "${{ github.base_ref || github.ref_name }}" "${{ inputs.major_version }}.x" master )
-          else
-            TARGETS=( "${{ github.base_ref || github.ref_name }}" "dev-${{ inputs.major_version }}.x" develop )
-          fi
-
-          for TARGET in "${TARGETS[@]}"; do
-            RESULT=0
-            echo "[INFO] - Searching baseline file for $TARGET's"
-            aws s3 ls "$BUCKET/$TARGET/results.json" || RESULT=$( echo $? )
-            if [[ $RESULT -eq 0 ]]; then
-              aws s3 cp "$BUCKET/$TARGET/results.json" "/tmp/results.json"
-              echo "[INFO] - Found $TARGET's baseline file"
-              baseline_file_path="/tmp/results.json"
-              create_baseline_from="standard"
-              break
-            else
-              echo "::warning::Baseline file not found for branch $TARGET"
-            fi
-          done
-
-          echo "baseline_file=$baseline_file_path" >> $GITHUB_ENV
-          echo "create_baseline_from=$create_baseline_from" >> $GITHUB_ENV
-          cat $GITHUB_ENV
-
-      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
-        with:
-          distribution: 'zulu'
-          java-version: 8
-
-      - name: Pipeline scan
-        uses: veracode/Veracode-pipeline-scan-action@fe0924c134a03ab5a74fcb9722ed8456efa48e17 # v1.0.16
-        continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
-        with:
-          vid: "vera01ei-${{ secrets.veracode_api_id }}"
-          vkey: "vera01es-${{ secrets.veracode_api_key }}"
-          file: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
-          baseline_file: "${{ env.baseline_file }}"
-          create_baseline_from: "${{ env.create_baseline_from }}"
-          fail_build: '${{ needs.build.outputs.fail_build }}'
-          fail_on_severity: "'Very High','High'"
-          timeout: 60
-          development_stage: '${{ needs.build.outputs.development_stage }}'
-          summary_display: '${{ needs.build.outputs.display_summary }}'
-          issue_details: '${{ needs.build.outputs.display_summary }}'
-
-      - name: Backup analysis reports
-        # debug step used to investigate support case
-        if: needs.build.outputs.enable_qg == 'false' || failure()
-        run: |
-          echo "[DEBUG] downloaded baseline details in /tmp"
-          ls -la /tmp
-          echo "[DEBUG] current location details of analysis results"
-          pwd
-          ls -la
-
-          function backup_baseline(){
-            echo "" # adding a blank line
-            if [[ -z $1 ]]; then
-              echo "[ERROR] Missing mandatory parameters to backup baseline file"
-              exit 0
-            fi
-            CURRENT_NAME=$1
-
-            # specific case for downloaded baseline file
-            if [[ -n $2 && "$2" != "downloaded" ]]; then
-              echo "[ERROR] Missing downloaded baseline mandatory parameter to continue"
-              exit 0
-            fi
-            [[ -n $2 ]] && TARGET=$BASE_BRANCH || TARGET=$CURRENT_PR
-            [[ -n $2 ]] && FILENAME="/tmp/$CURRENT_NAME" || FILENAME="$CURRENT_NAME"
-            [[ -n $2 ]] && NEW_NAME="baseline.json" || NEW_NAME=$CURRENT_NAME
-
-            echo "[DEBUG] FILENAME = $FILENAME"
-            if [[ -s "$FILENAME" ]]; then
-              FILE_DETAILS=$( stat -c '%s %y' "$FILENAME" )
-              DETAILS=(${FILE_DETAILS//\ / })
-
-              FILE_SIZE=${DETAILS[0]}
-              CREATION_DATE=${DETAILS[1]}
-              CREATION_TIME=$( echo "${DETAILS[2]}" | cut -d ':' -f1-2 | tr ':' 'h' )
-              cp "$FILENAME" "/tmp/backup/$TARGET.$CREATION_DATE.$CREATION_TIME.size$FILE_SIZE.$NEW_NAME"
-            else
-              echo "[WARN] - no $CURRENT_NAME found for FILENAME. Skipping it"
-            fi
-          }
-
-          CURRENT_DATE=$( date +"%Y-%m-%d" )
-          CURRENT_PR="PR-"$( echo "${{ github.ref_name }}" | cut -d '/' -f1 )
-          BASE_BRANCH=${{ github.base_ref || github.ref_name }}
-          BACKUP_LOCATION="s3://centreon-veracode-reports/${{ inputs.module_name }}/debug/$CURRENT_PR"
-
-          # saving all reports
-          mkdir /tmp/backup
-          backup_baseline "results.json" "downloaded"
-          backup_baseline "results.json"
-          backup_baseline "filtered_results.json"
-
-          ZIPNAME="$CURRENT_PR.$CURRENT_DATE.${{github.run_id}}.zip"
-          cd /tmp/backup && zip "$ZIPNAME" *
-          aws s3 cp "/tmp/backup/$ZIPNAME" "$BACKUP_LOCATION/$ZIPNAME"
-
       - name: Create jira ticket
         # In case of QG failure, a ticket must be created
-        if: needs.build.outputs.enable_qg == 'false' || ( needs.build.outputs.development_stage == 'Development' && failure() )
+        #if: needs.build.outputs.enable_qg == 'false' || ( needs.build.outputs.development_stage == 'Development' && failure() )
         uses: ./.github/actions/veracode-create-jira-ticket
         with:
           jira_base_url: ${{ secrets.jira_base_url }}
           jira_user_email: ${{ secrets.jira_user_email }}
           jira_api_token: ${{ secrets.jira_api_token }}
           module_name: ${{ inputs.module_name }}
-
-      - name: Save baseline files
-        # only baseline files not generated from a development branch are saved
-        if: success() && needs.build.outputs.development_stage != 'Development'
-        run: |
-          BRANCHES=(develop master dev-${{ inputs.major_version }}.x ${{ inputs.major_version }}.x)
-          for BRANCH in "${BRANCHES[@]}"; do
-            if [[ "${{ github.ref_name }}" == "$BRANCH" ]]; then
-              mv *results.json /tmp
-              BUCKET="s3://centreon-veracode-reports/${{ inputs.module_name }}/${{ github.base_ref || github.ref_name }}"
-              aws s3 cp "/tmp/filtered_results.json" "$BUCKET/filtered_results.json"
-              aws s3 cp "/tmp/results.json" "$BUCKET/results.json"
-            fi
-          done
-
-  clean-artifact:
-    needs: [pipeline-scan]
-    name: Clean artifact
-    if: success() || failure()
-    runs-on: ubuntu-22.04
-
-    steps:
-      - uses: geekyeggo/delete-artifact@24928e75e6e6590170563b8ddae9fac674508aa1 # v5.0.0
-        with:
-          name: "Veracode Pipeline-Scan Results"
-
-  policy-scan:
-    needs: [build]
-    name: Run a sandbox scan
-    # only stable and unstable maintenances branches will produce a report
-    if: needs.build.outputs.development_stage != 'Development'
-    runs-on: ubuntu-22.04
-
-    steps:
-      - name: Get build binary
-        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
-        with:
-          path: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
-          key: "${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary"
-          fail-on-cache-miss: true
-
-      - name: Sandbox scan
-        uses: veracode/veracode-uploadandscan-action@f7e1fbf02c5c899fba9f12e3f537b62f2f1230e1 # 0.2.7
-        continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
-        with:
-          appname: "${{ inputs.module_name }}"
-          version: "${{ inputs.major_version }}.${{ inputs.minor_version }}_runId-${{ github.run_id }}_attempt-${{ github.run_attempt }}"
-          filepath: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
-          vid: "vera01ei-${{ secrets.veracode_api_id }}"
-          vkey: "vera01es-${{ secrets.veracode_api_key }}"
-          createprofile: true
-          createsandbox: true
-          sandboxname: "${{ github.ref_name }}"
-          scantimeout: 120
-          includenewmodules: true
-          scanallnonfataltoplevelmodules: true
-          deleteincompletescan: 1
-          scanpollinginterval: 120  # time between two checks in seconds / [30 to 120]
-
-      - name: Promote Scan
-        # only develop will be promoted to policy scan
-        if: success() && github.ref_name == 'develop'
-        env:
-          VERACODE_API_ID: "${{ secrets.veracode_api_id }}"
-          VERACODE_API_SECRET: "${{ secrets.veracode_api_key }}"
-
-        # Action forked due to an API call hardcoding the '.com' route
-        uses: sc979/veracode-sandboxes-helper@616cfc1e3428691c30382dab33d569f00b14f664 # v0.3
-        with:
-          activity: "promote-latest-scan"
-          app-name: "${{ inputs.module_name }}"
-          sandbox-name: "${{ github.ref_name }}"
-          delete-on-promote: false
-
-  sca-scan:
-    needs: [build]
-    name: Run a SCA scan
-    # only stable and unstable maintenance branches will produce a report
-    if: needs.build.outputs.development_stage != 'Development'
-    runs-on: ubuntu-22.04
-    continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
-
-      - name: Prepare analysis
-        run: |
-          cd ${{ inputs.module_directory }}
-
-          echo "[DEBUG] - pnpm dependencies analysis disabled"
-          find ./ -type f -name "package.json" -o -name "package-lock.json" -o -name "npm-shrinkwrap.json" -delete
-
-          if [[ -f composer.json ]]; then
-            echo "is_php_project=true" >> $GITHUB_ENV
-            PHP_VERSION=$(grep -m1 '"php":' composer.json | cut -d ":" -f2 | cut -d"." -f 1,2 |  tr -d '">= ~' )
-            echo "php_version=$PHP_VERSION" >> $GITHUB_ENV
-            echo "trigger_sca_scan=true" >> $GITHUB_ENV
-            if [[ ! -f composer.lock ]]; then
-              composer install --no-dev --optimize-autoloader
-            fi
-          fi
-
-          cat $GITHUB_ENV
-
-      - name: install PHP
-        if: env.is_php_project == 'true'
-        uses: shivammathur/setup-php@2e947f1f6932d141d076ca441d0e1e881775e95b # v2.31.0
-        with:
-          php-version: ${{ env.php_version }}
-          extensions: none
-          tools: composer:v2
-          coverage: none
-        env:
-          fail-fast: "true"
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: SCA scan
-        if: env.trigger_sca_scan == 'true'
-        env:
-          SRCCLR_API_TOKEN: ${{ secrets.veracode_srcclr_token }}
-          SRCCLR_REGION: "ER"
-
-        uses: sc979/veracode-sca@c407924976db886ffb1bfdbbbf3463f0939f835d # v1.11
-        # This action is based on the following command:
-        # curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan "./${{ inputs.module_directory }}" --debug
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          create-issues: false
-          allow-dirty: true
-          path: "./${{ inputs.module_directory }}"
-          recursive: true
