Revert "to revert - trigger test"
This reverts commit 1843304e924f174098a2854b5c08b07380665e13.

diff --git a/.github/workflows/veracode-analysis.yml b/.github/workflows/veracode-analysis.yml
--- a/.github/workflows/veracode-analysis.yml
+++ b/.github/workflows/veracode-analysis.yml
@@ -149,8 +149,76 @@ jobs:
           java-version: 8
 
       - name: Pipeline scan
+        uses: veracode/Veracode-pipeline-scan-action@5644ae0f9f16ccc10344fc874246555d6f08730a # v1.0.14
+        continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
+        with:
+          vid: "vera01ei-${{ secrets.veracode_api_id }}"
+          vkey: "vera01es-${{ secrets.veracode_api_key }}"
+          file: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
+          baseline_file: "${{ env.baseline_file }}"
+          create_baseline_from: "${{ env.create_baseline_from }}"
+          fail_build: '${{ needs.build.outputs.fail_build }}'
+          fail_on_severity: "'Very High','High'"
+          timeout: 60
+          development_stage: '${{ needs.build.outputs.development_stage }}'
+          summary_display: '${{ needs.build.outputs.display_summary }}'
+          issue_details: '${{ needs.build.outputs.display_summary }}'
+
+      - name: Backup analysis reports
+        # debug step used to investigate support case
+        if: needs.build.outputs.enable_qg == 'false' || (failure() && github.event.pull_request.draft == false)
         run: |
-          ls -la toto
+          echo "[DEBUG] downloaded baseline details in /tmp"
+          ls -la /tmp
+          echo "[DEBUG] current location details of analysis results"
+          pwd
+          ls -la
+
+          function backup_baseline(){
+            echo "" # adding a blank line
+            if [[ -z $1 ]]; then
+              echo "[ERROR] Missing mandatory parameters to backup baseline file"
+              exit 0
+            fi
+            CURRENT_NAME=$1
+
+            # specific case for downloaded baseline file
+            if [[ -n $2 && "$2" != "downloaded" ]]; then
+              echo "[ERROR] Missing downloaded baseline mandatory parameter to continue"
+              exit 0
+            fi
+            [[ -n $2 ]] && TARGET=$BASE_BRANCH || TARGET=$CURRENT_PR
+            [[ -n $2 ]] && FILENAME="/tmp/$CURRENT_NAME" || FILENAME="$CURRENT_NAME"
+            [[ -n $2 ]] && NEW_NAME="baseline.json" || NEW_NAME=$CURRENT_NAME
+
+            echo "[DEBUG] FILENAME = $FILENAME"
+            if [[ -s "$FILENAME" ]]; then
+              FILE_DETAILS=$( stat -c '%s %y' "$FILENAME" )
+              DETAILS=(${FILE_DETAILS//\ / })
+
+              FILE_SIZE=${DETAILS[0]}
+              CREATION_DATE=${DETAILS[1]}
+              CREATION_TIME=$( echo "${DETAILS[2]}" | cut -d ':' -f1-2 | tr ':' 'h' )
+              cp "$FILENAME" "/tmp/backup/$TARGET.$CREATION_DATE.$CREATION_TIME.size$FILE_SIZE.$NEW_NAME"
+            else
+              echo "[WARN] - no $CURRENT_NAME found for FILENAME. Skipping it"
+            fi
+          }
+
+          CURRENT_DATE=$( date +"%Y-%m-%d" )
+          CURRENT_PR="PR-"$( echo "${{ github.ref_name }}" | cut -d '/' -f1 )
+          BASE_BRANCH=${{ github.base_ref || github.ref_name }}
+          BACKUP_LOCATION="s3://centreon-veracode-reports/${{ inputs.module_name }}/debug/$CURRENT_PR"
+
+          # saving all reports
+          mkdir /tmp/backup
+          backup_baseline "results.json" "downloaded"
+          backup_baseline "results.json"
+          backup_baseline "filtered_results.json"
+
+          ZIPNAME="$CURRENT_PR.$CURRENT_DATE.${{github.run_id}}.zip"
+          cd /tmp/backup && zip "$ZIPNAME" *
+          aws s3 cp "/tmp/backup/$ZIPNAME" "$BACKUP_LOCATION/$ZIPNAME"
 
       - name: Create jira ticket
         # In case of QG failure, a ticket must be created
@@ -161,3 +229,116 @@ jobs:
           jira_user_email: ${{ secrets.jira_user_email }}
           jira_api_token: ${{ secrets.jira_api_token }}
           module_name: ${{ inputs.module_name }}
+
+      - name: Save baseline files
+        # only baseline files not generated from a development branch are saved
+        if: success() && needs.build.outputs.development_stage != 'Development'
+        run: |
+          BRANCHES=(develop master dev-${{ inputs.major_version }}.x ${{ inputs.major_version }}.x)
+          for BRANCH in "${BRANCHES[@]}"; do
+            if [[ "${{ github.ref_name }}" == "$BRANCH" ]]; then
+              mv *results.json /tmp
+              BUCKET="s3://centreon-veracode-reports/${{ inputs.module_name }}/${{ github.base_ref || github.ref_name }}"
+              aws s3 cp "/tmp/filtered_results.json" "$BUCKET/filtered_results.json"
+              aws s3 cp "/tmp/results.json" "$BUCKET/results.json"
+            fi
+          done
+
+  clean-artifact:
+    needs: [pipeline-scan]
+    name: Clean artifact
+    if: success() || failure()
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: geekyeggo/delete-artifact@65041433121f7239077fa20be14c0690f70569de # v4.1.0
+        with:
+          name: "Veracode Pipeline-Scan Results"
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+  policy-scan:
+    needs: [build]
+    name: Run a sandbox scan
+    # only stable and unstable maintenances branches will produce a report
+    if: needs.build.outputs.development_stage != 'Development'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Get build binary
+        uses: actions/cache/restore@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
+        with:
+          path: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
+          key: "${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary"
+          fail-on-cache-miss: true
+
+      - name: Sandbox scan
+        uses: veracode/veracode-uploadandscan-action@f7e1fbf02c5c899fba9f12e3f537b62f2f1230e1 # master
+        continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
+        with:
+          appname: "${{ inputs.module_name }}"
+          version: "${{ inputs.major_version }}.${{ inputs.minor_version }}_runId-${{ github.run_id }}"
+          filepath: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
+          vid: "vera01ei-${{ secrets.veracode_api_id }}"
+          vkey: "vera01es-${{ secrets.veracode_api_key }}"
+          createprofile: true
+          createsandbox: true
+          sandboxname: "${{ github.ref_name }}"
+          scantimeout: 120
+          includenewmodules: true
+          scanallnonfataltoplevelmodules: true
+          deleteincompletescan: 1
+          scanpollinginterval: 120  # time between two checks in seconds / [30 to 120]
+
+      - name: Promote Scan
+        # only develop will be promoted to policy scan
+        if: success() && github.ref_name == 'develop'
+        env:
+          VERACODE_API_ID: "${{ secrets.veracode_api_id }}"
+          VERACODE_API_SECRET: "${{ secrets.veracode_api_key }}"
+
+        # Action forked due to an API call hardcoding the '.com' route
+        uses: sc979/veracode-sandboxes-helper@cf67241c27cbe6405ad8705111121ece9a48c4ff # v0.2
+        with:
+          activity: "promote-latest-scan"
+          app-name: "${{ inputs.module_name }}"
+          sandbox-name: "${{ github.ref_name }}"
+          delete-on-promote: false
+
+  sca-scan:
+    needs: [build]
+    name: Run a SCA scan
+    # only stable and unstable maintenance branches will produce a report
+    if: needs.build.outputs.development_stage != 'Development'
+    runs-on: ubuntu-latest
+    continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+
+      - name: Removing pnpm dependencies
+        run: |
+          cd ${{ inputs.module_directory }}
+          echo "[DEBUG] - pnpm dependencies analysis disabled"
+          find ./ -type f -name "package.json" -o -name "package-lock.json" -o -name "npm-shrinkwrap.json" -delete
+
+          RESULT=`find ./ -type f -name "composer.lock" -o -name "composer.json"`
+          if [[ -n ${RESULT[0]} ]]; then
+          	echo "trigger_sca_scan=true" >> $GITHUB_ENV
+          fi
+
+      - name: SCA scan
+        if: env.trigger_sca_scan == 'true'
+        env:
+          SRCCLR_API_TOKEN: ${{ secrets.veracode_srcclr_token }}
+          SRCCLR_REGION: "ER"
+
+        uses: sc979/veracode-sca@c407924976db886ffb1bfdbbbf3463f0939f835d # v1.11
+        # This action is based on the following command:
+        # curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan "./${{ inputs.module_directory }}" --debug
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          create-issues: false
+          allow-dirty: true
+          path: "./${{ inputs.module_directory }}"
+          recursive: true
