Revert "to revert : trigger build"
This reverts commit 4238d0eb31b7771f189f14c3cfcdbec666645398.

diff --git a/.github/workflows/veracode-analysis.yml b/.github/workflows/veracode-analysis.yml
--- a/.github/workflows/veracode-analysis.yml
+++ b/.github/workflows/veracode-analysis.yml
@@ -70,11 +70,200 @@ jobs:
           echo "[INFO] - display_summary = $DISPLAY_SUMMARY"
           echo "[INFO] - check if PR branch = $CHECK_BRANCH"
 
+  pipeline-scan:
+    needs: [build]
+    name: Run a pipeline scan
+    runs-on: [self-hosted, veracode]
+
+    steps:
+      - name: Get build binary
+        uses: actions/cache/restore@v3
+        with:
+          path: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
+          key: "${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary"
+          fail-on-cache-miss: true
+
+      - name: Get baseline files
+        run: |
+          BUCKET="s3://centreon-veracode-reports/${{ inputs.module_name }}"
+          aws s3 ls "$BUCKET/${{ github.base_ref || github.ref_name }}/results.json" || RESULT=$( echo $? )
+          if [[ $RESULT -eq 0 ]]; then
+            aws s3 cp "$BUCKET/${{ github.base_ref || github.ref_name }}/results.json" "/tmp/results.json"
+            echo "[INFO] - Found ${{ github.base_ref || github.ref_name }} Baseline file"
+            echo "baseline_file=/tmp/results.json" >> $GITHUB_ENV
+            echo "create_baseline_from=standard" >> $GITHUB_ENV
+          else
+            RESULT=0
+            echo "[WARN] - Baseline file not found for branch ${{ github.base_ref || github.ref_name }}"
+            echo "[INFO] - Trying with default (develop's) Baseline file"
+            aws s3 ls "$BUCKET/develop/results.json" || RESULT=$( echo $? )
+            if [[ $RESULT -eq 0 ]]; then
+              echo "[INFO] - Found default Baseline file"
+              aws s3 cp "$BUCKET/develop/results.json" "/tmp/results.json"
+              echo "baseline_file=/tmp/results.json" >> $GITHUB_ENV
+              echo "create_baseline_from=standard" >> $GITHUB_ENV
+            else
+              echo "[ERROR] - Default baseline file not found in the bucket"
+              echo "baseline_file=" >> $GITHUB_ENV
+              echo "create_baseline_from=" >> $GITHUB_ENV
+            fi
+          fi
+
+      - uses: actions/setup-java@v3
+        with:
+          distribution: 'zulu'
+          java-version: 8
+
+      - name: Pipeline scan
+        uses: veracode/Veracode-pipeline-scan-action@v1.0.8
+        continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
+        with:
+          vid: "vera01ei-${{ secrets.veracode_api_id }}"
+          vkey: "vera01es-${{ secrets.veracode_api_key }}"
+          file: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
+          baseline_file: "${{ env.baseline_file }}"
+          create_baseline_from: "${{ env.create_baseline_from }}"
+          fail_build: '${{ needs.build.outputs.fail_build }}'
+          fail_on_severity: "'Very High','High'"
+          timeout: 60
+          development_stage: '${{ needs.build.outputs.development_stage }}'
+          summary_display: '${{ needs.build.outputs.display_summary }}'
+          issue_details: '${{ needs.build.outputs.display_summary }}'
+
+      - name: Backup analysis reports
+        # debug step used to investigate support case
+        if: ( success() || failure() ) && vars.VERACODE_BACKUP_DEBUG == 'true'
+        run: |
+          echo "[DEBUG] downloaded baseline details in /tmp"
+          ls -la /tmp
+          echo "[DEBUG] current location details of analysis results"
+          pwd
+          ls -la
+
+          function backup_baseline(){
+            echo "" # adding a blank line
+            if [[ -z $1 ]]; then
+              echo "[ERROR] Missing mandatory parameters to backup baseline file"
+              exit 0
+            fi
+            CURRENT_NAME=$1
+
+            # specific case for downloaded baseline file
+            if [[ -n $2 && "$2" != "downloaded" ]]; then
+              echo "[ERROR] Missing downloaded baseline mandatory parameter to continue"
+              exit 0
+            fi
+            [[ -n $2 ]] && TARGET=$BASE_BRANCH || TARGET=$CURRENT_PR
+            [[ -n $2 ]] && FILENAME="/tmp/$CURRENT_NAME" || FILENAME="$CURRENT_NAME"
+            [[ -n $2 ]] && NEW_NAME="baseline.json" || NEW_NAME=$CURRENT_NAME
+
+            echo "[DEBUG] FILENAME = $FILENAME"
+            if [[ -s "$FILENAME" ]]; then
+              FILE_DETAILS=$( stat -c '%s %y' "$FILENAME" )
+              DETAILS=(${FILE_DETAILS//\ / })
+
+              FILE_SIZE=${DETAILS[0]}
+              CREATION_DATE=${DETAILS[1]}
+              CREATION_TIME=$( echo "${DETAILS[2]}" | cut -d ':' -f1-2 | tr ':' 'h' )
+              cp "$FILENAME" "/tmp/backup/$TARGET.$CREATION_DATE.$CREATION_TIME.size$FILE_SIZE.$NEW_NAME"
+            else
+              echo "[WARN] - no $CURRENT_NAME found for FILENAME. Skipping it"
+            fi
+          }
+
+          CURRENT_DATE=$( date +"%Y-%m-%d" )
+          CURRENT_PR="PR-"$( echo "${{ github.ref_name }}" | cut -d '/' -f1 )
+          BASE_BRANCH=${{ github.base_ref || github.ref_name }}
+          BACKUP_LOCATION="s3://centreon-veracode-reports/${{ inputs.module_name }}/debug/$CURRENT_PR"
+
+          # saving all reports
+          mkdir /tmp/backup
+          backup_baseline "results.json" "downloaded"
+          backup_baseline "results.json"
+          backup_baseline "filtered_results.json"
+
+          ZIPNAME="$CURRENT_PR.$CURRENT_DATE.${{github.run_id}}.zip"
+          cd /tmp/backup && zip "$ZIPNAME" *
+          aws s3 cp "/tmp/backup/$ZIPNAME" "$BACKUP_LOCATION/$ZIPNAME"
+
+      - name: Save baseline files
+        # only baseline files not generated from a development branch are saved
+        if: success() && needs.build.outputs.development_stage != 'Development'
+        run: |
+          BRANCHES=(develop master dev-${{ inputs.major_version }}.x ${{ inputs.major_version }}.x)
+          for BRANCH in "${BRANCHES[@]}"; do
+            if [[ "${{ github.ref_name }}" == "$BRANCH" ]]; then
+              mv *results.json /tmp
+              BUCKET="s3://centreon-veracode-reports/${{ inputs.module_name }}/${{ github.base_ref || github.ref_name }}"
+              aws s3 cp "/tmp/filtered_results.json" "$BUCKET/filtered_results.json"
+              aws s3 cp "/tmp/results.json" "$BUCKET/results.json"
+            fi
+          done
+
+  clean-artifact:
+    needs: [pipeline-scan]
+    name: Clean artifact
+    if: success() || failure()
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: geekyeggo/delete-artifact@v2
+        with:
+          name: "Veracode Pipeline-Scan Results"
+
+  policy-scan:
+    needs: [build]
+    name: Run a sandbox scan
+    # only stable and unstable maintenances branches will produce a report
+    if: needs.build.outputs.development_stage != 'Development'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Get build binary
+        uses: actions/cache/restore@v3
+        with:
+          path: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
+          key: "${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary"
+          fail-on-cache-miss: true
+
+      - name: Sandbox scan
+        uses: veracode/veracode-uploadandscan-action@master
+        continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
+        with:
+          appname: "${{ inputs.module_name }}"
+          version: "${{ inputs.major_version }}.${{ inputs.minor_version }}_runId-${{ github.run_id }}"
+          filepath: "${{ inputs.module_directory }}/${{ inputs.module_name }}-${{ github.sha }}-${{ github.run_id }}-veracode-binary.zip"
+          vid: "vera01ei-${{ secrets.veracode_api_id }}"
+          vkey: "vera01es-${{ secrets.veracode_api_key }}"
+          createprofile: true
+          createsandbox: true
+          sandboxname: "${{ github.ref_name }}"
+          scantimeout: 120
+          includenewmodules: true
+          scanallnonfataltoplevelmodules: true
+          deleteincompletescan: 1
+          scanpollinginterval: 120 # time between two checks in seconds / [30 to 120]
+
+      - name: Promote Scan
+        # only develop will be promoted to policy scan
+        if: success() && github.ref_name == 'develop'
+        env:
+          VERACODE_API_ID: "${{ secrets.veracode_api_id }}"
+          VERACODE_API_SECRET: "${{ secrets.veracode_api_key }}"
+
+        # Action forked as API call hardcode '.com' route
+        uses: sc979/veracode-sandboxes-helper@v0.2
+        with:
+          activity: "promote-latest-scan"
+          app-name: "${{ inputs.module_name }}"
+          sandbox-name: "${{ github.ref_name }}"
+          delete-on-promote: false
+
   sca-scan:
     needs: [build]
     name: Run a SCA scan
     # only stable and unstable maintenance branches will produce a report
-    #if: needs.build.outputs.development_stage != 'Development'
+    if: needs.build.outputs.development_stage != 'Development'
     runs-on: ubuntu-latest
     continue-on-error: ${{ vars.VERACODE_CONTINUE_ON_ERROR == 'true' }}
 
