test

diff --git a/.github/workflows/veracode-pipeline-scan.yml b/.github/workflows/veracode-pipeline-scan.yml
--- a/.github/workflows/veracode-pipeline-scan.yml
+++ b/.github/workflows/veracode-pipeline-scan.yml
@@ -72,31 +72,15 @@ jobs:
       - name: DEBUG - Github head ref
         run: echo ${{ inputs.head_ref_name }} #TODO: to remove
 
-      - name: Setup awscli
-        run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          sudo unzip -q awscliv2.zip
-          sudo ./aws/install
-
-      - name: Get baseline file
-        run: |
-          TARGET_S3="s3://centreon-veracode-reports/${{ inputs.module_name }}/${{ inputs.target_branch_name }}/results.json"
-          BASELINE_FILE="/tmp/results.json"
-          aws s3 ls "$TARGET_S3" || RESULT=$( echo $? )
-          if [[ $RESULT -eq 0 ]]; then
-            aws s3 cp "$TARGET_S3" "$BASELINE_FILE"
-            echo "baseline_file=$BASELINE_FILE" >> $GITHUB_OUTPUT
-          else
-            echo "[DEBUG] - File not found in the bucket"
-            echo "baseline_file=" >> $GITHUB_OUTPUT
-          fi
-
       - name: Get current time
         run: echo "$(date +'%Y-%m-%d %H:%M:%S')"
 
   pipeline-scan:
     runs-on: [self-hosted, veracode]
     needs: [build]
+    outputs:
+      baseline_file: ''
+
     steps:
 #      - uses: actions/checkout@v3
 
@@ -110,6 +94,26 @@ jobs:
         with:
           distribution: 'zulu'
           java-version: 8
+
+      - name: Setup awscli
+        run: |
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          sudo unzip -q awscliv2.zip
+          sudo ./aws/install
+
+      - name: Get baseline file
+        id: baseline_search
+        run: |
+          TARGET_S3="s3://centreon-veracode-reports/${{ inputs.module_name }}/${{ inputs.target_branch_name }}/results.json"
+          BASELINE_FILE="/tmp/results.json"
+          aws s3 ls "$TARGET_S3" || RESULT=$( echo $? )
+          if [[ $RESULT -eq 0 ]]; then
+            aws s3 cp "$TARGET_S3" "$BASELINE_FILE"
+            echo "baseline_file=$BASELINE_FILE" >> $GITHUB_OUTPUT
+          else
+            echo "[DEBUG] - File not found in the bucket"
+            echo "baseline_file=" >> $GITHUB_OUTPUT
+          fi
 
       - name: DEBUG - check location
         run: ls -la
