try node_modules

diff --git a/.github/workflows/veracode-analysis.yml b/.github/workflows/veracode-analysis.yml
--- a/.github/workflows/veracode-analysis.yml
+++ b/.github/workflows/veracode-analysis.yml
@@ -204,6 +204,12 @@ jobs:
           fi
 
           if [[ -f package.json ]]; then
+            npm i --package-lock-only --legacy-peer-dep --omit=dev 1>/dev/null || RESULT=$( echo $? )
+            if [[ $RESULT -ne 0 ]]; then
+              echo "[DEBUG] - Failure of '$ npm install'. Deleting the 'node_modules' to avoid analysis failure"
+              rm -rf node_modules
+            fi
+
             rm -f package.json
           fi
 
