echo condition

diff --git a/.github/workflows/web.yml b/.github/workflows/web.yml
--- a/.github/workflows/web.yml
+++ b/.github/workflows/web.yml
@@ -955,13 +955,14 @@ jobs:
         deliver-rpm,
         deliver-deb
       ]
-    if: |
-        contains(fromJson('["testing", "unstable", "canary"]'), needs.get-environment.outputs.stability) &&
-        (cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) &&
-        (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && contains(github.workflow, 'nightly')))
     steps:
       - name: Checkout sources
         uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
+
+      - run: |
+          echo ${{ contains(fromJson('["testing", "unstable", "canary"]'), needs.get-environment.outputs.stability) }}
+          echo ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+          echo ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && contains(github.workflow, 'nightly')) }}
 
       - name: Create Jira ticket
         uses: ./.github/actions/create-jira-ticket
