enh(ci): suggest translation changes

diff --git a/.github/workflows/web.yml b/.github/workflows/web.yml
--- a/.github/workflows/web.yml
+++ b/.github/workflows/web.yml
@@ -241,170 +241,174 @@ jobs:
           mkdir -p www/locale/en_US.UTF-8/LC_MESSAGES
           php bin/centreon-translations.php en lang/fr_FR.UTF-8/LC_MESSAGES/messages.po www/locale/en_US.UTF-8/LC_MESSAGES/messages.ser
 
-          if [[ '${{ github.event_name }}' == 'pull_request' && `git status --porcelain` ]]; then
-            git config user.name "technique-ci"
-            git config user.email "technique+ci@centreon.com"
-            git status
-            git add .
-            git commit -m "chore(lang): update translations"
-            git push
-          fi
+          # if [[ '${{ github.event_name }}' == 'pull_request' && `git status --porcelain` ]]; then
+          #   git config user.name "technique-ci"
+          #   git config user.email "technique+ci@centreon.com"
+          #   git status
+          #   git add .
+          #   git commit -m "chore(lang): update translations"
+          #   git push
+          # fi
         shell: bash
+
+      - uses: ./.github/actions/suggests-changes
+        with:
+          comment: automatic code suggestions
 
       - uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         with:
           path: ${{ env.base_directory }}/www/locale
           key: ${{ github.sha }}-${{ github.run_id }}-translation
 
-  frontend-web-lint:
-    runs-on: ubuntu-24.04
-    needs: [changes, get-environment]
-    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_frontend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
+  # frontend-web-lint:
+  #   runs-on: ubuntu-24.04
+  #   needs: [changes, get-environment]
+  #   if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_frontend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
 
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #   steps:
+  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - uses: ./.github/actions/frontend-lint
-        with:
-          frontend_directory: ${{ env.base_directory }}
-          module_name: centreon
-          dependencies_lock_file: ${{ env.base_directory }}/pnpm-lock.yaml
-          pat: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          lint_path: ./www/front_src/
+  #     - uses: ./.github/actions/frontend-lint
+  #       with:
+  #         frontend_directory: ${{ env.base_directory }}
+  #         module_name: centreon
+  #         dependencies_lock_file: ${{ env.base_directory }}/pnpm-lock.yaml
+  #         pat: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         lint_path: ./www/front_src/
 
-  frontend-unit-test:
-    runs-on: ubuntu-24.04
-    needs: [changes, get-environment]
-    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_frontend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
+  # frontend-unit-test:
+  #   runs-on: ubuntu-24.04
+  #   needs: [changes, get-environment]
+  #   if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_frontend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
 
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #   steps:
+  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
-        with:
-          version: 10
-          run_install: false
+  #     - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
+  #       with:
+  #         version: 10
+  #         run_install: false
 
-      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
-        with:
-          node-version: 20
-          cache: pnpm
-          cache-dependency-path: ${{ env.base_directory }}/pnpm-lock.yaml
+  #     - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
+  #       with:
+  #         node-version: 20
+  #         cache: pnpm
+  #         cache-dependency-path: ${{ env.base_directory }}/pnpm-lock.yaml
 
-      - name: Install dependencies
-        run: pnpm install --frozen-lockfile
-        working-directory: centreon
-        env:
-          CYPRESS_INSTALL_BINARY: "0"
-          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
-          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
+  #     - name: Install dependencies
+  #       run: pnpm install --frozen-lockfile
+  #       working-directory: centreon
+  #       env:
+  #         CYPRESS_INSTALL_BINARY: "0"
+  #         PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
+  #         PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
 
-      - name: Unit test
-        run: pnpm t --silent --reporter=jest-junit
-        working-directory: centreon
+  #     - name: Unit test
+  #       run: pnpm t --silent --reporter=jest-junit
+  #       working-directory: centreon
 
-      - if: failure()
-        uses: ./.github/actions/publish-report
-        with:
-          path: "centreon/junit.xml"
+  #     - if: failure()
+  #       uses: ./.github/actions/publish-report
+  #       with:
+  #         path: "centreon/junit.xml"
 
-  frontend-component-test:
-    needs: [changes, get-environment]
-    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_frontend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
-    uses: ./.github/workflows/cypress-component-parallelization.yml
-    secrets:
-      AWS_ACCESS_KEY_ID: ${{ secrets.LIGHTHOUSE_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.LIGHTHOUSE_SECRET }}
-      jira_base_url: ${{ secrets.JIRA_BASE_URL }}
-      jira_user_email: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
-      jira_api_token: ${{ secrets.XRAY_JIRA_TOKEN }}
-    with:
-      name: centreon
-      module_name: centreon
-      specs_path: www/**
-      dependencies_lock_file: centreon/pnpm-lock.yaml
-      is_nightly: ${{ needs.get-environment.outputs.is_nightly }}
+  # frontend-component-test:
+  #   needs: [changes, get-environment]
+  #   if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_frontend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
+  #   uses: ./.github/workflows/cypress-component-parallelization.yml
+  #   secrets:
+  #     AWS_ACCESS_KEY_ID: ${{ secrets.LIGHTHOUSE_ID }}
+  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.LIGHTHOUSE_SECRET }}
+  #     jira_base_url: ${{ secrets.JIRA_BASE_URL }}
+  #     jira_user_email: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
+  #     jira_api_token: ${{ secrets.XRAY_JIRA_TOKEN }}
+  #   with:
+  #     name: centreon
+  #     module_name: centreon
+  #     specs_path: www/**
+  #     dependencies_lock_file: centreon/pnpm-lock.yaml
+  #     is_nightly: ${{ needs.get-environment.outputs.is_nightly }}
 
-  backend-unit-test:
-    runs-on: ubuntu-24.04
-    needs: [changes, get-environment]
-    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_backend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
+  # backend-unit-test:
+  #   runs-on: ubuntu-24.04
+  #   needs: [changes, get-environment]
+  #   if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_backend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
 
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #   steps:
+  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Setup PHP
-        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
-        with:
-          php-version: 8.2
-          coverage: none
-        env:
-          runner: ubuntu-24.04
+  #     - name: Setup PHP
+  #       uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
+  #       with:
+  #         php-version: 8.2
+  #         coverage: none
+  #       env:
+  #         runner: ubuntu-24.04
 
-      - name: Install dependencies
-        uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565 # v3.1.0
-        with:
-          working-directory: centreon
-          composer-options: "--optimize-autoloader"
+  #     - name: Install dependencies
+  #       uses: ramsey/composer-install@a2636af0004d1c0499ffca16ac0b4cc94df70565 # v3.1.0
+  #       with:
+  #         working-directory: centreon
+  #         composer-options: "--optimize-autoloader"
 
-      - name: Unit test
-        run: XDEBUG_MODE=coverage composer run-script test:ci
-        working-directory: centreon
+  #     - name: Unit test
+  #       run: XDEBUG_MODE=coverage composer run-script test:ci
+  #       working-directory: centreon
 
-      - if: failure()
-        uses: ./.github/actions/publish-report
-        with:
-          path: "centreon/build/phpunit.xml"
-          format: "php-junit"
+  #     - if: failure()
+  #       uses: ./.github/actions/publish-report
+  #       with:
+  #         path: "centreon/build/phpunit.xml"
+  #         format: "php-junit"
 
-  backend-lint:
-    runs-on: ubuntu-24.04
-    needs: [changes, get-environment]
-    if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_backend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
+  # backend-lint:
+  #   runs-on: ubuntu-24.04
+  #   needs: [changes, get-environment]
+  #   if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && needs.changes.outputs.has_backend_changes == 'true' && needs.get-environment.outputs.stability != 'stable' }}
 
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #   steps:
+  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Setup PHP
-        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
-        with:
-          php-version: 8.2
-          coverage: none
-        env:
-          runner: ubuntu-24.04
+  #     - name: Setup PHP
+  #       uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
+  #       with:
+  #         php-version: 8.2
+  #         coverage: none
+  #       env:
+  #         runner: ubuntu-24.04
 
-      - name: Install Dependencies
-        run: composer install --optimize-autoloader
-        working-directory: centreon
-        shell: bash
+  #     - name: Install Dependencies
+  #       run: composer install --optimize-autoloader
+  #       working-directory: centreon
+  #       shell: bash
 
-      - name: Create configuration file
-        run: cp config/centreon.config.php.template config/centreon.config.php
-        working-directory: centreon
+  #     - name: Create configuration file
+  #       run: cp config/centreon.config.php.template config/centreon.config.php
+  #       working-directory: centreon
 
-      - name: Check Symfony configuration
-        run: composer symfony:check:ci
-        working-directory: centreon
+  #     - name: Check Symfony configuration
+  #       run: composer symfony:check:ci
+  #       working-directory: centreon
 
-      - name: Run of php-cs-fixer with strict_type
-        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --verbose --dry-run --diff
-        working-directory: centreon
+  #     - name: Run of php-cs-fixer with strict_type
+  #       run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --verbose --dry-run --diff
+  #       working-directory: centreon
 
-      - name: Run of php-cs-fixer without strict_type
-        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.unstrict.php --verbose --dry-run --diff
-        working-directory: centreon
+  #     - name: Run of php-cs-fixer without strict_type
+  #       run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.unstrict.php --verbose --dry-run --diff
+  #       working-directory: centreon
 
-      - name: Run of phpstan on /src at level 4
-        run: vendor/bin/phpstan analyse --no-progress --level=4 --configuration=phpstan.neon
-        working-directory: centreon
+  #     - name: Run of phpstan on /src at level 4
+  #       run: vendor/bin/phpstan analyse --no-progress --level=4 --configuration=phpstan.neon
+  #       working-directory: centreon
 
-      - name: Run of phpstan on /src/Core at level 8 + Centreon Custom Rules
-        run: vendor/bin/phpstan analyse --no-progress --level=8 --configuration=phpstan.core.neon
-        working-directory: centreon
+  #     - name: Run of phpstan on /src/Core at level 8 + Centreon Custom Rules
+  #       run: vendor/bin/phpstan analyse --no-progress --level=8 --configuration=phpstan.core.neon
+  #       working-directory: centreon
 
-      - name: Run of phpstan on /tests at level 2
-        run: vendor/bin/phpstan analyse --no-progress --level=2 --configuration=phpstan.test.neon
-        working-directory: centreon
+  #     - name: Run of phpstan on /tests at level 2
+  #       run: vendor/bin/phpstan analyse --no-progress --level=2 --configuration=phpstan.test.neon
+  #       working-directory: centreon
 
   package:
     needs:
@@ -413,12 +417,12 @@ jobs:
         get-environment,
         translation-build,
         backend-dependencies,
-        backend-lint,
-        backend-unit-test,
+        # backend-lint,
+        # backend-unit-test,
         frontend-web-build,
-        frontend-web-lint,
-        frontend-unit-test,
-        frontend-component-test,
+        # frontend-web-lint,
+        # frontend-unit-test,
+        # frontend-component-test,
       ]
     if: ${{ needs.get-environment.outputs.skip_workflow == 'false' && !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && needs.get-environment.outputs.stability != 'stable' }}
 
@@ -450,6 +454,7 @@ jobs:
     name: package ${{ matrix.distrib }}
 
     steps:
+      - run: exit 1
       - name: Checkout sources
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
