test ci web workflow

diff --git a/.github/workflows/web.yml b/.github/workflows/web.yml
--- a/.github/workflows/web.yml
+++ b/.github/workflows/web.yml
@@ -592,19 +592,19 @@ jobs:
             echo "::group::php-cs-fixer Legacy"
             composer cs:legacy:www -- --format=txt --show-progress=none \
             && composer cs:legacy:src -- --format=txt --show-progress=none \
-            && composer cs:legacy:test -- --format=txt --show-progress=none
+            && composer cs:legacy:test -- --format=txt --show-progress=none && echo "✅ PHP-CS-Fixer Legacy: Success" || { echo "❌ PHP-CS-Fixer Legacy: Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
           {
             echo "::group::php-cs-fixer Core"
-            composer cs:core -- --format=txt --show-progress=none
+            composer cs:core -- --format=txt --show-progress=none && echo "✅ PHP-CS-Fixer Core: Success" || { echo "❌ PHP-CS-Fixer Core: Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
           {
             echo "::group::php-cs-fixer New"
-            composer cs:new -- --format=txt --show-progress=none
+            composer cs:new -- --format=txt --show-progress=none && echo "✅ PHP-CS-Fixer New: Success" || { echo "❌ PHP-CS-Fixer New: Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
@@ -620,21 +620,21 @@ jobs:
             echo "::group::PHPStan Legacy"
             composer stan:legacy:www -- --no-progress \
             && composer stan:legacy:src -- --no-progress \
-            && composer stan:legacy:test -- --no-progress
+            && composer stan:legacy:test -- --no-progress && echo "✅ PHPStan Legacy: Success" || { echo "❌ PHPStan Legacy: Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
           {
             echo "::group::PHPStan Core"
             composer stan:core:src -- --no-progress \
-            composer stan:core:test -- --no-progress
+            && composer stan:core:test -- --no-progress && echo "✅ PHPStan Core: Success" || { echo "❌ PHPStan Core: Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
           {
             echo "::group::PHPStan New"
             composer stan:new:src -- --no-progress \
-            composer stan:new:test -- --no-progress
+            && composer stan:new:test -- --no-progress && echo "✅ PHPStan New: Success" || { echo "❌ PHPStan New: Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
