test ci web workflow

diff --git a/.github/workflows/web.yml b/.github/workflows/web.yml
--- a/.github/workflows/web.yml
+++ b/.github/workflows/web.yml
@@ -589,10 +589,20 @@ jobs:
           set -e
 
           {
-            echo "::group::php-cs-fixer Legacy"
-            composer cs:legacy:www -- --format=txt --show-progress=none \
-            && composer cs:legacy:src -- --format=txt --show-progress=none \
-            && composer cs:legacy:test -- --format=txt --show-progress=none && echo "✅ PHP-CS-Fixer Legacy: Success" || { echo "❌ PHP-CS-Fixer Legacy: Failed"; exit 1; }
+            echo "::group::php-cs-fixer legacy:www"
+            composer cs:legacy:www -- --format=txt --show-progress=none && echo "✅ PHP-CS-Fixer Legacy (www): Success" || { echo "❌ PHP-CS-Fixer Legacy (www): Failed"; exit 1; }
+            echo "::endgroup::"
+          } &
+
+          {
+            echo "::group::php-cs-fixer legacy:src"
+            composer cs:legacy:src -- --format=txt --show-progress=none && echo "✅ PHP-CS-Fixer Legacy (src): Success" || { echo "❌ PHP-CS-Fixer Legacy (src): Failed"; exit 1; }
+            echo "::endgroup::"
+          } &
+
+          {
+            echo "::group::php-cs-fixer legacy:test"
+            composer cs:legacy:test -- --format=txt --show-progress=none && echo "✅ PHP-CS-Fixer Legacy (test): Success" || { echo "❌ PHP-CS-Fixer Legacy (test): Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
@@ -617,24 +627,44 @@ jobs:
           set -e
 
           {
-            echo "::group::PHPStan Legacy"
-            composer stan:legacy:www -- --no-progress \
-            && composer stan:legacy:src -- --no-progress \
-            && composer stan:legacy:test -- --no-progress && echo "✅ PHPStan Legacy: Success" || { echo "❌ PHPStan Legacy: Failed"; exit 1; }
+            echo "::group::PHPStan legacy:www"
+            composer stan:legacy:www -- --no-progress && echo "✅ PHPStan Legacy (www): Success" || { echo "❌ PHPStan Legacy (www): Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
           {
-            echo "::group::PHPStan Core"
-            composer stan:core:src -- --no-progress \
-            && composer stan:core:test -- --no-progress && echo "✅ PHPStan Core: Success" || { echo "❌ PHPStan Core: Failed"; exit 1; }
+            echo "::group::PHPStan legacy:src"
+            composer stan:legacy:src -- --no-progress && echo "✅ PHPStan Legacy (src): Success" || { echo "❌ PHPStan Legacy (src): Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
           {
-            echo "::group::PHPStan New"
-            composer stan:new:src -- --no-progress \
-            && composer stan:new:test -- --no-progress && echo "✅ PHPStan New: Success" || { echo "❌ PHPStan New: Failed"; exit 1; }
+            echo "::group::PHPStan legacy:test"
+            composer stan:legacy:test -- --no-progress && echo "✅ PHPStan Legacy (test): Success" || { echo "❌ PHPStan Legacy (test): Failed"; exit 1; }
+            echo "::endgroup::"
+          } &
+
+          {
+            echo "::group::PHPStan core:src"
+            composer stan:core:src -- --no-progress && echo "✅ PHPStan Core (src): Success" || { echo "❌ PHPStan Core (src): Failed"; exit 1; }
+            echo "::endgroup::"
+          } &
+
+          {
+            echo "::group::PHPStan core:test"
+            composer stan:core:test -- --no-progress && echo "✅ PHPStan Core (test): Success" || { echo "❌ PHPStan Core (test): Failed"; exit 1; }
+            echo "::endgroup::"
+          } &
+
+          {
+            echo "::group::PHPStan new:src"
+            composer stan:new:src -- --no-progress && echo "✅ PHPStan New (src): Success" || { echo "❌ PHPStan New (src): Failed"; exit 1; }
+            echo "::endgroup::"
+          } &
+
+          {
+            echo "::group::PHPStan new:test"
+            && composer stan:new:test -- --no-progress && echo "✅ PHPStan New (test): Success" || { echo "❌ PHPStan New (test): Failed"; exit 1; }
             echo "::endgroup::"
           } &
 
