fix matrix

diff --git a/.github/workflows/web.yml b/.github/workflows/web.yml
--- a/.github/workflows/web.yml
+++ b/.github/workflows/web.yml
@@ -312,24 +312,36 @@ jobs:
     needs: [get-version, package]
     if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && needs.get-version.outputs.stability != 'stable' }}
 
+    env:
+      project: centreon-web
     strategy:
       matrix:
         os: ${{ fromJson(needs.get-version.outputs.dockerize_matrix) }}
-        include:
-          - project: centreon-web
-          - os: alma8
-            distrib: el8
-            package_extension: rpm
-          - os: alma9
-            distrib: el9
-            package_extension: rpm
-          - os: bullseye
-            distrib: debian
-            package_extension: deb
 
     steps:
       - name: Checkout sources
         uses: actions/checkout@v3
+
+      - name: Generate information according to matrix os
+        id: matrix_include
+        run: |
+          if [ "${{ matrix.os }}" = "alma8"]; then
+            DISTRIB=el8
+            PACKAGE_EXTENSION=rpm
+          elif [ "${{ matrix.os }}" = "alma9"]; then
+            DISTRIB=el9
+            PACKAGE_EXTENSION=rpm
+          elif [ "${{ matrix.os }}" = "bullseye"]; then
+            DISTRIB=bullseye
+            PACKAGE_EXTENSION=deb
+          else
+            echo "::error::${{ matrix.os }} is not managed"
+            exit 1
+          fi
+
+          echo "distrib=$DISTRIB" >> $GITHUB_OUTPUT
+          echo "package_extension=$PACKAGE_EXTENSION" >> $GITHUB_OUTPUT
+        shell: bash
 
       - name: Login to registry
         uses: docker/login-action@v2
@@ -338,18 +350,18 @@ jobs:
           username: ${{ secrets.DOCKER_REGISTRY_ID }}
           password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
 
-      - name: Restore ${{ matrix.package_extension }} files
+      - name: Restore ${{ steps.matrix_include.outputs.package_extension }} files
         uses: actions/cache@v3
         with:
-          path: ./*.${{ matrix.package_extension }}
-          key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
+          path: ./*.${{ steps.matrix_include.outputs.package_extension }}
+          key: ${{ github.sha }}-${{ github.run_id }}-${{ steps.matrix_include.outputs.package_extension }}-${{ steps.matrix_include.outputs.distrib }}
           fail-on-cache-miss: true
 
       - uses: docker/setup-buildx-action@v2
 
       - uses: docker/build-push-action@v3
         with:
-          file: .github/docker/Dockerfile.${{ matrix.project }}-${{ matrix.os }}
+          file: .github/docker/Dockerfile.${{ env.project }}-${{ matrix.os }}
           target: web_fresh
           context: .
           build-args: |
@@ -357,11 +369,11 @@ jobs:
             "VERSION=${{ needs.get-version.outputs.major_version }}"
           pull: true
           load: true
-          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}-fresh-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
+          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.project }}-fresh-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
 
       - uses: docker/build-push-action@v3
         with:
-          file: .github/docker/Dockerfile.${{ matrix.project }}-${{ matrix.os }}
+          file: .github/docker/Dockerfile.${{ env.project }}-${{ matrix.os }}
           target: web_fresh
           context: .
           build-args: |
@@ -369,11 +381,11 @@ jobs:
             "VERSION=${{ needs.get-version.outputs.major_version }}"
           pull: false
           push: true
-          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}-fresh-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
+          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.project }}-fresh-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
 
       - uses: docker/build-push-action@v3
         with:
-          file: .github/docker/Dockerfile.${{ matrix.project }}-${{ matrix.os }}
+          file: .github/docker/Dockerfile.${{ env.project }}-${{ matrix.os }}
           target: web_standard
           context: .
           build-args: |
@@ -381,11 +393,11 @@ jobs:
             "VERSION=${{ needs.get-version.outputs.major_version }}"
           pull: true
           load: true
-          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
+          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.project }}-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
 
       - uses: docker/build-push-action@v3
         with:
-          file: .github/docker/Dockerfile.${{ matrix.project }}-${{ matrix.os }}
+          file: .github/docker/Dockerfile.${{ env.project }}-${{ matrix.os }}
           target: web_standard
           context: .
           build-args: |
@@ -393,7 +405,7 @@ jobs:
             "VERSION=${{ needs.get-version.outputs.major_version }}"
           pull: false
           push: true
-          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
+          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.project }}-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
 
       - name: Setup docker slim
         run: |
@@ -414,10 +426,10 @@ jobs:
               --include-path-file .github/docker/slim-configuration/include-path.txt \
               --include-bin-file .github/docker/slim-configuration/include-bin.txt \
               --path-perms-file .github/docker/slim-configuration/path-perms.txt \
-              --tag ${{ matrix.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }} \
-              ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}$IMAGE_SUFFIX-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
-            docker tag ${{ matrix.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }} ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
-            docker push ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
+              --tag ${{ env.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }} \
+              ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.project }}$IMAGE_SUFFIX-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
+            docker tag ${{ env.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }} ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
+            docker push ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.project }}$IMAGE_SUFFIX-slim-${{ matrix.os }}:${{ github.head_ref || github.ref_name }}
           done
         shell: bash
 
